package main

import (
	"bytes"
	"go/format"
	"os"
	"path/filepath"
	"text/template"
)

const header = `// Code generated by go generate; DO NOT EDIT.
//
// To regenerate: doppler run -- go generate ./internal/sqlite

`

var typeTemplate = template.Must(template.New("type").Parse(header + `package sqlite
{{if .NeedsJSON}}
import "encoding/json"
{{end}}
// {{.StructName}} represents a row in the {{.Name}} table.
type {{.StructName}} struct {
{{- range .Columns}}
	{{.FieldName}} {{.GoType}} ` + "`" + `json:"{{.Name}}"` + "`" + ` // {{.PgType}}
{{- end}}
}
`))

var schemaTemplate = template.Must(template.New("schema").Parse(header + `package sqlite

import "encoding/json"

// Schema defines the tables that will be synced from the control plane.
type Schema struct {
	Tables []SchemaTable ` + "`" + `json:"tables"` + "`" + `
}

// SchemaTable defines a single table in the sync schema.
type SchemaTable struct {
	Name    string         ` + "`" + `json:"name"` + "`" + `
	Columns []SchemaColumn ` + "`" + `json:"columns"` + "`" + `
}

// SchemaColumn defines a column in a synced table.
type SchemaColumn struct {
	Name string ` + "`" + `json:"name"` + "`" + `
	Type string ` + "`" + `json:"type"` + "`" + ` // "text", "integer", "real"
}

// DefaultSchema returns the schema for tables synced from the control plane.
func DefaultSchema() Schema {
	return Schema{
		Tables: []SchemaTable{
{{- range .Tables}}
			{
				Name: "{{.Name}}",
				Columns: []SchemaColumn{
{{- range .Columns}}
					{Name: "{{.Name}}", Type: "{{.SQLiteType}}"},
{{- end}}
				},
			},
{{- end}}
		},
	}
}

// JSON returns the schema as a JSON string for powersync_replace_schema().
func (s Schema) JSON() (string, error) {
	data, err := json.Marshal(s)
	if err != nil {
		return "", err
	}
	return string(data), nil
}
`))

// WriteTypeFile generates a Go file for a single table type.
func WriteTypeFile(outputDir string, table Table) error {
	var buf bytes.Buffer
	if err := typeTemplate.Execute(&buf, table); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(outputDir, table.FileName), formatted, 0o644)
}

// WriteSchemaFile generates the schema.go file.
func WriteSchemaFile(outputDir string, tables []Table) error {
	data := struct {
		Tables []Table
	}{
		Tables: tables,
	}

	var buf bytes.Buffer
	if err := schemaTemplate.Execute(&buf, data); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(outputDir, "schema.generated.go"), formatted, 0o644)
}
