// Package main generates SQLite schema types from PowerSync.
//
// It boots a temp database with the PowerSync extension and embedded schema,
// then reflects the schema back to a SQL file for sqlc.
//
// Prerequisites: Run `go generate ./internal/powersync` first to generate schema.json.
//
// Usage:
//
//	doppler run -- go generate ./internal/sqlite
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/usetero/cli/internal/powersync"
	"github.com/usetero/cli/internal/sqlite"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	// Create temp database
	tmpDir, err := os.MkdirTemp("", "tero-generate-*")
	if err != nil {
		return fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	dbPath := filepath.Join(tmpDir, "generate.db")
	db, err := sqlite.Open(dbPath)
	if err != nil {
		return fmt.Errorf("open database: %w", err)
	}
	defer db.Close()

	// Load PowerSync extension
	extPath, err := powersync.ExtensionPath()
	if err != nil {
		return fmt.Errorf("get extension path: %w", err)
	}

	if err := db.LoadExtension(extPath, "sqlite3_powersync_init"); err != nil {
		return fmt.Errorf("load extension: %w", err)
	}

	fmt.Println("Applying embedded PowerSync schema...")

	// Apply embedded schema to create views (just like runtime)
	if _, err := db.Exec("SELECT powersync_replace_schema(?)", powersync.SchemaJSON()); err != nil {
		return fmt.Errorf("replace schema: %w", err)
	}

	fmt.Println("Reflecting schema from SQLite...")

	// Reflect schema to SQL
	schemaSQL, err := reflectSchema(db)
	if err != nil {
		return fmt.Errorf("reflect schema: %w", err)
	}

	// Write schema.sql
	outputDir := mustGetwd()
	schemaPath := filepath.Join(outputDir, "schema.sql")
	if err := os.WriteFile(schemaPath, []byte(schemaSQL), 0o644); err != nil {
		return fmt.Errorf("write schema.sql: %w", err)
	}

	fmt.Printf("Wrote %s\n", schemaPath)

	// Run sqlc generate
	fmt.Println("Running sqlc generate...")
	if err := runSqlc(); err != nil {
		return fmt.Errorf("sqlc generate: %w", err)
	}

	fmt.Println("Done!")
	return nil
}

// reflectSchema reflects the schema from sqlite_master to SQL.
// It extracts CREATE VIEW statements for PowerSync views (excluding internal tables).
func reflectSchema(db *sqlite.DB) (string, error) {
	// Query all views created by PowerSync (they have the auto-generated comment)
	rows, err := db.Query(`
		SELECT name, sql
		FROM sqlite_master
		WHERE type = 'view'
		AND sql LIKE '%-- powersync-auto-generated%'
		ORDER BY name
	`)
	if err != nil {
		return "", fmt.Errorf("query sqlite_master: %w", err)
	}
	defer rows.Close()

	var views []struct {
		name string
		sql  string
	}

	for rows.Next() {
		var name, sql string
		if err := rows.Scan(&name, &sql); err != nil {
			return "", fmt.Errorf("scan row: %w", err)
		}
		views = append(views, struct {
			name string
			sql  string
		}{name, sql})
	}

	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("iterate rows: %w", err)
	}

	// Sort by name for deterministic output
	sort.Slice(views, func(i, j int) bool {
		return views[i].name < views[j].name
	})

	// Convert views to CREATE TABLE statements for sqlc
	// (sqlc needs tables, not views, to generate types)
	var statements []string
	statements = append(statements, "-- Code generated by go generate; DO NOT EDIT.")
	statements = append(statements, "-- Source: PowerSync schema reflected from sqlite_master")
	statements = append(statements, "")

	for _, view := range views {
		// Parse the view to extract column info and generate CREATE TABLE
		tableSQL, err := viewToTable(db, view.name)
		if err != nil {
			return "", fmt.Errorf("convert view %s: %w", view.name, err)
		}
		statements = append(statements, tableSQL)
		statements = append(statements, "")
	}

	return strings.Join(statements, "\n"), nil
}

// viewToTable converts a view definition to a CREATE TABLE statement.
// It queries the view's column info using PRAGMA table_info.
func viewToTable(db *sqlite.DB, viewName string) (string, error) {
	// Get column info from the view
	rows, err := db.Query(fmt.Sprintf("PRAGMA table_info(%s)", viewName))
	if err != nil {
		return "", fmt.Errorf("pragma table_info: %w", err)
	}
	defer rows.Close()

	var columns []string
	seen := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, colType string
		var notNull, pk int
		var dfltValue *string

		if err := rows.Scan(&cid, &name, &colType, &notNull, &dfltValue, &pk); err != nil {
			return "", fmt.Errorf("scan column: %w", err)
		}

		// Skip columns with invalid names (like "id:1" aliases from SQLite)
		if strings.Contains(name, ":") {
			continue
		}

		// Skip duplicates
		if seen[name] {
			continue
		}
		seen[name] = true

		// Normalize type for sqlc
		sqlType := normalizeSQLiteType(colType)

		col := fmt.Sprintf("    %s %s", name, sqlType)
		if pk == 1 {
			col += " PRIMARY KEY"
		}
		if notNull == 1 && pk != 1 {
			col += " NOT NULL"
		}
		columns = append(columns, col)
	}

	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("iterate columns: %w", err)
	}

	return fmt.Sprintf("CREATE TABLE %s (\n%s\n);", viewName, strings.Join(columns, ",\n")), nil
}

// normalizeSQLiteType normalizes SQLite type names for sqlc.
func normalizeSQLiteType(t string) string {
	t = strings.ToUpper(strings.TrimSpace(t))
	switch t {
	case "INT", "INTEGER", "BIGINT", "SMALLINT", "TINYINT":
		return "INTEGER"
	case "REAL", "DOUBLE", "FLOAT":
		return "REAL"
	case "BLOB":
		return "BLOB"
	default:
		return "TEXT"
	}
}

// runSqlc runs sqlc generate from the repository root.
func runSqlc() error {
	// Find repo root (where sqlc.yaml lives)
	repoRoot, err := findRepoRoot()
	if err != nil {
		return err
	}

	cmd := exec.Command("sqlc", "generate")
	cmd.Dir = repoRoot
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// findRepoRoot finds the repository root by looking for go.mod.
func findRepoRoot() (string, error) {
	dir := mustGetwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repository root (go.mod)")
		}
		dir = parent
	}
}

func mustGetwd() string {
	dir, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	return dir
}
