// Code generated by sqlite/generate. DO NOT EDIT.

package catalog

type LogEventFacts struct {
	IdentityProfile            *IdentityProfile
	AttributionProfile         *AttributionProfile
	StructureProfile           *StructureProfile
	EventRoleProfile           *EventRoleProfile
	EmissionTemplateProfile    *EmissionTemplateProfile
	OperatorProminenceProfile  *OperatorProminenceProfile
	ObservabilityValueProfile  *ObservabilityValueProfile
	LevelExpectationProfile    *LevelExpectationProfile
	PayloadHygieneProfile      *PayloadHygieneProfile
	ContextCompletenessProfile *ContextCompletenessProfile
	SensitiveDataProfile       *SensitiveDataProfile
}

// IdentityProfile Captures the intrinsic event identity: what happened, what durable thing it is about, the durable outcome if one exists, and the stable operation when that matters.
type IdentityProfile struct {
	// The coarse stable thing that happened.
	Action string `json:"action"`
	// The coarse stable class the subject belongs to.
	SubjectClass string `json:"subject_class"`
	// What specific durable thing the event is fundamentally about.
	Subject string `json:"subject"`
	// The durable outcome, when one exists.
	Outcome string `json:"outcome"`
	// The stable named operation, when one exists.
	Operation string `json:"operation"`
}

type AttributionProfilePeerRole string

const (
	AttributionProfilePeerRoleUser       AttributionProfilePeerRole = "user"
	AttributionProfilePeerRoleService    AttributionProfilePeerRole = "service"
	AttributionProfilePeerRoleDependency AttributionProfilePeerRole = "dependency"
	AttributionProfilePeerRoleBot        AttributionProfilePeerRole = "bot"
	AttributionProfilePeerRoleProbe      AttributionProfilePeerRole = "probe"
	AttributionProfilePeerRoleUnknown    AttributionProfilePeerRole = "unknown"
)

type AttributionProfilePeerKind string

const (
	AttributionProfilePeerKindDatabase       AttributionProfilePeerKind = "database"
	AttributionProfilePeerKindCache          AttributionProfilePeerKind = "cache"
	AttributionProfilePeerKindQueue          AttributionProfilePeerKind = "queue"
	AttributionProfilePeerKindObjectStore    AttributionProfilePeerKind = "object_store"
	AttributionProfilePeerKindInternalApi    AttributionProfilePeerKind = "internal_api"
	AttributionProfilePeerKindExternalApi    AttributionProfilePeerKind = "external_api"
	AttributionProfilePeerKindPaymentService AttributionProfilePeerKind = "payment_service"
	AttributionProfilePeerKindEmailService   AttributionProfilePeerKind = "email_service"
	AttributionProfilePeerKindUnknown        AttributionProfilePeerKind = "unknown"
)

type AttributionProfileBoundarySide string

const (
	AttributionProfileBoundarySideInternal   AttributionProfileBoundarySide = "internal"
	AttributionProfileBoundarySideUpstream   AttributionProfileBoundarySide = "upstream"
	AttributionProfileBoundarySideDownstream AttributionProfileBoundarySide = "downstream"
)

// AttributionProfile Captures the separate materially involved peer boundary around the event when one is clearly exposed.
type AttributionProfile struct {
	// The most specific stable peer identity materially involved, if one is clear.
	PeerLabel *string `json:"peer_label,omitempty"`
	// The coarse operational role of the materially involved peer.
	PeerRole *AttributionProfilePeerRole `json:"peer_role,omitempty"`
	// The operational kind of the materially involved peer.
	PeerKind *AttributionProfilePeerKind `json:"peer_kind,omitempty"`
	// The coarse side of the materially involved peer boundary.
	BoundarySide *AttributionProfileBoundarySide `json:"boundary_side,omitempty"`
}

type StructureProfileBodyKind string

const (
	StructureProfileBodyKindEmpty       StructureProfileBodyKind = "empty"
	StructureProfileBodyKindGeneric     StructureProfileBodyKind = "generic"
	StructureProfileBodyKindOpaque      StructureProfileBodyKind = "opaque"
	StructureProfileBodyKindDescriptive StructureProfileBodyKind = "descriptive"
)

type StructureProfileGaps string

const (
	StructureProfileGapsEmptyCapture             StructureProfileGaps = "empty_capture"
	StructureProfileGapsMissingStreamPartitions  StructureProfileGaps = "missing_stream_partitions"
	StructureProfileGapsMissingExecutionGrouping StructureProfileGaps = "missing_execution_grouping"
)

// StructureProfile Captures the event-facing structural summary from log stream structure, including real stream and execution keys.
type StructureProfile struct {
	// The deterministic body usefulness class.
	BodyKind StructureProfileBodyKind `json:"body_kind"`
	// Whether the event is a fragment rather than a complete semantic event.
	IsFragment bool `json:"is_fragment"`
	// The stable message or structural template when one is visible.
	Template string `json:"template"`
	// The canonical stream correlation keys observed in structure analysis.
	StreamCorrelationKeys []string `json:"stream_correlation_keys"`
	// The canonical execution or work-unit correlation keys observed in structure analysis.
	ExecutionCorrelationKeys []string `json:"execution_correlation_keys"`
	// Meaningful structural gaps observed during structure analysis.
	Gaps []StructureProfileGaps `json:"gaps"`
}

type EventRoleProfileRole string

const (
	EventRoleProfileRoleSignal        EventRoleProfileRole = "signal"
	EventRoleProfileRoleMarker        EventRoleProfileRole = "marker"
	EventRoleProfileRoleDebugArtifact EventRoleProfileRole = "debug_artifact"
	EventRoleProfileRoleGarbled       EventRoleProfileRole = "garbled"
)

// EventRoleProfile Classifies the event's coarse observability artifact role as signal, marker, debug artifact, or garbled output.
type EventRoleProfile struct {
	// The event's coarse observability role.
	Role EventRoleProfileRole `json:"role"`
}

// EmissionTemplateProfile Captures the stable emitted wording this event follows as an instrumentation artifact.
type EmissionTemplateProfile struct {
	// The stable emitted wording for this event, with descriptive placeholders for clearly variable slots.
	Template string `json:"template"`
}

type OperatorProminenceProfileOperatorProminence string

const (
	OperatorProminenceProfileOperatorProminenceNone OperatorProminenceProfileOperatorProminence = "none"
	OperatorProminenceProfileOperatorProminenceLow  OperatorProminenceProfileOperatorProminence = "low"
	OperatorProminenceProfileOperatorProminenceHigh OperatorProminenceProfileOperatorProminence = "high"
)

// OperatorProminenceProfile Captures how prominently the event deserves to appear in a normal operator workflow.
type OperatorProminenceProfile struct {
	// How prominently this event deserves to appear in normal operator workflows.
	OperatorProminence OperatorProminenceProfileOperatorProminence `json:"operator_prominence"`
}

type ObservabilityValueProfileInstanceValue string

const (
	ObservabilityValueProfileInstanceValueNone ObservabilityValueProfileInstanceValue = "none"
	ObservabilityValueProfileInstanceValueLow  ObservabilityValueProfileInstanceValue = "low"
	ObservabilityValueProfileInstanceValueHigh ObservabilityValueProfileInstanceValue = "high"
)

type ObservabilityValueProfileCollectionGain string

const (
	ObservabilityValueProfileCollectionGainNone ObservabilityValueProfileCollectionGain = "none"
	ObservabilityValueProfileCollectionGainLow  ObservabilityValueProfileCollectionGain = "low"
	ObservabilityValueProfileCollectionGainHigh ObservabilityValueProfileCollectionGain = "high"
)

// ObservabilityValueProfile Captures how much one representative event matters on its own and how much extra value the larger collection adds beyond one representative copy.
type ObservabilityValueProfile struct {
	// How helpful one representative event instance is on its own.
	InstanceValue ObservabilityValueProfileInstanceValue `json:"instance_value"`
	// How much additional observability value the larger collection adds beyond one representative instance.
	CollectionGain ObservabilityValueProfileCollectionGain `json:"collection_gain"`
}

type LevelExpectationProfileExpectedLevel string

const (
	LevelExpectationProfileExpectedLevelDebug LevelExpectationProfileExpectedLevel = "debug"
	LevelExpectationProfileExpectedLevelInfo  LevelExpectationProfileExpectedLevel = "info"
	LevelExpectationProfileExpectedLevelWarn  LevelExpectationProfileExpectedLevel = "warn"
	LevelExpectationProfileExpectedLevelError LevelExpectationProfileExpectedLevel = "error"
)

// LevelExpectationProfile Captures the normalized severity level the event deserves.
type LevelExpectationProfile struct {
	// The severity level this event should use.
	ExpectedLevel LevelExpectationProfileExpectedLevel `json:"expected_level"`
}

type PayloadHygieneProfileBodyWeight string

const (
	PayloadHygieneProfileBodyWeightLean     PayloadHygieneProfileBodyWeight = "lean"
	PayloadHygieneProfileBodyWeightModerate PayloadHygieneProfileBodyWeight = "moderate"
	PayloadHygieneProfileBodyWeightHeavy    PayloadHygieneProfileBodyWeight = "heavy"
)

type PayloadHygieneProfileAttributeWeight string

const (
	PayloadHygieneProfileAttributeWeightLean     PayloadHygieneProfileAttributeWeight = "lean"
	PayloadHygieneProfileAttributeWeightModerate PayloadHygieneProfileAttributeWeight = "moderate"
	PayloadHygieneProfileAttributeWeightHeavy    PayloadHygieneProfileAttributeWeight = "heavy"
)

// PayloadHygieneProfile Captures where event-local payload weight lives across the body and event attributes, plus the exact costly paths.
type PayloadHygieneProfile struct {
	// The weight carried by the log body itself.
	BodyWeight PayloadHygieneProfileBodyWeight `json:"body_weight"`
	// The weight carried by event attributes.
	AttributeWeight PayloadHygieneProfileAttributeWeight `json:"attribute_weight"`
	// Concrete paths that materially increase cost or clutter.
	ExpensivePaths []FieldPath `json:"expensive_paths,omitempty"`
}

type ContextCompletenessProfileTraceContext string

const (
	ContextCompletenessProfileTraceContextComplete      ContextCompletenessProfileTraceContext = "complete"
	ContextCompletenessProfileTraceContextPartial       ContextCompletenessProfileTraceContext = "partial"
	ContextCompletenessProfileTraceContextMissing       ContextCompletenessProfileTraceContext = "missing"
	ContextCompletenessProfileTraceContextNotApplicable ContextCompletenessProfileTraceContext = "not_applicable"
)

type ContextCompletenessProfileWorkUnitContext string

const (
	ContextCompletenessProfileWorkUnitContextComplete      ContextCompletenessProfileWorkUnitContext = "complete"
	ContextCompletenessProfileWorkUnitContextPartial       ContextCompletenessProfileWorkUnitContext = "partial"
	ContextCompletenessProfileWorkUnitContextMissing       ContextCompletenessProfileWorkUnitContext = "missing"
	ContextCompletenessProfileWorkUnitContextNotApplicable ContextCompletenessProfileWorkUnitContext = "not_applicable"
)

// ContextCompletenessProfile Captures whether the event carries the trace and work-unit identifiers that should exist on this event, and names any concrete required paths that are missing.
type ContextCompletenessProfile struct {
	// Whether the event carries the distributed trace identifiers it should have.
	TraceContext ContextCompletenessProfileTraceContext `json:"trace_context"`
	// Whether the event carries the concrete request, job, workflow, batch, message, or similar execution identifier it should have.
	WorkUnitContext ContextCompletenessProfileWorkUnitContext `json:"work_unit_context"`
	// Concrete correlation paths that should exist on this event but are missing.
	MissingRequiredPaths []FieldPath `json:"missing_required_paths"`
}

// SensitiveDataProfile Lists the exact event paths that actually expose secrets, payment data, PII, or PHI in sampled evidence.
type SensitiveDataProfile struct {
	// Exact paths that expose secrets or credentials.
	SecretPaths []FieldPath `json:"secret_paths"`
	// Exact paths that expose payment data.
	PaymentPaths []FieldPath `json:"payment_paths"`
	// Exact paths that expose actionable personally identifying data.
	PiiPaths []FieldPath `json:"pii_paths"`
	// Exact paths that expose protected health information.
	PhiPaths []FieldPath `json:"phi_paths"`
}
