// Code generated by sqlite/generate. DO NOT EDIT.

package catalog

import (
	"encoding/json"
)

// LogMatchersRow is the storage-level payload consumed by generated decoders for LogMatchers.
type LogMatchersRow struct {
	Namespace string
	FactType  string
	Value     string
}

func DecodeLogMatchers(rows []LogMatchersRow) (LogMatchers, error) {
	var out LogMatchers
	if len(rows) == 0 || rows[0].Value == "" {
		return out, nil
	}
	if err := json.Unmarshal([]byte(rows[0].Value), &out); err != nil {
		return nil, err
	}
	return out, nil
}
