// Code generated by sqlite/generate. DO NOT EDIT.

package catalog

// LogMatchers is generated from log_events.matchers.
type LogMatchers []LogMatchersItem

type LogMatchersItem struct {
	// Path to field as array of segments
	FieldPath []string `json:"field_path"`
	// Match operator: exact, contains, starts_with, ends_with, regex, exists, missing
	MatchType string `json:"match_type"`
	// Value to match against
	MatchValue string `json:"match_value"`
	// Whether matching is case-insensitive (optional)
	CaseInsensitive bool `json:"case_insensitive"`
	// Whether to invert match result (optional)
	Negate *bool `json:"negate,omitempty"`
}
