// Code generated by sqlite/generate. DO NOT EDIT.

package catalog

import (
	"encoding/json"
	"fmt"
)

// LogEventFactsRow is the storage-level payload consumed by generated decoders for LogEventFacts.
type LogEventFactsRow struct {
	Namespace string
	FactType  string
	Value     string
}

func DecodeLogEventFacts(rows []LogEventFactsRow) (LogEventFacts, error) {
	var out LogEventFacts
	for _, row := range rows {
		switch row.Namespace + ":" + row.FactType {
		case "identity:identity_profile":
			if out.IdentityProfile != nil {
				continue
			}
			var decoded IdentityProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return LogEventFacts{}, fmt.Errorf("decode IdentityProfile: %w", err)
			}
			out.IdentityProfile = &decoded
		case "attribution:attribution_profile":
			if out.AttributionProfile != nil {
				continue
			}
			var decoded AttributionProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return LogEventFacts{}, fmt.Errorf("decode AttributionProfile: %w", err)
			}
			out.AttributionProfile = &decoded
		case "structural:structure_profile":
			if out.StructureProfile != nil {
				continue
			}
			var decoded StructureProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return LogEventFacts{}, fmt.Errorf("decode StructureProfile: %w", err)
			}
			out.StructureProfile = &decoded
		case "artifact:event_role_profile":
			if out.EventRoleProfile != nil {
				continue
			}
			var decoded EventRoleProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return LogEventFacts{}, fmt.Errorf("decode EventRoleProfile: %w", err)
			}
			out.EventRoleProfile = &decoded
		case "artifact:emission_template_profile":
			if out.EmissionTemplateProfile != nil {
				continue
			}
			var decoded EmissionTemplateProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return LogEventFacts{}, fmt.Errorf("decode EmissionTemplateProfile: %w", err)
			}
			out.EmissionTemplateProfile = &decoded
		case "quality:operator_prominence_profile":
			if out.OperatorProminenceProfile != nil {
				continue
			}
			var decoded OperatorProminenceProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return LogEventFacts{}, fmt.Errorf("decode OperatorProminenceProfile: %w", err)
			}
			out.OperatorProminenceProfile = &decoded
		case "quality:observability_value_profile":
			if out.ObservabilityValueProfile != nil {
				continue
			}
			var decoded ObservabilityValueProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return LogEventFacts{}, fmt.Errorf("decode ObservabilityValueProfile: %w", err)
			}
			out.ObservabilityValueProfile = &decoded
		case "quality:level_expectation_profile":
			if out.LevelExpectationProfile != nil {
				continue
			}
			var decoded LevelExpectationProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return LogEventFacts{}, fmt.Errorf("decode LevelExpectationProfile: %w", err)
			}
			out.LevelExpectationProfile = &decoded
		case "quality:payload_hygiene_profile":
			if out.PayloadHygieneProfile != nil {
				continue
			}
			var decoded PayloadHygieneProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return LogEventFacts{}, fmt.Errorf("decode PayloadHygieneProfile: %w", err)
			}
			out.PayloadHygieneProfile = &decoded
		case "quality:context_completeness_profile":
			if out.ContextCompletenessProfile != nil {
				continue
			}
			var decoded ContextCompletenessProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return LogEventFacts{}, fmt.Errorf("decode ContextCompletenessProfile: %w", err)
			}
			out.ContextCompletenessProfile = &decoded
		case "compliance:sensitive_data_profile":
			if out.SensitiveDataProfile != nil {
				continue
			}
			var decoded SensitiveDataProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return LogEventFacts{}, fmt.Errorf("decode SensitiveDataProfile: %w", err)
			}
			out.SensitiveDataProfile = &decoded
		}
	}
	return out, nil
}
