// Code generated by sqlite/generate. DO NOT EDIT.

package catalog

import (
	"encoding/json"
	"fmt"
)

// ServiceFactsRow is the storage-level payload consumed by generated decoders for ServiceFacts.
type ServiceFactsRow struct {
	Namespace string
	FactType  string
	Value     string
}

func DecodeServiceFacts(rows []ServiceFactsRow) (ServiceFacts, error) {
	var out ServiceFacts
	for _, row := range rows {
		switch row.Namespace + ":" + row.FactType {
		case "semantic:service_profile":
			if out.ServiceProfile != nil {
				continue
			}
			var decoded ServiceProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return ServiceFacts{}, fmt.Errorf("decode ServiceProfile: %w", err)
			}
			out.ServiceProfile = &decoded
		case "semantic:telemetry_profile":
			if out.TelemetryProfile != nil {
				continue
			}
			var decoded TelemetryProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return ServiceFacts{}, fmt.Errorf("decode TelemetryProfile: %w", err)
			}
			out.TelemetryProfile = &decoded
		case "operational:actionability_profile":
			if out.ActionabilityProfile != nil {
				continue
			}
			var decoded ActionabilityProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return ServiceFacts{}, fmt.Errorf("decode ActionabilityProfile: %w", err)
			}
			out.ActionabilityProfile = &decoded
		case "operational:shared_payload_hygiene_profile":
			if out.SharedPayloadHygieneProfile != nil {
				continue
			}
			var decoded SharedPayloadHygieneProfile
			if err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {
				return ServiceFacts{}, fmt.Errorf("decode SharedPayloadHygieneProfile: %w", err)
			}
			out.SharedPayloadHygieneProfile = &decoded
		}
	}
	return out, nil
}
