// Code generated by sqlite/generate. DO NOT EDIT.

package catalog

type ServiceFacts struct {
	ServiceProfile              *ServiceProfile
	TelemetryProfile            *TelemetryProfile
	ActionabilityProfile        *ActionabilityProfile
	SharedPayloadHygieneProfile *SharedPayloadHygieneProfile
}

type ServiceProfileServiceCategory string

const (
	ServiceProfileServiceCategoryCustomerApi            ServiceProfileServiceCategory = "customer_api"
	ServiceProfileServiceCategoryInternalApi            ServiceProfileServiceCategory = "internal_api"
	ServiceProfileServiceCategoryBackgroundWorker       ServiceProfileServiceCategory = "background_worker"
	ServiceProfileServiceCategoryIntegrationAdapter     ServiceProfileServiceCategory = "integration_adapter"
	ServiceProfileServiceCategoryDataPipeline           ServiceProfileServiceCategory = "data_pipeline"
	ServiceProfileServiceCategoryPlatformComponent      ServiceProfileServiceCategory = "platform_component"
	ServiceProfileServiceCategoryMessageBroker          ServiceProfileServiceCategory = "message_broker"
	ServiceProfileServiceCategoryDatabase               ServiceProfileServiceCategory = "database"
	ServiceProfileServiceCategoryCache                  ServiceProfileServiceCategory = "cache"
	ServiceProfileServiceCategoryObservabilityComponent ServiceProfileServiceCategory = "observability_component"
	ServiceProfileServiceCategoryUnknown                ServiceProfileServiceCategory = "unknown"
)

type ServiceProfileSystemRoles string

const (
	ServiceProfileSystemRolesRequestHandling      ServiceProfileSystemRoles = "request_handling"
	ServiceProfileSystemRolesBackgroundProcessing ServiceProfileSystemRoles = "background_processing"
	ServiceProfileSystemRolesIntegration          ServiceProfileSystemRoles = "integration"
	ServiceProfileSystemRolesStateManagement      ServiceProfileSystemRoles = "state_management"
	ServiceProfileSystemRolesMessaging            ServiceProfileSystemRoles = "messaging"
	ServiceProfileSystemRolesPlatformOperations   ServiceProfileSystemRoles = "platform_operations"
)

// ServiceProfile Describes what the service appears to be, what it is primarily responsible for, and the major role it plays in the system.
type ServiceProfile struct {
	// A concise grounded summary of what the service appears to do.
	Summary string `json:"summary"`
	// The best-fitting broad service category.
	ServiceCategory ServiceProfileServiceCategory `json:"service_category"`
	// Short grounded statements of the service's primary responsibilities.
	PrimaryResponsibilities []string `json:"primary_responsibilities"`
	// Major system roles the service appears to play.
	SystemRoles []ServiceProfileSystemRoles `json:"system_roles"`
}

type TelemetryProfileDominantLogPatterns string

const (
	TelemetryProfileDominantLogPatternsRequestLogs              TelemetryProfileDominantLogPatterns = "request_logs"
	TelemetryProfileDominantLogPatternsJobLogs                  TelemetryProfileDominantLogPatterns = "job_logs"
	TelemetryProfileDominantLogPatternsIntegrationLogs          TelemetryProfileDominantLogPatterns = "integration_logs"
	TelemetryProfileDominantLogPatternsLifecycleLogs            TelemetryProfileDominantLogPatterns = "lifecycle_logs"
	TelemetryProfileDominantLogPatternsPlatformHousekeepingLogs TelemetryProfileDominantLogPatterns = "platform_housekeeping_logs"
	TelemetryProfileDominantLogPatternsAuditLogs                TelemetryProfileDominantLogPatterns = "audit_logs"
)

type TelemetryProfileTelemetryCharacteristics string

const (
	TelemetryProfileTelemetryCharacteristicsHighVolume           TelemetryProfileTelemetryCharacteristics = "high_volume"
	TelemetryProfileTelemetryCharacteristicsErrorHeavy           TelemetryProfileTelemetryCharacteristics = "error_heavy"
	TelemetryProfileTelemetryCharacteristicsInfraHeavy           TelemetryProfileTelemetryCharacteristics = "infra_heavy"
	TelemetryProfileTelemetryCharacteristicsIntegrationHeavy     TelemetryProfileTelemetryCharacteristics = "integration_heavy"
	TelemetryProfileTelemetryCharacteristicsStateTransitionHeavy TelemetryProfileTelemetryCharacteristics = "state_transition_heavy"
	TelemetryProfileTelemetryCharacteristicsMixedSignalQuality   TelemetryProfileTelemetryCharacteristics = "mixed_signal_quality"
)

// TelemetryProfile Describes the broad shape of telemetry this service emits, including the main log patterns and notable telemetry characteristics.
type TelemetryProfile struct {
	// A concise grounded summary of what the service's logs mostly look like.
	Summary string `json:"summary"`
	// The main classes of logs the service appears to emit.
	DominantLogPatterns []TelemetryProfileDominantLogPatterns `json:"dominant_log_patterns"`
	// Plain-language descriptions of the main operational roles visible in the logs.
	DominantOperationalRoles []string `json:"dominant_operational_roles"`
	// Broad traits of the service's telemetry.
	TelemetryCharacteristics []TelemetryProfileTelemetryCharacteristics `json:"telemetry_characteristics"`
}

type ActionabilityProfileServiceOrigin string

const (
	ActionabilityProfileServiceOriginFirstParty          ActionabilityProfileServiceOrigin = "first_party"
	ActionabilityProfileServiceOriginThirdParty          ActionabilityProfileServiceOrigin = "third_party"
	ActionabilityProfileServiceOriginOpenSourceComponent ActionabilityProfileServiceOrigin = "open_source_component"
	ActionabilityProfileServiceOriginManagedPlatform     ActionabilityProfileServiceOrigin = "managed_platform"
	ActionabilityProfileServiceOriginUnknown             ActionabilityProfileServiceOrigin = "unknown"
)

type ActionabilityProfileOwnershipLevel string

const (
	ActionabilityProfileOwnershipLevelOwnedCode      ActionabilityProfileOwnershipLevel = "owned_code"
	ActionabilityProfileOwnershipLevelConfiguredOnly ActionabilityProfileOwnershipLevel = "configured_only"
	ActionabilityProfileOwnershipLevelOperatedOnly   ActionabilityProfileOwnershipLevel = "operated_only"
	ActionabilityProfileOwnershipLevelUnknown        ActionabilityProfileOwnershipLevel = "unknown"
)

type ActionabilityProfileChangeLevers string

const (
	ActionabilityProfileChangeLeversApplicationCode  ActionabilityProfileChangeLevers = "application_code"
	ActionabilityProfileChangeLeversServiceConfig    ActionabilityProfileChangeLevers = "service_config"
	ActionabilityProfileChangeLeversDeploymentConfig ActionabilityProfileChangeLevers = "deployment_config"
	ActionabilityProfileChangeLeversCollectorConfig  ActionabilityProfileChangeLevers = "collector_config"
	ActionabilityProfileChangeLeversPlatformTuning   ActionabilityProfileChangeLevers = "platform_tuning"
)

// ActionabilityProfile Describes how much direct control the team likely has over this service and which change levers are most realistic when a finding affects it.
type ActionabilityProfile struct {
	// A concise grounded summary of how actionable findings against this service are likely to be.
	Summary string `json:"summary"`
	// Where this service likely comes from.
	ServiceOrigin ActionabilityProfileServiceOrigin `json:"service_origin"`
	// How much direct control the team likely has over behavior changes.
	OwnershipLevel ActionabilityProfileOwnershipLevel `json:"ownership_level"`
	// The most realistic levers available for changing this service or its telemetry.
	ChangeLevers []ActionabilityProfileChangeLevers `json:"change_levers"`
}

type SharedPayloadHygieneProfileSharedPayloadWeight string

const (
	SharedPayloadHygieneProfileSharedPayloadWeightLean     SharedPayloadHygieneProfileSharedPayloadWeight = "lean"
	SharedPayloadHygieneProfileSharedPayloadWeightModerate SharedPayloadHygieneProfileSharedPayloadWeight = "moderate"
	SharedPayloadHygieneProfileSharedPayloadWeightHeavy    SharedPayloadHygieneProfileSharedPayloadWeight = "heavy"
)

type SharedPayloadHygieneProfileSharedEnrichmentNoise string

const (
	SharedPayloadHygieneProfileSharedEnrichmentNoiseNone   SharedPayloadHygieneProfileSharedEnrichmentNoise = "none"
	SharedPayloadHygieneProfileSharedEnrichmentNoiseLow    SharedPayloadHygieneProfileSharedEnrichmentNoise = "low"
	SharedPayloadHygieneProfileSharedEnrichmentNoiseMedium SharedPayloadHygieneProfileSharedEnrichmentNoise = "medium"
	SharedPayloadHygieneProfileSharedEnrichmentNoiseHigh   SharedPayloadHygieneProfileSharedEnrichmentNoise = "high"
)

// SharedPayloadHygieneProfile Describes the overall weight and non-essential noise of shared service-level telemetry metadata, along with the exact expensive shared paths.
type SharedPayloadHygieneProfile struct {
	// The overall payload weight of the shared service-level metadata.
	SharedPayloadWeight SharedPayloadHygieneProfileSharedPayloadWeight `json:"shared_payload_weight"`
	// How much non-essential shared enrichment surrounds the service's logs.
	SharedEnrichmentNoise SharedPayloadHygieneProfileSharedEnrichmentNoise `json:"shared_enrichment_noise"`
	// Concrete shared paths that materially increase cost or clutter across this service's logs.
	ExpensiveSharedPaths []FieldPath `json:"expensive_shared_paths"`
}
