version: "3"

vars:
  CONTROL_PLANE_DIR: ../control-plane

tasks:
  # Client generation
  client:generate:
    desc: Generate GraphQL client from running control-plane API (requires control plane at localhost:8081)
    dir: pkg/client
    cmds:
      - npx get-graphql-schema http://localhost:8081/graphql > schema.graphql
      - go run github.com/Khan/genqlient
    sources:
      - "queries/*.graphql"
    generates:
      - "generated.go"

  # Build tasks
  build:
    desc: Build the tero CLI binary
    cmds:
      - go build -o tero cmd/tero/main.go
    sources:
      - "**/*.go"
    generates:
      - "tero"

  # Development tasks
  run:
    desc: Run tero without building (fast iteration)
    cmds:
      - go run ./cmd/tero {{.CLI_ARGS}}

  test:
    desc: Run tests
    cmds:
      - go test ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - |
        if ! command -v golangci-lint &> /dev/null; then
          echo "golangci-lint not found. Installing..."
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        fi
      - $(go env GOPATH)/bin/golangci-lint run ./...

  lint:scripts:
    desc: Lint shell scripts with shellcheck
    cmds:
      - shellcheck scripts/*.sh

  do:
    desc: Format, lint, and test
    cmds:
      - go fmt ./...
      - golangci-lint run ./...
      - task: lint:scripts
      - task: test

  signoff:
    desc: Full validation before push (format, lint, test, build)
    aliases: ["sign", "s"]
    cmds:
      - task: do
      - task: build
      - task: install:test
      - gh signoff

  dev:
    desc: Generate client and build
    cmds:
      - task: client:generate
      - task: build

  # Installation
  install:
    desc: Install tero CLI to GOPATH
    deps: [build]
    cmds:
      - go install cmd/tero/main.go

  # Clean
  clean:
    desc: Clean build artifacts and Go caches
    cmds:
      - rm -f tero
      - rm -rf dist/
      - go clean -cache -testcache -modcache
      - 'echo "Cleaned: binary and Go caches"'

  reset:
    desc: Reset development environment (auth, config, logs)
    cmds:
      - task: reset:auth
      - task: reset:config

  reset:auth:
    desc: Clear authentication tokens from keychain
    cmds:
      - security delete-generic-password -s "tero-cli" -a "access_token" 2>/dev/null || true
      - security delete-generic-password -s "tero-cli" -a "refresh_token" 2>/dev/null || true
      - 'echo "Cleared: authentication tokens"'

  reset:config:
    desc: Clear config files and logs
    cmds:
      - rm -f /tmp/tero.log
      - rm -rf ~/.tero/
      - rm -rf ~/.config/tero/
      - 'echo "Cleared: config files and logs"'

  # Release tasks
  build:version:
    desc: Build with version information injected (same as CI)
    cmds:
      - |
        VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "dev")
        go build -ldflags "-X main.version=${VERSION}" -o tero cmd/tero/main.go
        echo "Built tero ${VERSION}"

  release:check:
    desc: Check recent commits follow conventional commit format
    cmds:
      - |
        echo "Recent commits (should follow conventional commit format):"
        git log --oneline -10
        echo ""
        echo "Valid prefixes: feat, fix, chore, docs, refactor, test, ci, perf, revert"
        echo "Example: feat: add new feature"

  release:snapshot:
    desc: Test GoReleaser build locally without publishing
    cmds:
      - goreleaser release --snapshot --clean --skip=publish
      - echo ""
      - echo "Build artifacts in dist/ directory"
      - ls -lh dist/*.tar.gz dist/*.zip 2>/dev/null || true

  install:test:
    desc: Test install.sh script with released version
    cmds:
      - |
        echo "Testing install script..."
        export TERO_INSTALL_DIR="/tmp/tero-install-test"
        rm -rf "$TERO_INSTALL_DIR"

        # Test help
        sh scripts/install.sh --help

        # Test actual installation with latest release
        echo ""
        echo "Installing latest release to $TERO_INSTALL_DIR..."
        sh scripts/install.sh -y

        # Verify installation
        if [ -x "$TERO_INSTALL_DIR/tero" ]; then
          echo ""
          echo "✓ Installation successful!"
          "$TERO_INSTALL_DIR/tero" --version
        else
          echo "✗ Installation failed"
          exit 1
        fi

        # Cleanup
        rm -rf "$TERO_INSTALL_DIR"
