version: "3"

vars:
  CONTROL_PLANE_DIR: ../control-plane

tasks:
  # Client generation
  client:generate:
    desc: Generate GraphQL client from running control-plane API (requires control plane at localhost:8081)
    dir: pkg/client
    cmds:
      - npx get-graphql-schema http://localhost:8081/graphql > schema.graphql
      - go run github.com/Khan/genqlient
    sources:
      - "queries/*.graphql"
    generates:
      - "generated.go"

  # Build tasks
  build:
    desc: Build the tero CLI binary
    cmds:
      - go build -o tero cmd/tero/main.go
    sources:
      - "**/*.go"
    generates:
      - "tero"

  # Development tasks
  run:
    desc: Run tero without building (fast iteration)
    cmds:
      - go run ./cmd/tero {{.CLI_ARGS}}

  test:
    desc: Run tests
    cmds:
      - go test ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - |
        if ! command -v golangci-lint &> /dev/null; then
          echo "golangci-lint not found. Installing..."
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        fi
      - $(go env GOPATH)/bin/golangci-lint run ./...

  do:
    desc: Format, lint, and test
    cmds:
      - go fmt ./...
      - golangci-lint run ./...
      - task: test

  signoff:
    desc: Full validation before push (format, lint, test, build)
    aliases: ["sign", "s"]
    cmds:
      - task: do
      - task: build
      - gh signoff

  dev:
    desc: Generate client and build
    cmds:
      - task: client:generate
      - task: build

  # Installation
  install:
    desc: Install tero CLI to GOPATH
    deps: [build]
    cmds:
      - go install cmd/tero/main.go

  # Clean
  clean:
    desc: Clean build artifacts and Go caches
    cmds:
      - rm -f tero
      - rm -rf dist/
      - go clean -cache -testcache -modcache
      - 'echo "Cleaned: binary and Go caches"'

  reset:
    desc: Reset development environment (logs and preferences)
    cmds:
      - rm -f /tmp/tero.log
      - rm -rf ~/.tero/
      - rm -rf ~/.config/tero/
      - 'echo "Reset: logs and preferences cleared"'

  # Release tasks
  build:version:
    desc: Build with version information injected (same as CI)
    cmds:
      - |
        VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "dev")
        go build -ldflags "-X main.version=${VERSION}" -o tero cmd/tero/main.go
        echo "Built tero ${VERSION}"

  release:check:
    desc: Check recent commits follow conventional commit format
    cmds:
      - |
        echo "Recent commits (should follow conventional commit format):"
        git log --oneline -10
        echo ""
        echo "Valid prefixes: feat, fix, chore, docs, refactor, test, ci, perf, revert"
        echo "Example: feat: add new feature"

  release:snapshot:
    desc: Test GoReleaser build locally without publishing
    cmds:
      - goreleaser release --snapshot --clean --skip=publish
      - echo ""
      - echo "Build artifacts in dist/ directory"
      - ls -lh dist/*.tar.gz dist/*.zip 2>/dev/null || true
