// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package servicesdb

import (
	"context"
)

type Querier interface {
	ListAllServiceFacts(ctx context.Context) ([]ListAllServiceFactsRow, error)
	ListServiceFacts(ctx context.Context, serviceID *string) ([]ListServiceFactsRow, error)
	ListServices(ctx context.Context) ([]ListServicesRow, error)
}

var _ Querier = (*Queries)(nil)
