// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package servicesdb

import (
	"context"
)

const listAllServiceFacts = `-- name: ListAllServiceFacts :many
SELECT id, account_id, service_id, fact_group, fact_type, namespace, value, version, created_at
FROM service_facts
ORDER BY service_id ASC, namespace ASC, fact_type ASC, created_at DESC
`

type ListAllServiceFactsRow struct {
	ID        *string
	AccountID *string
	ServiceID *string
	FactGroup *string
	FactType  *string
	Namespace *string
	Value     *string
	Version   *int64
	CreatedAt *string
}

func (q *Queries) ListAllServiceFacts(ctx context.Context) ([]ListAllServiceFactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllServiceFacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllServiceFactsRow
	for rows.Next() {
		var i ListAllServiceFactsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ServiceID,
			&i.FactGroup,
			&i.FactType,
			&i.Namespace,
			&i.Value,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceFacts = `-- name: ListServiceFacts :many
SELECT id, account_id, service_id, fact_group, fact_type, namespace, value, version, created_at
FROM service_facts
WHERE service_id = ?
ORDER BY namespace ASC, fact_type ASC, created_at DESC
`

type ListServiceFactsRow struct {
	ID        *string
	AccountID *string
	ServiceID *string
	FactGroup *string
	FactType  *string
	Namespace *string
	Value     *string
	Version   *int64
	CreatedAt *string
}

func (q *Queries) ListServiceFacts(ctx context.Context, serviceID *string) ([]ListServiceFactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listServiceFacts, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceFactsRow
	for rows.Next() {
		var i ListServiceFactsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ServiceID,
			&i.FactGroup,
			&i.FactType,
			&i.Namespace,
			&i.Value,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, account_id, name, enabled, initial_weekly_log_count, created_at
FROM services
ORDER BY name ASC
`

type ListServicesRow struct {
	ID                    *string
	AccountID             *string
	Name                  *string
	Enabled               *int64
	InitialWeeklyLogCount *int64
	CreatedAt             *string
}

func (q *Queries) ListServices(ctx context.Context) ([]ListServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesRow
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Enabled,
			&i.InitialWeeklyLogCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
