// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package workspacesdb

import (
	"context"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) error
	Delete(ctx context.Context, id string) error
	ListByAccount(ctx context.Context, accountID string) ([]Workspace, error)
}

var _ Querier = (*Queries)(nil)
