// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package workspacesdb

import (
	"context"
)

const create = `-- name: Create :exec
INSERT INTO workspaces (id, account_id, name, created_at)
VALUES (?, ?, ?, ?)
`

type CreateParams struct {
	ID        *string
	AccountID *string
	Name      *string
	CreatedAt *string
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.ExecContext(ctx, create,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const delete = `-- name: Delete :exec
DELETE FROM workspaces
WHERE id = ?
`

func (q *Queries) Delete(ctx context.Context, id *string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const listByAccount = `-- name: ListByAccount :many
SELECT id, account_id, name, created_at
FROM workspaces
WHERE account_id = ?
ORDER BY created_at DESC
`

type ListByAccountRow struct {
	ID        *string
	AccountID *string
	Name      *string
	CreatedAt *string
}

func (q *Queries) ListByAccount(ctx context.Context, accountID *string) ([]ListByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListByAccountRow
	for rows.Next() {
		var i ListByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
