// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package messagesdb

import (
	"context"
)

const create = `-- name: Create :exec
INSERT INTO messages (id, conversation_id, role, content, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateParams struct {
	ID             string
	ConversationID string
	Role           string
	Content        string
	CreatedAt      string
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.ExecContext(ctx, create,
		arg.ID,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const delete = `-- name: Delete :exec
DELETE FROM messages
WHERE id = ?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const listByConversation = `-- name: ListByConversation :many
SELECT id, conversation_id, role, content, created_at
FROM messages
WHERE conversation_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListByConversation(ctx context.Context, conversationID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
