// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package messagesdb

type Account struct {
	ID        string
	Name      string
	CreatedAt string
}

type Conversation struct {
	ID        string
	Title     *string
	CreatedAt string
}

type Message struct {
	ID             string
	ConversationID string
	Role           string
	Content        string
	CreatedAt      string
}

type Workspace struct {
	ID        string
	AccountID string
	Name      string
	CreatedAt string
}
