// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package messagesdb

type Conversation struct {
	ID          *string
	AccountID   *string
	CreatedAt   *string
	Title       *string
	UserID      *string
	WorkspaceID *string
}

type DatadogAccount struct {
	ID                *string
	AccountID         *string
	CostPerGbIngested *float64
	CreatedAt         *string
	Name              *string
	Site              *string
}

type DatadogAccountStatusesCache struct {
	ID                             *string
	AccountID                      *string
	CurrentBytesPerHour            *float64
	CurrentBytesUsdPerHour         *float64
	CurrentEventsPerHour           *float64
	CurrentServiceEventsPerHour    *float64
	CurrentServiceVolumeUsdPerHour *float64
	CurrentTotalUsdPerHour         *float64
	CurrentVolumeUsdPerHour        *float64
	DatadogAccountID               *string
	DisabledServices               *int64
	EffectiveBytesPerHour          *float64
	EffectiveBytesUsdPerHour       *float64
	EffectiveEventsPerHour         *float64
	EffectiveLogEventCount         *int64
	EffectiveSavedBytesPerHour     *float64
	EffectiveSavedBytesUsdPerHour  *float64
	EffectiveSavedEventsPerHour    *float64
	EffectiveSavedTotalUsdPerHour  *float64
	EffectiveSavedVolumeUsdPerHour *float64
	EffectiveTotalUsdPerHour       *float64
	EffectiveVolumeUsdPerHour      *float64
	Health                         *string
	InactiveServices               *int64
	LogActiveServices              *int64
	LogEventAnalyzedCount          *int64
	LogEventCount                  *int64
	LogServiceCount                *int64
	OkServices                     *int64
	PreviewBytesPerHour            *float64
	PreviewBytesUsdPerHour         *float64
	PreviewEventsPerHour           *float64
	PreviewLogEventCount           *int64
	PreviewSavedBytesPerHour       *float64
	PreviewSavedBytesUsdPerHour    *float64
	PreviewSavedEventsPerHour      *float64
	PreviewSavedTotalUsdPerHour    *float64
	PreviewSavedVolumeUsdPerHour   *float64
	PreviewTotalUsdPerHour         *float64
	PreviewVolumeUsdPerHour        *float64
	ReadyForUse                    *int64
}

type DatadogLogIndex struct {
	ID                          *string
	AccountID                   *string
	CostPerMillionEventsIndexed *float64
	CreatedAt                   *string
	DatadogAccountID            *string
	Name                        *string
}

type Finding struct {
	ID             *string
	AccountID      *string
	ClosedAt       *string
	CreatedAt      *string
	Details        *string
	Domain         *string
	Fingerprint    *string
	LogEventID     *string
	ProblemVersion *int64
	ScopeKind      *string
	ServiceID      *string
	Type           *string
}

type FindingCuration struct {
	ID                    *string
	AccountID             *string
	Body                  *string
	CreatedAt             *string
	Disposition           *string
	FindingID             *string
	FindingProblemVersion *int64
	Priority              *string
	Title                 *string
	Version               *int64
}

type FindingLogEvent struct {
	ID         *string
	AccountID  *string
	CreatedAt  *string
	FindingID  *string
	LogEventID *string
}

type FindingPlan struct {
	ID                *string
	AccountID         *string
	CreatedAt         *string
	FindingCurationID *string
	FindingID         *string
	OpenQuestions     *string
	Rationale         *string
	Revision          *int64
	Status            *string
	Steps             *string
	Summary           *string
	Title             *string
	Version           *int64
}

type FindingStatusesCache struct {
	ID                            *string
	AccountID                     *string
	CurrentBytesPerHour           *float64
	CurrentBytesUsdPerHour        *float64
	CurrentEventsPerHour          *float64
	CurrentTotalUsdPerHour        *float64
	CurrentVolumeUsdPerHour       *float64
	FindingCreatedAt              *string
	FindingID                     *string
	FindingUpdatedAt              *string
	IsolatedBytesPerHour          *float64
	IsolatedBytesUsdPerHour       *float64
	IsolatedEventsPerHour         *float64
	IsolatedSavedBytesPerHour     *float64
	IsolatedSavedBytesUsdPerHour  *float64
	IsolatedSavedEventsPerHour    *float64
	IsolatedSavedTotalUsdPerHour  *float64
	IsolatedSavedVolumeUsdPerHour *float64
	IsolatedTotalUsdPerHour       *float64
	IsolatedVolumeUsdPerHour      *float64
	LogEventCount                 *int64
	LogEventID                    *string
	PlanStatus                    *string
	PlanUpdatedAt                 *string
	ScopeKind                     *string
	ServiceID                     *string
}

type LogEvent struct {
	ID                    *string
	AccountID             *string
	BaselineAvgBytes      *float64
	BaselineVolumePerHour *float64
	CreatedAt             *string
	Description           *string
	Matchers              *string
	Name                  *string
	ServiceID             *string
	Severity              *string
}

type LogEventFact struct {
	ID           *string
	AccountID    *string
	CreatedAt    *string
	FactName     *string
	LogEventID   *string
	SliceName    *string
	SliceVersion *int64
	Value        *string
}

type LogEventPolicy struct {
	ID         *string
	AccountID  *string
	CompiledAt *string
	CreatedAt  *string
	FindingID  *string
	Kind       *string
	LogEventID *string
	Spec       *string
}

type LogEventStatusesCache struct {
	ID                             *string
	AccountID                      *string
	CurrentBytesPerHour            *float64
	CurrentBytesUsdPerHour         *float64
	CurrentEventsPerHour           *float64
	CurrentTotalUsdPerHour         *float64
	CurrentVolumeUsdPerHour        *float64
	EffectiveBytesPerHour          *float64
	EffectiveBytesUsdPerHour       *float64
	EffectiveEventsPerHour         *float64
	EffectiveSavedBytesPerHour     *float64
	EffectiveSavedBytesUsdPerHour  *float64
	EffectiveSavedEventsPerHour    *float64
	EffectiveSavedTotalUsdPerHour  *float64
	EffectiveSavedVolumeUsdPerHour *float64
	EffectiveTotalUsdPerHour       *float64
	EffectiveVolumeUsdPerHour      *float64
	HasBeenAnalyzed                *int64
	HasEffectivePolicy             *int64
	HasPreviewPolicy               *int64
	HasVolumes                     *int64
	LogEventID                     *string
	PreviewBytesPerHour            *float64
	PreviewBytesUsdPerHour         *float64
	PreviewEventsPerHour           *float64
	PreviewSavedBytesPerHour       *float64
	PreviewSavedBytesUsdPerHour    *float64
	PreviewSavedEventsPerHour      *float64
	PreviewSavedTotalUsdPerHour    *float64
	PreviewSavedVolumeUsdPerHour   *float64
	PreviewTotalUsdPerHour         *float64
	PreviewVolumeUsdPerHour        *float64
	ServiceID                      *string
}

type Message struct {
	ID             *string
	AccountID      *string
	Content        *string
	ConversationID *string
	CreatedAt      *string
	Model          *string
	Role           *string
	StopReason     *string
}

type Service struct {
	ID                    *string
	AccountID             *string
	CreatedAt             *string
	Enabled               *int64
	InitialWeeklyLogCount *int64
	Name                  *string
}

type ServiceFact struct {
	ID        *string
	AccountID *string
	CreatedAt *string
	FactGroup *string
	FactType  *string
	Namespace *string
	ServiceID *string
	Value     *string
	Version   *int64
}

type ServiceStatusesCache struct {
	ID                               *string
	AccountID                        *string
	CurrentBytesPerHour              *float64
	CurrentBytesUsdPerHour           *float64
	CurrentEventsPerHour             *float64
	CurrentServiceDebugEventsPerHour *float64
	CurrentServiceErrorEventsPerHour *float64
	CurrentServiceEventsPerHour      *float64
	CurrentServiceInfoEventsPerHour  *float64
	CurrentServiceOtherEventsPerHour *float64
	CurrentServiceVolumeUsdPerHour   *float64
	CurrentServiceWarnEventsPerHour  *float64
	CurrentTotalUsdPerHour           *float64
	CurrentVolumeUsdPerHour          *float64
	DatadogAccountID                 *string
	EffectiveBytesPerHour            *float64
	EffectiveBytesUsdPerHour         *float64
	EffectiveEventsPerHour           *float64
	EffectiveLogEventCount           *int64
	EffectiveSavedBytesPerHour       *float64
	EffectiveSavedBytesUsdPerHour    *float64
	EffectiveSavedEventsPerHour      *float64
	EffectiveSavedTotalUsdPerHour    *float64
	EffectiveSavedVolumeUsdPerHour   *float64
	EffectiveTotalUsdPerHour         *float64
	EffectiveVolumeUsdPerHour        *float64
	Health                           *string
	LogEventAnalyzedCount            *int64
	LogEventCount                    *int64
	PreviewBytesPerHour              *float64
	PreviewBytesUsdPerHour           *float64
	PreviewEventsPerHour             *float64
	PreviewLogEventCount             *int64
	PreviewSavedBytesPerHour         *float64
	PreviewSavedBytesUsdPerHour      *float64
	PreviewSavedEventsPerHour        *float64
	PreviewSavedTotalUsdPerHour      *float64
	PreviewSavedVolumeUsdPerHour     *float64
	PreviewTotalUsdPerHour           *float64
	PreviewVolumeUsdPerHour          *float64
	ServiceID                        *string
}

type Team struct {
	ID          *string
	AccountID   *string
	CreatedAt   *string
	Name        *string
	WorkspaceID *string
}

type Workspace struct {
	ID        *string
	AccountID *string
	CreatedAt *string
	Name      *string
	Purpose   *string
}
