// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package messagesdb

import (
	"context"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) error
	Delete(ctx context.Context, id string) error
	ListByConversation(ctx context.Context, conversationID string) ([]Message, error)
}

var _ Querier = (*Queries)(nil)
