-- Code generated by go generate; DO NOT EDIT.
-- Source: PowerSync schema reflected from sqlite_master

CREATE TABLE conversation_contexts (
    id TEXT,
    account_id TEXT,
    added_by TEXT,
    conversation_id TEXT,
    created_at TEXT,
    entity_id TEXT,
    entity_type TEXT
);

CREATE TABLE conversations (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    title TEXT,
    user_id TEXT,
    view_id TEXT,
    workspace_id TEXT
);

CREATE TABLE datadog_account_statuses_cache (
    id TEXT,
    account_id TEXT,
    approved_recommendation_count INTEGER,
    current_bytes_per_hour REAL,
    current_bytes_usd_per_hour REAL,
    current_events_per_hour REAL,
    current_service_events_per_hour REAL,
    current_service_volume_usd_per_hour REAL,
    current_total_usd_per_hour REAL,
    current_volume_usd_per_hour REAL,
    datadog_account_id TEXT,
    disabled_services INTEGER,
    dismissed_recommendation_count INTEGER,
    estimated_bytes_per_hour REAL,
    estimated_bytes_usd_per_hour REAL,
    estimated_events_per_hour REAL,
    estimated_total_usd_per_hour REAL,
    estimated_volume_usd_per_hour REAL,
    health TEXT,
    impact_bytes_per_hour REAL,
    impact_bytes_usd_per_hour REAL,
    impact_events_per_hour REAL,
    impact_total_usd_per_hour REAL,
    impact_volume_usd_per_hour REAL,
    inactive_services INTEGER,
    log_active_services INTEGER,
    log_event_analyzed_count INTEGER,
    log_event_count INTEGER,
    log_service_count INTEGER,
    ok_services INTEGER,
    pending_recommendation_count INTEGER,
    policy_pending_critical_count INTEGER,
    policy_pending_high_count INTEGER,
    policy_pending_low_count INTEGER,
    policy_pending_medium_count INTEGER,
    ready_for_use INTEGER,
    recommendation_count INTEGER
);

CREATE TABLE datadog_accounts (
    id TEXT,
    account_id TEXT,
    cost_per_gb_ingested REAL,
    created_at TEXT,
    name TEXT,
    site TEXT
);

CREATE TABLE datadog_log_indexes (
    id TEXT,
    account_id TEXT,
    cost_per_million_events_indexed REAL,
    created_at TEXT,
    datadog_account_id TEXT,
    name TEXT
);

CREATE TABLE log_event_recommendations (
    id TEXT,
    account_id TEXT,
    action TEXT,
    analysis TEXT,
    approved_at TEXT,
    approved_baseline_avg_bytes REAL,
    approved_baseline_volume_per_hour REAL,
    approved_by TEXT,
    category TEXT,
    category_type TEXT,
    created_at TEXT,
    dismissed_at TEXT,
    dismissed_by TEXT,
    log_event_id TEXT,
    severity TEXT,
    subjective INTEGER,
    workspace_id TEXT
);

CREATE TABLE log_event_statuses_cache (
    id TEXT,
    account_id TEXT,
    approved_recommendation_count INTEGER,
    current_bytes_per_hour REAL,
    current_bytes_usd_per_hour REAL,
    current_events_per_hour REAL,
    current_total_usd_per_hour REAL,
    current_volume_usd_per_hour REAL,
    dismissed_recommendation_count INTEGER,
    effective_policy_enabled INTEGER,
    estimated_bytes_per_hour REAL,
    estimated_bytes_usd_per_hour REAL,
    estimated_events_per_hour REAL,
    estimated_total_usd_per_hour REAL,
    estimated_volume_usd_per_hour REAL,
    has_been_analyzed INTEGER,
    has_volumes INTEGER,
    impact_bytes_per_hour REAL,
    impact_bytes_usd_per_hour REAL,
    impact_events_per_hour REAL,
    impact_total_usd_per_hour REAL,
    impact_volume_usd_per_hour REAL,
    log_event_id TEXT,
    pending_recommendation_count INTEGER,
    policy_pending_critical_count INTEGER,
    policy_pending_high_count INTEGER,
    policy_pending_low_count INTEGER,
    policy_pending_medium_count INTEGER,
    recommendation_count INTEGER,
    service_id TEXT
);

CREATE TABLE log_events (
    id TEXT,
    account_id TEXT,
    baseline_avg_bytes REAL,
    baseline_volume_per_hour REAL,
    created_at TEXT,
    description TEXT,
    event_nature TEXT,
    examples TEXT,
    matchers TEXT,
    name TEXT,
    service_id TEXT,
    severity TEXT,
    signal_purpose TEXT
);

CREATE TABLE messages (
    id TEXT,
    account_id TEXT,
    content TEXT,
    conversation_id TEXT,
    created_at TEXT,
    model TEXT,
    role TEXT,
    stop_reason TEXT
);

CREATE TABLE recommendation_category_statuses_cache (
    id TEXT,
    account_id TEXT,
    action TEXT,
    approved_count INTEGER,
    boundary TEXT,
    category TEXT,
    category_type TEXT,
    dismissed_count INTEGER,
    display_name TEXT,
    estimated_bytes_reduction_per_hour REAL,
    estimated_cost_reduction_per_hour_bytes_usd REAL,
    estimated_cost_reduction_per_hour_usd REAL,
    estimated_cost_reduction_per_hour_volume_usd REAL,
    estimated_volume_reduction_per_hour REAL,
    events_with_volumes INTEGER,
    pending_count INTEGER,
    policy_pending_critical_count INTEGER,
    policy_pending_high_count INTEGER,
    policy_pending_low_count INTEGER,
    policy_pending_medium_count INTEGER,
    principle TEXT,
    subjective INTEGER,
    total_event_count INTEGER
);

CREATE TABLE recommendation_statuses_cache (
    id TEXT,
    account_id TEXT,
    action TEXT,
    approved_at TEXT,
    category TEXT,
    category_type TEXT,
    created_at TEXT,
    current_bytes_per_hour REAL,
    current_bytes_usd_per_hour REAL,
    current_events_per_hour REAL,
    current_total_usd_per_hour REAL,
    current_volume_usd_per_hour REAL,
    dismissed_at TEXT,
    estimated_bytes_per_hour REAL,
    estimated_bytes_usd_per_hour REAL,
    estimated_events_per_hour REAL,
    estimated_total_usd_per_hour REAL,
    estimated_volume_usd_per_hour REAL,
    impact_bytes_per_hour REAL,
    impact_bytes_usd_per_hour REAL,
    impact_events_per_hour REAL,
    impact_total_usd_per_hour REAL,
    impact_volume_usd_per_hour REAL,
    log_event_id TEXT,
    log_event_name TEXT,
    recommendation_id TEXT,
    service_id TEXT,
    service_name TEXT,
    severity TEXT,
    status TEXT,
    subjective INTEGER,
    survival_rate REAL,
    workspace_id TEXT
);

CREATE TABLE service_statuses_cache (
    id TEXT,
    account_id TEXT,
    approved_recommendation_count INTEGER,
    current_bytes_per_hour REAL,
    current_bytes_usd_per_hour REAL,
    current_events_per_hour REAL,
    current_service_debug_events_per_hour REAL,
    current_service_error_events_per_hour REAL,
    current_service_events_per_hour REAL,
    current_service_info_events_per_hour REAL,
    current_service_other_events_per_hour REAL,
    current_service_volume_usd_per_hour REAL,
    current_service_warn_events_per_hour REAL,
    current_total_usd_per_hour REAL,
    current_volume_usd_per_hour REAL,
    datadog_account_id TEXT,
    dismissed_recommendation_count INTEGER,
    estimated_bytes_per_hour REAL,
    estimated_bytes_usd_per_hour REAL,
    estimated_events_per_hour REAL,
    estimated_total_usd_per_hour REAL,
    estimated_volume_usd_per_hour REAL,
    health TEXT,
    impact_bytes_per_hour REAL,
    impact_bytes_usd_per_hour REAL,
    impact_events_per_hour REAL,
    impact_total_usd_per_hour REAL,
    impact_volume_usd_per_hour REAL,
    log_event_analyzed_count INTEGER,
    log_event_count INTEGER,
    pending_recommendation_count INTEGER,
    policy_pending_critical_count INTEGER,
    policy_pending_high_count INTEGER,
    policy_pending_low_count INTEGER,
    policy_pending_medium_count INTEGER,
    recommendation_count INTEGER,
    service_id TEXT
);

CREATE TABLE services (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    description TEXT,
    enabled INTEGER,
    initial_weekly_log_count INTEGER,
    name TEXT
);

CREATE TABLE teams (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    name TEXT,
    workspace_id TEXT
);

CREATE TABLE view_favorites (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    user_id TEXT,
    view_id TEXT
);

CREATE TABLE views (
    id TEXT,
    account_id TEXT,
    conversation_id TEXT,
    created_at TEXT,
    created_by TEXT,
    entity_type TEXT,
    forked_from_id TEXT,
    message_id TEXT,
    query TEXT
);

CREATE TABLE workspaces (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    name TEXT,
    purpose TEXT
);
