// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: findings.sql

package findingsdb

import (
	"context"
)

const listFindings = `-- name: ListFindings :many
SELECT
    f.id,
    f.account_id,
    f.service_id,
    f.log_event_id,
    f.domain,
    f.scope_kind,
    f.type,
    f.problem_version,
    f.fingerprint,
    f.details,
    f.closed_at,
    f.created_at,
    fc.disposition,
    fc.title,
    fc.body,
    fc.priority,
    fs.plan_status,
    fp.title AS plan_title,
    fp.summary AS plan_summary,
    fp.rationale AS plan_rationale,
    fp.open_questions AS plan_open_questions,
    fp.steps AS plan_steps,
    fp.revision AS plan_revision,
    fp.version AS plan_version,
    fs.isolated_events_per_hour,
    fs.isolated_total_usd_per_hour,
    fs.log_event_count,
    fs.finding_updated_at,
    fs.plan_updated_at
FROM findings f
LEFT JOIN finding_curations fc ON fc.id = (
    SELECT fc2.id
    FROM finding_curations fc2
    WHERE fc2.finding_id = f.id
    ORDER BY fc2.version DESC, fc2.created_at DESC
    LIMIT 1
)
LEFT JOIN finding_statuses_cache fs ON fs.finding_id = f.id
LEFT JOIN finding_plans fp ON fp.id = (
    SELECT fp2.id
    FROM finding_plans fp2
    WHERE fp2.finding_id = f.id
    ORDER BY fp2.version DESC, fp2.revision DESC, fp2.created_at DESC
    LIMIT 1
)
ORDER BY f.domain ASC, f.type ASC, f.created_at DESC
`

type ListFindingsRow struct {
	ID                      *string
	AccountID               *string
	ServiceID               *string
	LogEventID              *string
	Domain                  *string
	ScopeKind               *string
	Type                    *string
	ProblemVersion          *int64
	Fingerprint             *string
	Details                 *string
	ClosedAt                *string
	CreatedAt               *string
	Disposition             *string
	Title                   *string
	Body                    *string
	Priority                *string
	PlanStatus              *string
	PlanTitle               *string
	PlanSummary             *string
	PlanRationale           *string
	PlanOpenQuestions       *string
	PlanSteps               *string
	PlanRevision            *int64
	PlanVersion             *int64
	IsolatedEventsPerHour   *float64
	IsolatedTotalUsdPerHour *float64
	LogEventCount           *int64
	FindingUpdatedAt        *string
	PlanUpdatedAt           *string
}

func (q *Queries) ListFindings(ctx context.Context) ([]ListFindingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingsRow
	for rows.Next() {
		var i ListFindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ServiceID,
			&i.LogEventID,
			&i.Domain,
			&i.ScopeKind,
			&i.Type,
			&i.ProblemVersion,
			&i.Fingerprint,
			&i.Details,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.Disposition,
			&i.Title,
			&i.Body,
			&i.Priority,
			&i.PlanStatus,
			&i.PlanTitle,
			&i.PlanSummary,
			&i.PlanRationale,
			&i.PlanOpenQuestions,
			&i.PlanSteps,
			&i.PlanRevision,
			&i.PlanVersion,
			&i.IsolatedEventsPerHour,
			&i.IsolatedTotalUsdPerHour,
			&i.LogEventCount,
			&i.FindingUpdatedAt,
			&i.PlanUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByDomain = `-- name: ListFindingsByDomain :many
SELECT
    f.id,
    f.account_id,
    f.service_id,
    f.log_event_id,
    f.domain,
    f.scope_kind,
    f.type,
    f.problem_version,
    f.fingerprint,
    f.details,
    f.closed_at,
    f.created_at,
    fc.disposition,
    fc.title,
    fc.body,
    fc.priority,
    fs.plan_status,
    fp.title AS plan_title,
    fp.summary AS plan_summary,
    fp.rationale AS plan_rationale,
    fp.open_questions AS plan_open_questions,
    fp.steps AS plan_steps,
    fp.revision AS plan_revision,
    fp.version AS plan_version,
    fs.isolated_events_per_hour,
    fs.isolated_total_usd_per_hour,
    fs.log_event_count,
    fs.finding_updated_at,
    fs.plan_updated_at
FROM findings f
LEFT JOIN finding_curations fc ON fc.id = (
    SELECT fc2.id
    FROM finding_curations fc2
    WHERE fc2.finding_id = f.id
    ORDER BY fc2.version DESC, fc2.created_at DESC
    LIMIT 1
)
LEFT JOIN finding_statuses_cache fs ON fs.finding_id = f.id
LEFT JOIN finding_plans fp ON fp.id = (
    SELECT fp2.id
    FROM finding_plans fp2
    WHERE fp2.finding_id = f.id
    ORDER BY fp2.version DESC, fp2.revision DESC, fp2.created_at DESC
    LIMIT 1
)
WHERE f.domain = ?
ORDER BY f.type ASC, f.created_at DESC
`

type ListFindingsByDomainRow struct {
	ID                      *string
	AccountID               *string
	ServiceID               *string
	LogEventID              *string
	Domain                  *string
	ScopeKind               *string
	Type                    *string
	ProblemVersion          *int64
	Fingerprint             *string
	Details                 *string
	ClosedAt                *string
	CreatedAt               *string
	Disposition             *string
	Title                   *string
	Body                    *string
	Priority                *string
	PlanStatus              *string
	PlanTitle               *string
	PlanSummary             *string
	PlanRationale           *string
	PlanOpenQuestions       *string
	PlanSteps               *string
	PlanRevision            *int64
	PlanVersion             *int64
	IsolatedEventsPerHour   *float64
	IsolatedTotalUsdPerHour *float64
	LogEventCount           *int64
	FindingUpdatedAt        *string
	PlanUpdatedAt           *string
}

func (q *Queries) ListFindingsByDomain(ctx context.Context, domain *string) ([]ListFindingsByDomainRow, error) {
	rows, err := q.db.QueryContext(ctx, listFindingsByDomain, domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingsByDomainRow
	for rows.Next() {
		var i ListFindingsByDomainRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ServiceID,
			&i.LogEventID,
			&i.Domain,
			&i.ScopeKind,
			&i.Type,
			&i.ProblemVersion,
			&i.Fingerprint,
			&i.Details,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.Disposition,
			&i.Title,
			&i.Body,
			&i.Priority,
			&i.PlanStatus,
			&i.PlanTitle,
			&i.PlanSummary,
			&i.PlanRationale,
			&i.PlanOpenQuestions,
			&i.PlanSteps,
			&i.PlanRevision,
			&i.PlanVersion,
			&i.IsolatedEventsPerHour,
			&i.IsolatedTotalUsdPerHour,
			&i.LogEventCount,
			&i.FindingUpdatedAt,
			&i.PlanUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByService = `-- name: ListFindingsByService :many
SELECT
    f.id,
    f.account_id,
    f.service_id,
    f.log_event_id,
    f.domain,
    f.scope_kind,
    f.type,
    f.problem_version,
    f.fingerprint,
    f.details,
    f.closed_at,
    f.created_at,
    fc.disposition,
    fc.title,
    fc.body,
    fc.priority,
    fs.plan_status,
    fp.title AS plan_title,
    fp.summary AS plan_summary,
    fp.rationale AS plan_rationale,
    fp.open_questions AS plan_open_questions,
    fp.steps AS plan_steps,
    fp.revision AS plan_revision,
    fp.version AS plan_version,
    fs.isolated_events_per_hour,
    fs.isolated_total_usd_per_hour,
    fs.log_event_count,
    fs.finding_updated_at,
    fs.plan_updated_at
FROM findings f
LEFT JOIN finding_curations fc ON fc.id = (
    SELECT fc2.id
    FROM finding_curations fc2
    WHERE fc2.finding_id = f.id
    ORDER BY fc2.version DESC, fc2.created_at DESC
    LIMIT 1
)
LEFT JOIN finding_statuses_cache fs ON fs.finding_id = f.id
LEFT JOIN finding_plans fp ON fp.id = (
    SELECT fp2.id
    FROM finding_plans fp2
    WHERE fp2.finding_id = f.id
    ORDER BY fp2.version DESC, fp2.revision DESC, fp2.created_at DESC
    LIMIT 1
)
WHERE f.service_id = ?
ORDER BY f.domain ASC, f.type ASC, f.created_at DESC
`

type ListFindingsByServiceRow struct {
	ID                      *string
	AccountID               *string
	ServiceID               *string
	LogEventID              *string
	Domain                  *string
	ScopeKind               *string
	Type                    *string
	ProblemVersion          *int64
	Fingerprint             *string
	Details                 *string
	ClosedAt                *string
	CreatedAt               *string
	Disposition             *string
	Title                   *string
	Body                    *string
	Priority                *string
	PlanStatus              *string
	PlanTitle               *string
	PlanSummary             *string
	PlanRationale           *string
	PlanOpenQuestions       *string
	PlanSteps               *string
	PlanRevision            *int64
	PlanVersion             *int64
	IsolatedEventsPerHour   *float64
	IsolatedTotalUsdPerHour *float64
	LogEventCount           *int64
	FindingUpdatedAt        *string
	PlanUpdatedAt           *string
}

func (q *Queries) ListFindingsByService(ctx context.Context, serviceID *string) ([]ListFindingsByServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, listFindingsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingsByServiceRow
	for rows.Next() {
		var i ListFindingsByServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ServiceID,
			&i.LogEventID,
			&i.Domain,
			&i.ScopeKind,
			&i.Type,
			&i.ProblemVersion,
			&i.Fingerprint,
			&i.Details,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.Disposition,
			&i.Title,
			&i.Body,
			&i.Priority,
			&i.PlanStatus,
			&i.PlanTitle,
			&i.PlanSummary,
			&i.PlanRationale,
			&i.PlanOpenQuestions,
			&i.PlanSteps,
			&i.PlanRevision,
			&i.PlanVersion,
			&i.IsolatedEventsPerHour,
			&i.IsolatedTotalUsdPerHour,
			&i.LogEventCount,
			&i.FindingUpdatedAt,
			&i.PlanUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
