// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package findingsdb

import (
	"context"
)

type Querier interface {
	ListFindings(ctx context.Context) ([]ListFindingsRow, error)
	ListFindingsByDomain(ctx context.Context, domain *string) ([]ListFindingsByDomainRow, error)
	ListFindingsByService(ctx context.Context, serviceID *string) ([]ListFindingsByServiceRow, error)
}

var _ Querier = (*Queries)(nil)
