package powersync

import (
	_ "embed"
)

// schemaJSON is the PowerSync schema embedded at build time.
// It's generated by: go generate ./internal/powersync
//
//go:embed schema.json
var schemaJSON string

// SchemaJSON returns the embedded PowerSync schema.
func SchemaJSON() string {
	return schemaJSON
}
