// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package accountsdb

import (
	"context"
)

const create = `-- name: Create :exec
INSERT INTO accounts (id, name, created_at)
VALUES (?, ?, ?)
`

type CreateParams struct {
	ID        string
	Name      string
	CreatedAt string
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.ExecContext(ctx, create, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const delete = `-- name: Delete :exec
DELETE FROM accounts
WHERE id = ?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const list = `-- name: List :many
SELECT id, name, created_at
FROM accounts
ORDER BY created_at DESC
`

func (q *Queries) List(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
