// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package accountsdb

import (
	"context"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) error
	Delete(ctx context.Context, id string) error
	List(ctx context.Context) ([]Account, error)
}

var _ Querier = (*Queries)(nil)
