// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: log_events.sql

package logeventsdb

import (
	"context"
)

const listLogEventFacts = `-- name: ListLogEventFacts :many
SELECT id, account_id, log_event_id, fact_name, slice_name, slice_version, value, created_at
FROM log_event_facts
WHERE log_event_id = ?
ORDER BY slice_name ASC, fact_name ASC, created_at DESC
`

type ListLogEventFactsRow struct {
	ID           *string
	AccountID    *string
	LogEventID   *string
	FactName     *string
	SliceName    *string
	SliceVersion *int64
	Value        *string
	CreatedAt    *string
}

func (q *Queries) ListLogEventFacts(ctx context.Context, logEventID *string) ([]ListLogEventFactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLogEventFacts, logEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogEventFactsRow
	for rows.Next() {
		var i ListLogEventFactsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.LogEventID,
			&i.FactName,
			&i.SliceName,
			&i.SliceVersion,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogEventFactsByService = `-- name: ListLogEventFactsByService :many
SELECT lef.id, lef.account_id, lef.log_event_id, lef.fact_name, lef.slice_name, lef.slice_version, lef.value, lef.created_at
FROM log_event_facts lef
JOIN log_events le ON le.id = lef.log_event_id
WHERE le.service_id = ?
ORDER BY lef.log_event_id ASC, lef.slice_name ASC, lef.fact_name ASC, lef.created_at DESC
`

type ListLogEventFactsByServiceRow struct {
	ID           *string
	AccountID    *string
	LogEventID   *string
	FactName     *string
	SliceName    *string
	SliceVersion *int64
	Value        *string
	CreatedAt    *string
}

func (q *Queries) ListLogEventFactsByService(ctx context.Context, serviceID *string) ([]ListLogEventFactsByServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, listLogEventFactsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogEventFactsByServiceRow
	for rows.Next() {
		var i ListLogEventFactsByServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.LogEventID,
			&i.FactName,
			&i.SliceName,
			&i.SliceVersion,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogEventsByService = `-- name: ListLogEventsByService :many
SELECT id, account_id, service_id, name, description, severity, baseline_avg_bytes, baseline_volume_per_hour, created_at
FROM log_events
WHERE service_id = ?
ORDER BY name ASC
`

type ListLogEventsByServiceRow struct {
	ID                    *string
	AccountID             *string
	ServiceID             *string
	Name                  *string
	Description           *string
	Severity              *string
	BaselineAvgBytes      *float64
	BaselineVolumePerHour *float64
	CreatedAt             *string
}

func (q *Queries) ListLogEventsByService(ctx context.Context, serviceID *string) ([]ListLogEventsByServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, listLogEventsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogEventsByServiceRow
	for rows.Next() {
		var i ListLogEventsByServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ServiceID,
			&i.Name,
			&i.Description,
			&i.Severity,
			&i.BaselineAvgBytes,
			&i.BaselineVolumePerHour,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
