// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package logeventsdb

import (
	"context"
)

type Querier interface {
	ListLogEventFacts(ctx context.Context, logEventID *string) ([]ListLogEventFactsRow, error)
	ListLogEventFactsByService(ctx context.Context, serviceID *string) ([]ListLogEventFactsByServiceRow, error)
	ListLogEventsByService(ctx context.Context, serviceID *string) ([]ListLogEventsByServiceRow, error)
}

var _ Querier = (*Queries)(nil)
