package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

type jsonbManifest struct {
	Columns []jsonbColumn `json:"columns"`
}

type jsonbColumn struct {
	Key        string          `json:"key"`
	Entity     string          `json:"entity"`
	Family     string          `json:"family"`
	GoPackage  string          `json:"go_package"`
	GoType     string          `json:"go_type"`
	Generate   bool            `json:"generate"`
	Definition jsonbDefinition `json:"definition"`
}

type jsonbDefinition struct {
	Summary  string         `json:"summary"`
	Kind     string         `json:"kind"`
	Fields   []jsonbField   `json:"fields"`
	Variants []jsonbVariant `json:"variants"`
}

type jsonbVariant struct {
	Values   []string     `json:"values"`
	TypeName string       `json:"type_name"`
	Summary  string       `json:"summary"`
	Fields   []jsonbField `json:"fields"`
}

type jsonbField struct {
	Name       string          `json:"name"`
	Kind       string          `json:"kind"`
	Summary    string          `json:"summary"`
	Optional   bool            `json:"optional"`
	EnumValues []jsonbEnumItem `json:"enum_values"`
}

type jsonbEnumItem struct {
	Value   string `json:"value"`
	Summary string `json:"summary"`
}

func generateJSONBTypes(repoRoot string, manifestBytes []byte) error {
	var manifest jsonbManifest
	if err := json.Unmarshal(manifestBytes, &manifest); err != nil {
		return fmt.Errorf("unmarshal jsonb schema manifest: %w", err)
	}

	catalogColumns := make([]jsonbColumn, 0, len(manifest.Columns))
	for _, column := range manifest.Columns {
		if !column.Generate || column.GoPackage == "" || column.GoType == "" {
			continue
		}
		if !strings.HasPrefix(column.GoPackage, "catalog/") {
			continue
		}
		catalogColumns = append(catalogColumns, column)
	}
	if len(catalogColumns) == 0 {
		return nil
	}

	outputDir := filepath.Join(repoRoot, "internal", "domains", "catalog")
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create catalog output dir: %w", err)
	}

	if err := writeCatalogSupportFile(outputDir, catalogColumns); err != nil {
		return err
	}

	for _, column := range catalogColumns {
		stem := snakeCase(column.GoType)
		typesSource, err := renderTypesFile(column)
		if err != nil {
			return fmt.Errorf("render types for %s: %w", column.GoType, err)
		}
		if err := os.WriteFile(filepath.Join(outputDir, stem+".go"), typesSource, 0o644); err != nil {
			return fmt.Errorf("write %s.go: %w", stem, err)
		}

		decodeSource, err := renderDecodeFile(column)
		if err != nil {
			return fmt.Errorf("render decode for %s: %w", column.GoType, err)
		}
		if err := os.WriteFile(filepath.Join(outputDir, stem+"_decode.go"), decodeSource, 0o644); err != nil {
			return fmt.Errorf("write %s_decode.go: %w", stem, err)
		}

		if err := removeLegacyGeneratedDir(filepath.Join(outputDir, "db", pathBase(column.GoPackage))); err != nil {
			return err
		}
	}

	return nil
}

func writeCatalogSupportFile(outputDir string, columns []jsonbColumn) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by sqlite/generate. DO NOT EDIT.\n\n")
	buf.WriteString("package catalog\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString(")\n\n")
	buf.WriteString("type FieldPath []string\n\n")
	if anyColumnUsesObjectList(columns) {
		buf.WriteString("type JSONObject = map[string]json.RawMessage\n\n")
	}
	source, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format catalog support types: %w", err)
	}
	if err := os.WriteFile(filepath.Join(outputDir, "jsonb_support.go"), source, 0o644); err != nil {
		return fmt.Errorf("write jsonb_support.go: %w", err)
	}
	return nil
}

func renderTypesFile(column jsonbColumn) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by sqlite/generate. DO NOT EDIT.\n\n")
	buf.WriteString("package catalog\n\n")

	if isObjectListColumn(column) {
		buf.WriteString("// " + column.GoType + " is generated from " + column.Key + ".\n")
		buf.WriteString("type " + column.GoType + " []" + renderStandaloneObjectType(column.GoType, column.Definition.Fields) + "\n\n")
		if standalone := renderStandaloneObjectDefinition(column.GoType, column.Definition.Fields); standalone != "" {
			buf.WriteString(standalone)
		}
		return format.Source(buf.Bytes())
	}

	buf.WriteString("type " + column.GoType + " struct {\n")
	for _, variant := range column.Definition.Variants {
		buf.WriteString("\t" + variant.TypeName + " *" + variant.TypeName + "\n")
	}
	buf.WriteString("}\n\n")

	for _, variant := range column.Definition.Variants {
		for _, field := range variant.Fields {
			if len(field.EnumValues) == 0 {
				continue
			}
			enumType := enumTypeName(variant.TypeName, field.Name)
			buf.WriteString("type " + enumType + " string\n\n")
			buf.WriteString("const (\n")
			for _, item := range field.EnumValues {
				buf.WriteString("\t" + enumConstName(enumType, item.Value) + " " + enumType + " = " + quote(item.Value) + "\n")
			}
			buf.WriteString(")\n\n")
		}
		if variant.Summary != "" {
			buf.WriteString("// " + variant.TypeName + " " + variant.Summary + "\n")
		}
		buf.WriteString("type " + variant.TypeName + " struct {\n")
		for _, field := range variant.Fields {
			if field.Summary != "" {
				buf.WriteString("\t// " + field.Summary + "\n")
			}
			buf.WriteString("\t" + exported(field.Name) + " " + goTypeForField(variant.TypeName, field) + " `json:" + quote(jsonTag(field)) + "`\n")
		}
		buf.WriteString("}\n\n")
	}

	return format.Source(buf.Bytes())
}

func renderStandaloneObjectType(goType string, fields []jsonbField) string {
	return goType + "Item"
}

func renderStandaloneObjectDefinition(goType string, fields []jsonbField) string {
	if len(fields) == 0 {
		return ""
	}
	var buf bytes.Buffer
	itemType := renderStandaloneObjectType(goType, fields)
	buf.WriteString("type " + itemType + " struct {\n")
	for _, field := range fields {
		if field.Summary != "" {
			buf.WriteString("\t// " + field.Summary + "\n")
		}
		buf.WriteString("\t" + exported(field.Name) + " " + goTypeForField(itemType, field) + " `json:" + quote(jsonTag(field)) + "`\n")
	}
	buf.WriteString("}\n\n")
	return buf.String()
}

func renderDecodeFile(column jsonbColumn) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by sqlite/generate. DO NOT EDIT.\n\n")
	buf.WriteString("package catalog\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"encoding/json\"\n")
	if !isObjectListColumn(column) {
		buf.WriteString("\t\"fmt\"\n")
	}
	buf.WriteString(")\n\n")

	rowType := column.GoType + "Row"
	buf.WriteString("// " + rowType + " is the storage-level payload consumed by generated decoders for " + column.GoType + ".\n")
	buf.WriteString("type " + rowType + " struct {\n")
	buf.WriteString("\tNamespace string\n")
	buf.WriteString("\tFactType  string\n")
	buf.WriteString("\tValue     string\n")
	buf.WriteString("}\n\n")

	decodeFn := "Decode" + column.GoType
	buf.WriteString("func " + decodeFn + "(rows []" + rowType + ") (" + column.GoType + ", error) {\n")
	buf.WriteString("\tvar out " + column.GoType + "\n")
	if isObjectListColumn(column) {
		buf.WriteString("\tif len(rows) == 0 || rows[0].Value == \"\" {\n")
		buf.WriteString("\t\treturn out, nil\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\tif err := json.Unmarshal([]byte(rows[0].Value), &out); err != nil {\n")
		buf.WriteString("\t\treturn nil, err\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\treturn out, nil\n")
		buf.WriteString("}\n")
		return format.Source(buf.Bytes())
	}

	buf.WriteString("\tfor _, row := range rows {\n")
	buf.WriteString("\t\tswitch row.Namespace + \":\" + row.FactType {\n")
	for _, variant := range column.Definition.Variants {
		if len(variant.Values) != 2 {
			return nil, fmt.Errorf("variant %s requires namespace and fact type", variant.TypeName)
		}
		buf.WriteString("\t\tcase " + quote(variant.Values[0]+":"+variant.Values[1]) + ":\n")
		buf.WriteString("\t\t\tif out." + variant.TypeName + " != nil {\n")
		buf.WriteString("\t\t\t\tcontinue\n")
		buf.WriteString("\t\t\t}\n")
		buf.WriteString("\t\t\tvar decoded " + variant.TypeName + "\n")
		buf.WriteString("\t\t\tif err := json.Unmarshal([]byte(row.Value), &decoded); err != nil {\n")
		buf.WriteString("\t\t\t\treturn " + column.GoType + "{}, fmt.Errorf(\"decode " + variant.TypeName + ": %w\", err)\n")
		buf.WriteString("\t\t\t}\n")
		buf.WriteString("\t\t\tout." + variant.TypeName + " = &decoded\n")
	}
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn out, nil\n")
	buf.WriteString("}\n")

	return format.Source(buf.Bytes())
}

func anyColumnUsesObjectList(columns []jsonbColumn) bool {
	for _, column := range columns {
		if columnUsesObjectList(column) {
			return true
		}
	}
	return false
}

func columnUsesObjectList(column jsonbColumn) bool {
	if isObjectListColumn(column) {
		return true
	}
	for _, variant := range column.Definition.Variants {
		for _, field := range variant.Fields {
			if field.Kind == "object_list" {
				return true
			}
		}
	}
	return false
}

func isObjectListColumn(column jsonbColumn) bool {
	return column.Definition.Kind == "object_list"
}

func goTypeForField(ownerType string, field jsonbField) string {
	switch field.Kind {
	case "string":
		if field.Optional {
			return "*string"
		}
		return "string"
	case "boolean":
		if field.Optional {
			return "*bool"
		}
		return "bool"
	case "enum":
		enumType := enumTypeName(ownerType, field.Name)
		if field.Optional {
			return "*" + enumType
		}
		return enumType
	case "string_list":
		return "[]string"
	case "enum_list":
		return "[]" + enumTypeName(ownerType, field.Name)
	case "field_path_list":
		return "[]FieldPath"
	case "object_list":
		return "[]JSONObject"
	default:
		return "any"
	}
}

func enumTypeName(typeName, fieldName string) string {
	return typeName + exported(fieldName)
}

func enumConstName(typeName, value string) string {
	return typeName + exported(value)
}

func exported(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '_' || r == '-' || r == '.' || unicode.IsSpace(r)
	})
	if len(parts) == 0 {
		return ""
	}
	var out strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(strings.ToLower(part))
		runes[0] = unicode.ToUpper(runes[0])
		out.WriteString(string(runes))
	}
	return out.String()
}

func jsonTag(field jsonbField) string {
	if field.Optional {
		return field.Name + ",omitempty"
	}
	return field.Name
}

func quote(v string) string {
	return fmt.Sprintf("%q", v)
}

func pathBase(v string) string {
	parts := strings.Split(v, "/")
	return parts[len(parts)-1]
}

func snakeCase(name string) string {
	var out []rune
	for i, r := range name {
		if unicode.IsUpper(r) {
			if i > 0 {
				out = append(out, '_')
			}
			out = append(out, unicode.ToLower(r))
			continue
		}
		out = append(out, r)
	}
	return string(out)
}

func removeLegacyGeneratedDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("read legacy generated dir %s: %w", dir, err)
	}
	for _, entry := range entries {
		if err := os.RemoveAll(filepath.Join(dir, entry.Name())); err != nil {
			return fmt.Errorf("remove legacy generated artifact %s: %w", filepath.Join(dir, entry.Name()), err)
		}
	}
	if err := os.Remove(dir); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove legacy generated dir %s: %w", dir, err)
	}
	return nil
}
