package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/usetero/cli/internal/infrastructure/powersync/extension"
	"github.com/usetero/cli/internal/infrastructure/sqlite"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	ctx := context.Background()

	if err := extension.Register(); err != nil {
		return fmt.Errorf("register powersync extension: %w", err)
	}

	tmpDir, err := os.MkdirTemp("", "tero-generate-*")
	if err != nil {
		return fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	dbPath := filepath.Join(tmpDir, "generate.db")
	db, err := sqlite.OpenBare(ctx, dbPath)
	if err != nil {
		return fmt.Errorf("open database: %w", err)
	}
	defer db.Close()

	if err := extension.ApplySchema(ctx, db); err != nil {
		return fmt.Errorf("apply embedded powersync schema: %w", err)
	}

	schemaSQL, err := reflectSchema(ctx, db)
	if err != nil {
		return fmt.Errorf("reflect schema: %w", err)
	}

	outputDir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("get working directory: %w", err)
	}
	schemaPath := filepath.Join(outputDir, "schema.sql")
	if err := os.WriteFile(schemaPath, []byte(schemaSQL), 0o644); err != nil {
		return fmt.Errorf("write schema.sql: %w", err)
	}

	if err := runSQLC(ctx); err != nil {
		return fmt.Errorf("sqlc generate: %w", err)
	}

	fmt.Printf("Wrote %s\n", schemaPath)
	return nil
}

func reflectSchema(ctx context.Context, db *sqlite.DB) (string, error) {
	rows, err := db.Query(ctx, `
		SELECT name, sql
		FROM sqlite_master
		WHERE type = 'view'
		AND sql LIKE '%-- powersync-auto-generated%'
		ORDER BY name
	`)
	if err != nil {
		return "", fmt.Errorf("query sqlite_master: %w", err)
	}
	defer rows.Close()

	var views []string
	for rows.Next() {
		var name string
		var sqlText string
		if err := rows.Scan(&name, &sqlText); err != nil {
			return "", fmt.Errorf("scan row: %w", err)
		}
		views = append(views, name)
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("iterate rows: %w", err)
	}

	sort.Strings(views)

	statements := []string{
		"-- Code generated by go generate; DO NOT EDIT.",
		"-- Source: PowerSync schema reflected from sqlite_master",
		"",
	}
	for _, viewName := range views {
		tableSQL, err := viewToTable(ctx, db, viewName)
		if err != nil {
			return "", fmt.Errorf("convert view %s: %w", viewName, err)
		}
		statements = append(statements, tableSQL, "")
	}

	return strings.Join(statements, "\n"), nil
}

func viewToTable(ctx context.Context, db *sqlite.DB, viewName string) (string, error) {
	rows, err := db.Query(ctx, fmt.Sprintf("PRAGMA table_info(%s)", viewName))
	if err != nil {
		return "", fmt.Errorf("pragma table_info: %w", err)
	}
	defer rows.Close()

	var columns []string
	seen := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, colType string
		var notNull, pk int
		var dfltValue *string

		if err := rows.Scan(&cid, &name, &colType, &notNull, &dfltValue, &pk); err != nil {
			return "", fmt.Errorf("scan column: %w", err)
		}
		if strings.Contains(name, ":") || seen[name] {
			continue
		}
		seen[name] = true

		col := fmt.Sprintf("    %s %s", name, normalizeSQLiteType(colType))
		if pk == 1 {
			col += " PRIMARY KEY"
		}
		if notNull == 1 && pk != 1 {
			col += " NOT NULL"
		}
		columns = append(columns, col)
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("iterate columns: %w", err)
	}

	return fmt.Sprintf("CREATE TABLE %s (\n%s\n);", viewName, strings.Join(columns, ",\n")), nil
}

func normalizeSQLiteType(t string) string {
	switch strings.ToUpper(strings.TrimSpace(t)) {
	case "INT", "INTEGER", "BIGINT", "SMALLINT", "TINYINT":
		return "INTEGER"
	case "REAL", "DOUBLE", "FLOAT":
		return "REAL"
	case "BLOB":
		return "BLOB"
	default:
		return "TEXT"
	}
}

func runSQLC(ctx context.Context) error {
	repoRoot, err := findRepoRoot()
	if err != nil {
		return err
	}

	sqlcPath := filepath.Join(repoRoot, "bin", "sqlc")
	cmd := exec.CommandContext(ctx, sqlcPath, "generate")
	cmd.Dir = repoRoot
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "sqlc.yaml")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repo root")
		}
		dir = parent
	}
}
