package msgs

import (
	"github.com/usetero/cli/internal/domain"
	domaintools "github.com/usetero/cli/internal/domain/tools"
)

// TurnStarted is fired when a new turn begins within a round.
type TurnStarted struct {
	UserMessageID  domain.MessageID
	ConversationID domain.ConversationID
}

// AssistantContentUpdated is fired as the assistant message streams in.
type AssistantContentUpdated struct {
	TurnID  domain.MessageID // user message ID that started this turn
	Message domain.Message
}

// StreamCompleted is fired when the assistant stream finishes.
type StreamCompleted struct {
	TurnID        domain.MessageID // user message ID that started this turn
	Message       domain.Message
	Title         string // AI-generated conversation title, if provided
	ContextWindow int    // model's max token capacity
	InputTokens   int    // tokens consumed by input this turn
	OutputTokens  int    // tokens generated by output this turn
}

// StreamFailed is fired when the assistant stream encounters an error.
type StreamFailed struct {
	TurnID domain.MessageID // user message ID that started this turn
	Err    error
}

// ToolResultsReady is fired by a turn when all tool results are collected.
// This is internal to round - it triggers the next turn in the tool loop.
type ToolResultsReady struct {
	TurnID  domain.MessageID     // identifies which turn completed
	Results []domaintools.Result // collected tool results
}
