// Code generated by go generate; DO NOT EDIT.
//
// To regenerate: doppler run -- go generate ./internal/powersync

package sqlite

// Conversation represents a row in the conversations table.
type Conversation struct {
	ID          string `json:"id"`           // uuid
	AccountID   string `json:"account_id"`   // uuid
	CreatedAt   string `json:"created_at"`   // timestamptz
	UpdatedAt   string `json:"updated_at"`   // timestamptz
	UserID      string `json:"user_id"`      // varchar
	WorkspaceID string `json:"workspace_id"` // uuid
}
