// Code generated by go generate; DO NOT EDIT.
//
// To regenerate: doppler run -- go generate ./internal/powersync

package sqlite

import "encoding/json"

// LogEventPolicy represents a row in the log_event_policies table.
type LogEventPolicy struct {
	ID          string          `json:"id"`           // uuid
	AccountID   string          `json:"account_id"`   // uuid
	Analysis    json.RawMessage `json:"analysis"`     // jsonb
	ApprovedAt  string          `json:"approved_at"`  // timestamptz
	ApprovedBy  string          `json:"approved_by"`  // varchar
	Category    string          `json:"category"`     // varchar
	CreatedAt   string          `json:"created_at"`   // timestamptz
	DismissedAt string          `json:"dismissed_at"` // timestamptz
	DismissedBy string          `json:"dismissed_by"` // varchar
	LogEventID  string          `json:"log_event_id"` // uuid
	Model       string          `json:"model"`        // varchar
	UpdatedAt   string          `json:"updated_at"`   // timestamptz
	WorkspaceID string          `json:"workspace_id"` // uuid
}
