// Code generated by go generate; DO NOT EDIT.
//
// To regenerate: doppler run -- go generate ./internal/powersync

package sqlite

import "encoding/json"

// LogEvent represents a row in the log_events table.
type LogEvent struct {
	ID          string          `json:"id"`          // uuid
	AccountID   string          `json:"account_id"`  // uuid
	AnalyzedAt  string          `json:"analyzed_at"` // timestamptz
	CreatedAt   string          `json:"created_at"`  // timestamptz
	Description string          `json:"description"` // text
	Examples    json.RawMessage `json:"examples"`    // jsonb
	Matchers    json.RawMessage `json:"matchers"`    // jsonb
	Name        string          `json:"name"`        // varchar
	ServiceID   string          `json:"service_id"`  // uuid
	UpdatedAt   string          `json:"updated_at"`  // timestamptz
}
