// Code generated by go generate; DO NOT EDIT.
//
// To regenerate: doppler run -- go generate ./internal/powersync

package sqlite

import "encoding/json"

// LogEventVolume represents a row in the log_event_volumes table.
type LogEventVolume struct {
	ID                string          `json:"id"`                   // uuid
	AccountID         string          `json:"account_id"`           // uuid
	AttributeAVGBytes json.RawMessage `json:"attribute_avg_bytes"`  // jsonb
	AVGBytes          float64         `json:"avg_bytes"`            // float8
	Count             float64         `json:"count"`                // float8
	CreatedAt         string          `json:"created_at"`           // timestamptz
	DatadogLogIndexID string          `json:"datadog_log_index_id"` // uuid
	EdgeInstanceID    string          `json:"edge_instance_id"`     // uuid
	LogEventID        string          `json:"log_event_id"`         // uuid
	Timestamp         string          `json:"timestamp"`            // timestamptz
}
