// Code generated by go generate; DO NOT EDIT.
//
// To regenerate: doppler run -- go generate ./internal/powersync

package sqlite

import "encoding/json"

// Message represents a row in the messages table.
type Message struct {
	ID             string          `json:"id"`              // uuid
	AccountID      string          `json:"account_id"`      // uuid
	Content        json.RawMessage `json:"content"`         // jsonb
	ConversationID string          `json:"conversation_id"` // uuid
	CreatedAt      string          `json:"created_at"`      // timestamptz
	Role           string          `json:"role"`            // varchar
	StopReason     string          `json:"stop_reason"`     // varchar
}
