// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

type Conversation struct {
	ID          *string
	AccountID   *string
	CreatedAt   *string
	UpdatedAt   *string
	UserID      *string
	WorkspaceID *string
}

type DatadogAccount struct {
	ID        *string
	AccountID *string
	CreatedAt *string
	Name      *string
	Site      *string
	UpdatedAt *string
}

type DatadogAccountStatusesCache struct {
	ID                     *string
	AccountID              *string
	DatadogAccountID       *string
	LogActiveServices      *int64
	LogAnalyzingCount      *int64
	LogAnalyzingServices   *int64
	LogBrokenServices      *int64
	LogDisabledServices    *int64
	LogDiscoveredVolume    *int64
	LogDiscoveringCount    *int64
	LogDiscoveringServices *int64
	LogError               *string
	LogErrorAt             *string
	LogEventCount          *int64
	LogInactiveServices    *int64
	LogPercentComplete     *float64
	LogReadyServices       *int64
	LogSavedCount          *int64
	LogServiceCount        *int64
	LogServiceVolume       *int64
	LogStaleServices       *int64
	LogStatus              *string
	LogValuableCount       *int64
	LogWarning             *string
	LogWarningAt           *string
	LogWasteCount          *int64
	RefreshedAt            *string
}

type DatadogLogIndex struct {
	ID               *string
	AccountID        *string
	CreatedAt        *string
	DatadogAccountID *string
	LastSeenAt       *string
	Name             *string
}

type DiscoveryStatus struct {
	ID                  *string
	AccountID           *string
	CompletedAt         *string
	ConsecutiveErrors   *int64
	ConsecutiveWarnings *int64
	CreatedAt           *string
	DatadogAccountID    *string
	DiscoveryType       *string
	LastError           *string
	LastErrorAt         *string
	LastWarning         *string
	LastWarningAt       *string
	ServiceID           *string
	StartedAt           *string
	UpdatedAt           *string
}

type LogEvent struct {
	ID          *string
	AccountID   *string
	AnalyzedAt  *string
	CreatedAt   *string
	Description *string
	Examples    *string
	Matchers    *string
	Name        *string
	ServiceID   *string
	UpdatedAt   *string
}

type LogEventPolicy struct {
	ID          *string
	AccountID   *string
	Analysis    *string
	ApprovedAt  *string
	ApprovedBy  *string
	Category    *string
	CreatedAt   *string
	DismissedAt *string
	DismissedBy *string
	LogEventID  *string
	Model       *string
	UpdatedAt   *string
	WorkspaceID *string
}

type LogEventPolicyStatusesCache struct {
	ID          *string
	AccountID   *string
	ApprovedAt  *string
	BytesSaved  *float64
	Category    *string
	DismissedAt *string
	LogEventID  *string
	PolicyID    *string
	RefreshedAt *string
	Status      *string
	VolumeSaved *float64
	WorkspaceID *string
}

type LogEventStatusesCache struct {
	ID               *string
	AccountID        *string
	BytesAfter       *float64
	BytesBefore      *float64
	DatadogAccountID *string
	Error            *string
	HasBeenAnalyzed  *int64
	HasVolumes       *int64
	LogEventID       *string
	RefreshedAt      *string
	ServiceID        *string
	Status           *string
	VolumeAfter      *float64
	VolumeBefore     *float64
}

type LogEventVolume struct {
	ID                *string
	AccountID         *string
	AttributeAvgBytes *string
	AvgBytes          *float64
	Count             *float64
	CreatedAt         *string
	DatadogLogIndexID *string
	EdgeInstanceID    *string
	LogEventID        *string
	Timestamp         *string
}

type Message struct {
	ID             *string
	AccountID      *string
	Content        *string
	ConversationID *string
	CreatedAt      *string
	Role           *string
	StopReason     *string
}

type Service struct {
	ID                    *string
	AccountID             *string
	CreatedAt             *string
	Description           *string
	Enabled               *int64
	InitialWeeklyLogCount *int64
	Name                  *string
	UpdatedAt             *string
}

type ServiceLogVolume struct {
	ID               *string
	AccountID        *string
	CreatedAt        *string
	DatadogAccountID *string
	ServiceID        *string
	Timestamp        *string
	UpdatedAt        *string
	Volume           *int64
}

type ServiceStatusesCache struct {
	ID                  *string
	AccountID           *string
	DatadogAccountID    *string
	LogAnalyzingCount   *int64
	LogBytesAfter       *float64
	LogBytesBefore      *float64
	LogDiscoveredVolume *int64
	LogDiscoveringCount *int64
	LogError            *string
	LogErrorAt          *string
	LogEventCount       *int64
	LogPercentComplete  *float64
	LogSavedCount       *int64
	LogServiceVolume    *int64
	LogStatus           *string
	LogValuableCount    *int64
	LogVolumeAfter      *float64
	LogVolumeBefore     *float64
	LogWarning          *string
	LogWarningAt        *string
	LogWasteCount       *int64
	RefreshedAt         *string
	ServiceID           *string
}

type Team struct {
	ID          *string
	AccountID   *string
	CreatedAt   *string
	Name        *string
	UpdatedAt   *string
	WorkspaceID *string
}

type Workspace struct {
	ID        *string
	AccountID *string
	CreatedAt *string
	Name      *string
	Purpose   *string
	UpdatedAt *string
}
