-- Code generated by go generate; DO NOT EDIT.
-- Source: PowerSync schema reflected from sqlite_master

CREATE TABLE conversation_contexts (
    id TEXT,
    account_id TEXT,
    added_by TEXT,
    conversation_id TEXT,
    created_at TEXT,
    entity_id TEXT,
    entity_type TEXT
);

CREATE TABLE conversations (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    title TEXT,
    updated_at TEXT,
    user_id TEXT,
    view_id TEXT,
    workspace_id TEXT
);

CREATE TABLE datadog_account_statuses_cache (
    id TEXT,
    account_id TEXT,
    datadog_account_id TEXT,
    log_active_services INTEGER,
    log_analyzed_count INTEGER,
    log_analyzing_count INTEGER,
    log_analyzing_services INTEGER,
    log_broken_services INTEGER,
    log_disabled_services INTEGER,
    log_discovered_volume_in_window INTEGER,
    log_discovering_count INTEGER,
    log_discovering_services INTEGER,
    log_error TEXT,
    log_error_at TEXT,
    log_event_count INTEGER,
    log_inactive_services INTEGER,
    log_percent_complete REAL,
    log_ready_services INTEGER,
    log_saved_count INTEGER,
    log_service_count INTEGER,
    log_service_volume_in_window INTEGER,
    log_stale_services INTEGER,
    log_status TEXT,
    log_valuable_count INTEGER,
    log_warning TEXT,
    log_warning_at TEXT,
    log_waste_count INTEGER,
    ready_for_use INTEGER,
    refreshed_at TEXT
);

CREATE TABLE datadog_accounts (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    name TEXT,
    site TEXT,
    updated_at TEXT
);

CREATE TABLE datadog_log_indexes (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    datadog_account_id TEXT,
    last_seen_at TEXT,
    name TEXT
);

CREATE TABLE discovery_statuses (
    id TEXT,
    account_id TEXT,
    completed_at TEXT,
    consecutive_errors INTEGER,
    consecutive_warnings INTEGER,
    created_at TEXT,
    datadog_account_id TEXT,
    discovery_type TEXT,
    last_error TEXT,
    last_error_at TEXT,
    last_warning TEXT,
    last_warning_at TEXT,
    service_id TEXT,
    started_at TEXT,
    updated_at TEXT
);

CREATE TABLE log_event_policies (
    id TEXT,
    account_id TEXT,
    analysis TEXT,
    approved_at TEXT,
    approved_by TEXT,
    benefits TEXT,
    category TEXT,
    created_at TEXT,
    dismissed_at TEXT,
    dismissed_by TEXT,
    log_event_id TEXT,
    model TEXT,
    objectivity TEXT,
    risk_level TEXT,
    updated_at TEXT,
    workspace_id TEXT
);

CREATE TABLE log_event_policy_statuses_cache (
    id TEXT,
    account_id TEXT,
    approved_at TEXT,
    bytes_saved_per_hour REAL,
    category TEXT,
    dismissed_at TEXT,
    log_event_id TEXT,
    policy_id TEXT,
    refreshed_at TEXT,
    status TEXT,
    volume_saved_per_hour REAL,
    workspace_id TEXT
);

CREATE TABLE log_event_statuses_cache (
    id TEXT,
    account_id TEXT,
    bytes_per_hour_after REAL,
    bytes_per_hour_before REAL,
    datadog_account_id TEXT,
    error TEXT,
    has_been_analyzed INTEGER,
    has_volumes INTEGER,
    log_event_id TEXT,
    refreshed_at TEXT,
    service_id TEXT,
    status TEXT,
    volume_per_hour_after REAL,
    volume_per_hour_before REAL
);

CREATE TABLE log_event_volumes (
    id TEXT,
    account_id TEXT,
    attribute_avg_bytes TEXT,
    avg_bytes REAL,
    count_per_hour REAL,
    created_at TEXT,
    datadog_log_index_id TEXT,
    edge_instance_id TEXT,
    log_event_id TEXT,
    timestamp TEXT
);

CREATE TABLE log_events (
    id TEXT,
    account_id TEXT,
    analyzed_at TEXT,
    created_at TEXT,
    description TEXT,
    examples TEXT,
    matchers TEXT,
    name TEXT,
    service_id TEXT,
    updated_at TEXT
);

CREATE TABLE messages (
    id TEXT,
    account_id TEXT,
    content TEXT,
    conversation_id TEXT,
    created_at TEXT,
    model TEXT,
    role TEXT,
    stop_reason TEXT
);

CREATE TABLE service_log_volumes (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    datadog_account_id TEXT,
    service_id TEXT,
    timestamp TEXT,
    updated_at TEXT,
    volume_per_hour INTEGER
);

CREATE TABLE service_statuses_cache (
    id TEXT,
    account_id TEXT,
    datadog_account_id TEXT,
    log_analyzing_count INTEGER,
    log_bytes_per_hour_after REAL,
    log_bytes_per_hour_before REAL,
    log_discovered_volume_in_window INTEGER,
    log_discovering_count INTEGER,
    log_error TEXT,
    log_error_at TEXT,
    log_event_count INTEGER,
    log_percent_complete REAL,
    log_saved_count INTEGER,
    log_service_volume_in_window INTEGER,
    log_status TEXT,
    log_valuable_count INTEGER,
    log_volume_per_hour_after REAL,
    log_volume_per_hour_before REAL,
    log_warning TEXT,
    log_warning_at TEXT,
    log_waste_count INTEGER,
    refreshed_at TEXT,
    service_id TEXT
);

CREATE TABLE services (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    description TEXT,
    enabled INTEGER,
    initial_weekly_log_count INTEGER,
    name TEXT,
    updated_at TEXT
);

CREATE TABLE teams (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    name TEXT,
    updated_at TEXT,
    workspace_id TEXT
);

CREATE TABLE view_favorites (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    user_id TEXT,
    view_id TEXT
);

CREATE TABLE views (
    id TEXT,
    account_id TEXT,
    conversation_id TEXT,
    created_at TEXT,
    created_by TEXT,
    entity_type TEXT,
    forked_from_id TEXT,
    message_id TEXT,
    query TEXT
);

CREATE TABLE workspaces (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    name TEXT,
    purpose TEXT,
    updated_at TEXT
);
