// Code generated by go generate; DO NOT EDIT.
//
// To regenerate: doppler run -- go generate ./internal/powersync

package sqlite

import "encoding/json"

// Schema defines the tables that will be synced from the control plane.
type Schema struct {
	Tables []SchemaTable `json:"tables"`
}

// SchemaTable defines a single table in the sync schema.
type SchemaTable struct {
	Name    string         `json:"name"`
	Columns []SchemaColumn `json:"columns"`
}

// SchemaColumn defines a column in a synced table.
type SchemaColumn struct {
	Name string `json:"name"`
	Type string `json:"type"` // "text", "integer", "real"
}

// DefaultSchema returns the schema for tables synced from the control plane.
func DefaultSchema() Schema {
	return Schema{
		Tables: []SchemaTable{
			{
				Name: "conversations",
				Columns: []SchemaColumn{
					{Name: "id", Type: "text"},
					{Name: "account_id", Type: "text"},
					{Name: "created_at", Type: "text"},
					{Name: "updated_at", Type: "text"},
					{Name: "user_id", Type: "text"},
					{Name: "workspace_id", Type: "text"},
				},
			},
			{
				Name: "log_event_policies",
				Columns: []SchemaColumn{
					{Name: "id", Type: "text"},
					{Name: "account_id", Type: "text"},
					{Name: "analysis", Type: "text"},
					{Name: "approved_at", Type: "text"},
					{Name: "approved_by", Type: "text"},
					{Name: "category", Type: "text"},
					{Name: "created_at", Type: "text"},
					{Name: "dismissed_at", Type: "text"},
					{Name: "dismissed_by", Type: "text"},
					{Name: "log_event_id", Type: "text"},
					{Name: "model", Type: "text"},
					{Name: "updated_at", Type: "text"},
					{Name: "workspace_id", Type: "text"},
				},
			},
			{
				Name: "log_event_volumes",
				Columns: []SchemaColumn{
					{Name: "id", Type: "text"},
					{Name: "account_id", Type: "text"},
					{Name: "attribute_avg_bytes", Type: "text"},
					{Name: "avg_bytes", Type: "real"},
					{Name: "count", Type: "real"},
					{Name: "created_at", Type: "text"},
					{Name: "datadog_log_index_id", Type: "text"},
					{Name: "edge_instance_id", Type: "text"},
					{Name: "log_event_id", Type: "text"},
					{Name: "timestamp", Type: "text"},
				},
			},
			{
				Name: "log_events",
				Columns: []SchemaColumn{
					{Name: "id", Type: "text"},
					{Name: "account_id", Type: "text"},
					{Name: "analyzed_at", Type: "text"},
					{Name: "created_at", Type: "text"},
					{Name: "description", Type: "text"},
					{Name: "examples", Type: "text"},
					{Name: "matchers", Type: "text"},
					{Name: "name", Type: "text"},
					{Name: "service_id", Type: "text"},
					{Name: "updated_at", Type: "text"},
				},
			},
			{
				Name: "messages",
				Columns: []SchemaColumn{
					{Name: "id", Type: "text"},
					{Name: "account_id", Type: "text"},
					{Name: "content", Type: "text"},
					{Name: "conversation_id", Type: "text"},
					{Name: "created_at", Type: "text"},
					{Name: "role", Type: "text"},
					{Name: "stop_reason", Type: "text"},
				},
			},
			{
				Name: "services",
				Columns: []SchemaColumn{
					{Name: "id", Type: "text"},
					{Name: "account_id", Type: "text"},
					{Name: "created_at", Type: "text"},
					{Name: "description", Type: "text"},
					{Name: "enabled", Type: "integer"},
					{Name: "initial_weekly_log_count", Type: "integer"},
					{Name: "name", Type: "text"},
					{Name: "updated_at", Type: "text"},
				},
			},
			{
				Name: "teams",
				Columns: []SchemaColumn{
					{Name: "id", Type: "text"},
					{Name: "account_id", Type: "text"},
					{Name: "created_at", Type: "text"},
					{Name: "name", Type: "text"},
					{Name: "updated_at", Type: "text"},
					{Name: "workspace_id", Type: "text"},
				},
			},
			{
				Name: "workspaces",
				Columns: []SchemaColumn{
					{Name: "id", Type: "text"},
					{Name: "account_id", Type: "text"},
					{Name: "created_at", Type: "text"},
					{Name: "name", Type: "text"},
					{Name: "purpose", Type: "text"},
					{Name: "updated_at", Type: "text"},
				},
			},
		},
	}
}

// JSON returns the schema as a JSON string for powersync_replace_schema().
func (s Schema) JSON() (string, error) {
	data, err := json.Marshal(s)
	if err != nil {
		return "", err
	}
	return string(data), nil
}
