-- Code generated by go generate; DO NOT EDIT.
-- Source: PowerSync schema reflected from sqlite_master

CREATE TABLE conversations (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    title TEXT,
    user_id TEXT
);

CREATE TABLE datadog_account_statuses_cache (
    id TEXT,
    account_id TEXT,
    current_bytes_per_hour REAL,
    current_bytes_usd_per_hour REAL,
    current_events_per_hour REAL,
    current_service_events_per_hour REAL,
    current_service_volume_usd_per_hour REAL,
    current_total_usd_per_hour REAL,
    current_volume_usd_per_hour REAL,
    datadog_account_id TEXT,
    disabled_services INTEGER,
    effective_bytes_per_hour REAL,
    effective_bytes_usd_per_hour REAL,
    effective_events_per_hour REAL,
    effective_log_event_count INTEGER,
    effective_saved_bytes_per_hour REAL,
    effective_saved_bytes_usd_per_hour REAL,
    effective_saved_events_per_hour REAL,
    effective_saved_total_usd_per_hour REAL,
    effective_saved_volume_usd_per_hour REAL,
    effective_total_usd_per_hour REAL,
    effective_volume_usd_per_hour REAL,
    health TEXT,
    inactive_services INTEGER,
    log_active_services INTEGER,
    log_event_analyzed_count INTEGER,
    log_event_count INTEGER,
    log_service_count INTEGER,
    ok_services INTEGER,
    preview_bytes_per_hour REAL,
    preview_bytes_usd_per_hour REAL,
    preview_events_per_hour REAL,
    preview_log_event_count INTEGER,
    preview_saved_bytes_per_hour REAL,
    preview_saved_bytes_usd_per_hour REAL,
    preview_saved_events_per_hour REAL,
    preview_saved_total_usd_per_hour REAL,
    preview_saved_volume_usd_per_hour REAL,
    preview_total_usd_per_hour REAL,
    preview_volume_usd_per_hour REAL,
    ready_for_use INTEGER
);

CREATE TABLE datadog_accounts (
    id TEXT,
    account_id TEXT,
    cost_per_gb_ingested REAL,
    created_at TEXT,
    name TEXT,
    site TEXT
);

CREATE TABLE datadog_log_indexes (
    id TEXT,
    account_id TEXT,
    cost_per_million_events_indexed REAL,
    created_at TEXT,
    datadog_account_id TEXT,
    name TEXT
);

CREATE TABLE finding_curations (
    id TEXT,
    account_id TEXT,
    body TEXT,
    created_at TEXT,
    disposition TEXT,
    finding_id TEXT,
    finding_problem_version INTEGER,
    priority TEXT,
    title TEXT,
    version INTEGER
);

CREATE TABLE finding_log_events (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    finding_id TEXT,
    log_event_id TEXT
);

CREATE TABLE finding_plans (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    finding_curation_id TEXT,
    finding_id TEXT,
    open_questions TEXT,
    rationale TEXT,
    revision INTEGER,
    status TEXT,
    steps TEXT,
    summary TEXT,
    title TEXT,
    version INTEGER
);

CREATE TABLE finding_statuses_cache (
    id TEXT,
    account_id TEXT,
    current_bytes_per_hour REAL,
    current_bytes_usd_per_hour REAL,
    current_events_per_hour REAL,
    current_total_usd_per_hour REAL,
    current_volume_usd_per_hour REAL,
    finding_created_at TEXT,
    finding_id TEXT,
    finding_updated_at TEXT,
    isolated_bytes_per_hour REAL,
    isolated_bytes_usd_per_hour REAL,
    isolated_events_per_hour REAL,
    isolated_saved_bytes_per_hour REAL,
    isolated_saved_bytes_usd_per_hour REAL,
    isolated_saved_events_per_hour REAL,
    isolated_saved_total_usd_per_hour REAL,
    isolated_saved_volume_usd_per_hour REAL,
    isolated_total_usd_per_hour REAL,
    isolated_volume_usd_per_hour REAL,
    log_event_count INTEGER,
    log_event_id TEXT,
    plan_status TEXT,
    plan_updated_at TEXT,
    scope_kind TEXT,
    service_id TEXT
);

CREATE TABLE findings (
    id TEXT,
    account_id TEXT,
    closed_at TEXT,
    created_at TEXT,
    details TEXT,
    domain TEXT,
    fingerprint TEXT,
    log_event_id TEXT,
    problem_version INTEGER,
    scope_kind TEXT,
    service_id TEXT,
    type TEXT
);

CREATE TABLE log_event_facts (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    fact_name TEXT,
    log_event_id TEXT,
    slice_name TEXT,
    slice_version INTEGER,
    value TEXT
);

CREATE TABLE log_event_policies (
    id TEXT,
    account_id TEXT,
    compiled_at TEXT,
    created_at TEXT,
    finding_id TEXT,
    kind TEXT,
    log_event_id TEXT,
    spec TEXT
);

CREATE TABLE log_event_statuses_cache (
    id TEXT,
    account_id TEXT,
    current_bytes_per_hour REAL,
    current_bytes_usd_per_hour REAL,
    current_events_per_hour REAL,
    current_total_usd_per_hour REAL,
    current_volume_usd_per_hour REAL,
    effective_bytes_per_hour REAL,
    effective_bytes_usd_per_hour REAL,
    effective_events_per_hour REAL,
    effective_saved_bytes_per_hour REAL,
    effective_saved_bytes_usd_per_hour REAL,
    effective_saved_events_per_hour REAL,
    effective_saved_total_usd_per_hour REAL,
    effective_saved_volume_usd_per_hour REAL,
    effective_total_usd_per_hour REAL,
    effective_volume_usd_per_hour REAL,
    has_been_analyzed INTEGER,
    has_effective_policy INTEGER,
    has_preview_policy INTEGER,
    has_volumes INTEGER,
    log_event_id TEXT,
    preview_bytes_per_hour REAL,
    preview_bytes_usd_per_hour REAL,
    preview_events_per_hour REAL,
    preview_saved_bytes_per_hour REAL,
    preview_saved_bytes_usd_per_hour REAL,
    preview_saved_events_per_hour REAL,
    preview_saved_total_usd_per_hour REAL,
    preview_saved_volume_usd_per_hour REAL,
    preview_total_usd_per_hour REAL,
    preview_volume_usd_per_hour REAL,
    service_id TEXT
);

CREATE TABLE log_events (
    id TEXT,
    account_id TEXT,
    baseline_avg_bytes REAL,
    baseline_volume_per_hour REAL,
    created_at TEXT,
    description TEXT,
    matchers TEXT,
    name TEXT,
    service_id TEXT,
    severity TEXT
);

CREATE TABLE messages (
    id TEXT,
    account_id TEXT,
    content TEXT,
    conversation_id TEXT,
    created_at TEXT,
    model TEXT,
    role TEXT,
    stop_reason TEXT
);

CREATE TABLE service_facts (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    fact_group TEXT,
    fact_type TEXT,
    namespace TEXT,
    service_id TEXT,
    value TEXT,
    version INTEGER
);

CREATE TABLE service_statuses_cache (
    id TEXT,
    account_id TEXT,
    current_bytes_per_hour REAL,
    current_bytes_usd_per_hour REAL,
    current_events_per_hour REAL,
    current_service_debug_events_per_hour REAL,
    current_service_error_events_per_hour REAL,
    current_service_events_per_hour REAL,
    current_service_info_events_per_hour REAL,
    current_service_other_events_per_hour REAL,
    current_service_volume_usd_per_hour REAL,
    current_service_warn_events_per_hour REAL,
    current_total_usd_per_hour REAL,
    current_volume_usd_per_hour REAL,
    datadog_account_id TEXT,
    effective_bytes_per_hour REAL,
    effective_bytes_usd_per_hour REAL,
    effective_events_per_hour REAL,
    effective_log_event_count INTEGER,
    effective_saved_bytes_per_hour REAL,
    effective_saved_bytes_usd_per_hour REAL,
    effective_saved_events_per_hour REAL,
    effective_saved_total_usd_per_hour REAL,
    effective_saved_volume_usd_per_hour REAL,
    effective_total_usd_per_hour REAL,
    effective_volume_usd_per_hour REAL,
    health TEXT,
    log_event_analyzed_count INTEGER,
    log_event_count INTEGER,
    preview_bytes_per_hour REAL,
    preview_bytes_usd_per_hour REAL,
    preview_events_per_hour REAL,
    preview_log_event_count INTEGER,
    preview_saved_bytes_per_hour REAL,
    preview_saved_bytes_usd_per_hour REAL,
    preview_saved_events_per_hour REAL,
    preview_saved_total_usd_per_hour REAL,
    preview_saved_volume_usd_per_hour REAL,
    preview_total_usd_per_hour REAL,
    preview_volume_usd_per_hour REAL,
    service_id TEXT
);

CREATE TABLE service_team_mappings (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    service_id TEXT,
    team_id TEXT,
    updated_at TEXT
);

CREATE TABLE services (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    enabled INTEGER,
    initial_weekly_log_count INTEGER,
    name TEXT
);

CREATE TABLE team_memberships (
    id TEXT,
    created_at TEXT,
    organization_id TEXT,
    team_id TEXT,
    updated_at TEXT,
    user_id TEXT
);

CREATE TABLE teams (
    id TEXT,
    created_at TEXT,
    description TEXT,
    external_id TEXT,
    name TEXT,
    organization_id TEXT,
    updated_at TEXT
);

CREATE TABLE workspaces (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    name TEXT,
    purpose TEXT
);
