-- Code generated by go generate; DO NOT EDIT.
-- Source: PowerSync schema reflected from sqlite_master

CREATE TABLE conversation_contexts (
    id TEXT,
    account_id TEXT,
    added_by TEXT,
    conversation_id TEXT,
    created_at TEXT,
    entity_id TEXT,
    entity_type TEXT
);

CREATE TABLE conversations (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    title TEXT,
    updated_at TEXT,
    user_id TEXT,
    view_id TEXT,
    workspace_id TEXT
);

CREATE TABLE datadog_account_statuses_cache (
    id TEXT,
    account_id TEXT,
    datadog_account_id TEXT,
    disabled_services INTEGER,
    error TEXT,
    error_at TEXT,
    error_services INTEGER,
    estimated_bytes_reduction_per_hour REAL,
    estimated_cost_reduction_per_hour_bytes_usd REAL,
    estimated_cost_reduction_per_hour_usd REAL,
    estimated_cost_reduction_per_hour_volume_usd REAL,
    estimated_volume_reduction_per_hour REAL,
    health TEXT,
    inactive_services INTEGER,
    log_active_services INTEGER,
    log_event_analyzed_count INTEGER,
    log_event_bytes_per_hour REAL,
    log_event_cost_per_hour_bytes_usd REAL,
    log_event_cost_per_hour_usd REAL,
    log_event_cost_per_hour_volume_usd REAL,
    log_event_count INTEGER,
    log_event_quarantined_count INTEGER,
    log_event_volume_per_hour REAL,
    log_service_count INTEGER,
    observed_bytes_per_hour_after REAL,
    observed_bytes_per_hour_before REAL,
    observed_cost_per_hour_after_bytes_usd REAL,
    observed_cost_per_hour_after_usd REAL,
    observed_cost_per_hour_after_volume_usd REAL,
    observed_cost_per_hour_before_bytes_usd REAL,
    observed_cost_per_hour_before_usd REAL,
    observed_cost_per_hour_before_volume_usd REAL,
    observed_volume_per_hour_after REAL,
    observed_volume_per_hour_before REAL,
    ok_services INTEGER,
    policy_approved_count INTEGER,
    policy_dismissed_count INTEGER,
    policy_pending_count INTEGER,
    ready_for_use INTEGER,
    refreshed_at TEXT,
    service_cost_per_hour_volume_usd REAL,
    service_volume_per_hour REAL,
    stale_services INTEGER,
    warning TEXT,
    warning_at TEXT
);

CREATE TABLE datadog_accounts (
    id TEXT,
    account_id TEXT,
    cost_per_gb_ingested REAL,
    created_at TEXT,
    name TEXT,
    site TEXT,
    updated_at TEXT
);

CREATE TABLE datadog_log_indexes (
    id TEXT,
    account_id TEXT,
    cost_per_million_events_indexed REAL,
    created_at TEXT,
    datadog_account_id TEXT,
    last_seen_at TEXT,
    name TEXT
);

CREATE TABLE discovery_statuses (
    id TEXT,
    account_id TEXT,
    completed_at TEXT,
    consecutive_errors INTEGER,
    consecutive_warnings INTEGER,
    created_at TEXT,
    datadog_account_id TEXT,
    discovery_type TEXT,
    last_error TEXT,
    last_error_at TEXT,
    last_warning TEXT,
    last_warning_at TEXT,
    service_id TEXT,
    started_at TEXT,
    updated_at TEXT
);

CREATE TABLE log_event_policies (
    id TEXT,
    account_id TEXT,
    analysis TEXT,
    approved_at TEXT,
    approved_by TEXT,
    benefits TEXT,
    category TEXT,
    created_at TEXT,
    dismissed_at TEXT,
    dismissed_by TEXT,
    log_event_id TEXT,
    model TEXT,
    objectivity TEXT,
    updated_at TEXT,
    workspace_id TEXT
);

CREATE TABLE log_event_policy_statuses_cache (
    id TEXT,
    account_id TEXT,
    approved_at TEXT,
    benefits TEXT,
    category TEXT,
    created_at TEXT,
    dismissed_at TEXT,
    estimated_bytes_reduction_per_hour REAL,
    estimated_cost_reduction_per_hour_bytes_usd REAL,
    estimated_cost_reduction_per_hour_usd REAL,
    estimated_cost_reduction_per_hour_volume_usd REAL,
    estimated_volume_reduction_per_hour REAL,
    log_event_id TEXT,
    objectivity TEXT,
    policy_id TEXT,
    refreshed_at TEXT,
    status TEXT,
    workspace_id TEXT
);

CREATE TABLE log_event_statuses_cache (
    id TEXT,
    account_id TEXT,
    approved_policy_count INTEGER,
    bytes_per_hour REAL,
    cost_per_hour_bytes_usd REAL,
    cost_per_hour_usd REAL,
    cost_per_hour_volume_usd REAL,
    datadog_account_id TEXT,
    dismissed_policy_count INTEGER,
    error TEXT,
    estimable_policy_count INTEGER,
    estimated_bytes_reduction_per_hour REAL,
    estimated_cost_reduction_per_hour_bytes_usd REAL,
    estimated_cost_reduction_per_hour_usd REAL,
    estimated_cost_reduction_per_hour_volume_usd REAL,
    estimated_volume_reduction_per_hour REAL,
    has_been_analyzed INTEGER,
    has_volumes INTEGER,
    log_event_id TEXT,
    observed_bytes_per_hour_after REAL,
    observed_bytes_per_hour_before REAL,
    observed_cost_per_hour_after_bytes_usd REAL,
    observed_cost_per_hour_after_usd REAL,
    observed_cost_per_hour_after_volume_usd REAL,
    observed_cost_per_hour_before_bytes_usd REAL,
    observed_cost_per_hour_before_usd REAL,
    observed_cost_per_hour_before_volume_usd REAL,
    observed_volume_per_hour_after REAL,
    observed_volume_per_hour_before REAL,
    pending_policy_count INTEGER,
    policy_count INTEGER,
    refreshed_at TEXT,
    service_id TEXT,
    status TEXT,
    volume_per_hour REAL
);

CREATE TABLE log_events (
    id TEXT,
    account_id TEXT,
    analyzed_at TEXT,
    created_at TEXT,
    description TEXT,
    examples TEXT,
    matchers TEXT,
    name TEXT,
    service_id TEXT,
    updated_at TEXT
);

CREATE TABLE messages (
    id TEXT,
    account_id TEXT,
    content TEXT,
    conversation_id TEXT,
    created_at TEXT,
    model TEXT,
    role TEXT,
    stop_reason TEXT
);

CREATE TABLE service_statuses_cache (
    id TEXT,
    account_id TEXT,
    datadog_account_id TEXT,
    error TEXT,
    error_at TEXT,
    estimated_bytes_reduction_per_hour REAL,
    estimated_cost_reduction_per_hour_bytes_usd REAL,
    estimated_cost_reduction_per_hour_usd REAL,
    estimated_cost_reduction_per_hour_volume_usd REAL,
    estimated_volume_reduction_per_hour REAL,
    health TEXT,
    log_event_analyzed_count INTEGER,
    log_event_bytes_per_hour REAL,
    log_event_cost_per_hour_bytes_usd REAL,
    log_event_cost_per_hour_usd REAL,
    log_event_cost_per_hour_volume_usd REAL,
    log_event_count INTEGER,
    log_event_quarantined_count INTEGER,
    log_event_volume_per_hour REAL,
    observed_bytes_per_hour_after REAL,
    observed_bytes_per_hour_before REAL,
    observed_cost_per_hour_after_bytes_usd REAL,
    observed_cost_per_hour_after_usd REAL,
    observed_cost_per_hour_after_volume_usd REAL,
    observed_cost_per_hour_before_bytes_usd REAL,
    observed_cost_per_hour_before_usd REAL,
    observed_cost_per_hour_before_volume_usd REAL,
    observed_volume_per_hour_after REAL,
    observed_volume_per_hour_before REAL,
    policy_approved_count INTEGER,
    policy_dismissed_count INTEGER,
    policy_pending_count INTEGER,
    refreshed_at TEXT,
    service_cost_per_hour_volume_usd REAL,
    service_id TEXT,
    service_volume_per_hour REAL,
    warning TEXT,
    warning_at TEXT
);

CREATE TABLE services (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    description TEXT,
    enabled INTEGER,
    initial_weekly_log_count INTEGER,
    name TEXT,
    updated_at TEXT
);

CREATE TABLE teams (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    name TEXT,
    updated_at TEXT,
    workspace_id TEXT
);

CREATE TABLE view_favorites (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    user_id TEXT,
    view_id TEXT
);

CREATE TABLE views (
    id TEXT,
    account_id TEXT,
    conversation_id TEXT,
    created_at TEXT,
    created_by TEXT,
    entity_type TEXT,
    forked_from_id TEXT,
    message_id TEXT,
    query TEXT
);

CREATE TABLE workspaces (
    id TEXT,
    account_id TEXT,
    created_at TEXT,
    name TEXT,
    purpose TEXT,
    updated_at TEXT
);
