// Code generated by go generate; DO NOT EDIT.
//
// To regenerate: doppler run -- go generate ./internal/powersync

package sqlite

// Service represents a row in the services table.
type Service struct {
	ID                    string `json:"id"`                       // uuid
	AccountID             string `json:"account_id"`               // uuid
	CreatedAt             string `json:"created_at"`               // timestamptz
	Description           string `json:"description"`              // text
	Enabled               int64  `json:"enabled"`                  // bool
	InitialWeeklyLogCount int64  `json:"initial_weekly_log_count"` // int8
	Name                  string `json:"name"`                     // varchar
	UpdatedAt             string `json:"updated_at"`               // timestamptz
}
