// Code generated by go generate; DO NOT EDIT.
//
// To regenerate: doppler run -- go generate ./internal/powersync

package sqlite

// Team represents a row in the teams table.
type Team struct {
	ID          string `json:"id"`           // uuid
	AccountID   string `json:"account_id"`   // uuid
	CreatedAt   string `json:"created_at"`   // timestamptz
	Name        string `json:"name"`         // varchar
	UpdatedAt   string `json:"updated_at"`   // timestamptz
	WorkspaceID string `json:"workspace_id"` // uuid
}
