// Code generated by go generate; DO NOT EDIT.
//
// To regenerate: doppler run -- go generate ./internal/powersync

package sqlite

// Workspace represents a row in the workspaces table.
type Workspace struct {
	ID        string `json:"id"`         // uuid
	AccountID string `json:"account_id"` // uuid
	CreatedAt string `json:"created_at"` // timestamptz
	Name      string `json:"name"`       // varchar
	Purpose   string `json:"purpose"`    // varchar
	UpdatedAt string `json:"updated_at"` // timestamptz
}
