// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package conversationsdb

import (
	"context"
)

const create = `-- name: Create :exec
INSERT INTO conversations (id, title, created_at)
VALUES (?, ?, ?)
`

type CreateParams struct {
	ID        string
	Title     *string
	CreatedAt string
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.ExecContext(ctx, create, arg.ID, arg.Title, arg.CreatedAt)
	return err
}

const delete = `-- name: Delete :exec
DELETE FROM conversations
WHERE id = ?
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const list = `-- name: List :many
SELECT id, title, created_at
FROM conversations
ORDER BY created_at DESC
`

func (q *Queries) List(ctx context.Context) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
