// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// CreateAccountCreateAccount includes the requested fields of the GraphQL type Account.
type CreateAccountCreateAccount struct {
	// Unique identifier of the account
	Id string `json:"id"`
	// Human-readable name within the organization
	Name string `json:"name"`
	// When the account was created
	CreatedAt time.Time `json:"createdAt"`
}

// GetId returns CreateAccountCreateAccount.Id, and is useful for accessing the field via an interface.
func (v *CreateAccountCreateAccount) GetId() string { return v.Id }

// GetName returns CreateAccountCreateAccount.Name, and is useful for accessing the field via an interface.
func (v *CreateAccountCreateAccount) GetName() string { return v.Name }

// GetCreatedAt returns CreateAccountCreateAccount.CreatedAt, and is useful for accessing the field via an interface.
func (v *CreateAccountCreateAccount) GetCreatedAt() time.Time { return v.CreatedAt }

// CreateAccountInput is used for create Account object.
// Input was generated by ent.
type CreateAccountInput struct {
	// Human-readable name within the organization
	Name             string `json:"name"`
	OrganizationID   string `json:"organizationID"`
	DatadogAccountID string `json:"datadogAccountID"`
}

// GetName returns CreateAccountInput.Name, and is useful for accessing the field via an interface.
func (v *CreateAccountInput) GetName() string { return v.Name }

// GetOrganizationID returns CreateAccountInput.OrganizationID, and is useful for accessing the field via an interface.
func (v *CreateAccountInput) GetOrganizationID() string { return v.OrganizationID }

// GetDatadogAccountID returns CreateAccountInput.DatadogAccountID, and is useful for accessing the field via an interface.
func (v *CreateAccountInput) GetDatadogAccountID() string { return v.DatadogAccountID }

// CreateAccountResponse is returned by CreateAccount on success.
type CreateAccountResponse struct {
	CreateAccount CreateAccountCreateAccount `json:"createAccount"`
}

// GetCreateAccount returns CreateAccountResponse.CreateAccount, and is useful for accessing the field via an interface.
func (v *CreateAccountResponse) GetCreateAccount() CreateAccountCreateAccount { return v.CreateAccount }

// CreateDatadogAccountInput is used for create DatadogAccount object.
// Input was generated by ent.
type CreateDatadogAccountInput struct {
	// Display name for this Datadog account
	Name string `json:"name"`
	// Datadog site for this account (must be explicit)
	Site      DatadogAccountSite `json:"site"`
	AccountID string             `json:"accountID"`
}

// GetName returns CreateDatadogAccountInput.Name, and is useful for accessing the field via an interface.
func (v *CreateDatadogAccountInput) GetName() string { return v.Name }

// GetSite returns CreateDatadogAccountInput.Site, and is useful for accessing the field via an interface.
func (v *CreateDatadogAccountInput) GetSite() DatadogAccountSite { return v.Site }

// GetAccountID returns CreateDatadogAccountInput.AccountID, and is useful for accessing the field via an interface.
func (v *CreateDatadogAccountInput) GetAccountID() string { return v.AccountID }

// CreateDatadogAccountWithCredentialsCreateDatadogAccount includes the requested fields of the GraphQL type DatadogAccount.
type CreateDatadogAccountWithCredentialsCreateDatadogAccount struct {
	// Unique identifier of the Datadog configuration
	Id string `json:"id"`
	// Display name for this Datadog account
	Name string `json:"name"`
	// Datadog site for this account (must be explicit)
	Site DatadogAccountSite `json:"site"`
	// When the Datadog account was created
	CreatedAt time.Time `json:"createdAt"`
	// When the Datadog account was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// GetId returns CreateDatadogAccountWithCredentialsCreateDatadogAccount.Id, and is useful for accessing the field via an interface.
func (v *CreateDatadogAccountWithCredentialsCreateDatadogAccount) GetId() string { return v.Id }

// GetName returns CreateDatadogAccountWithCredentialsCreateDatadogAccount.Name, and is useful for accessing the field via an interface.
func (v *CreateDatadogAccountWithCredentialsCreateDatadogAccount) GetName() string { return v.Name }

// GetSite returns CreateDatadogAccountWithCredentialsCreateDatadogAccount.Site, and is useful for accessing the field via an interface.
func (v *CreateDatadogAccountWithCredentialsCreateDatadogAccount) GetSite() DatadogAccountSite {
	return v.Site
}

// GetCreatedAt returns CreateDatadogAccountWithCredentialsCreateDatadogAccount.CreatedAt, and is useful for accessing the field via an interface.
func (v *CreateDatadogAccountWithCredentialsCreateDatadogAccount) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// GetUpdatedAt returns CreateDatadogAccountWithCredentialsCreateDatadogAccount.UpdatedAt, and is useful for accessing the field via an interface.
func (v *CreateDatadogAccountWithCredentialsCreateDatadogAccount) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

type CreateDatadogAccountWithCredentialsInput struct {
	Attributes  CreateDatadogAccountInput     `json:"attributes"`
	Credentials CreateDatadogCredentialsInput `json:"credentials"`
}

// GetAttributes returns CreateDatadogAccountWithCredentialsInput.Attributes, and is useful for accessing the field via an interface.
func (v *CreateDatadogAccountWithCredentialsInput) GetAttributes() CreateDatadogAccountInput {
	return v.Attributes
}

// GetCredentials returns CreateDatadogAccountWithCredentialsInput.Credentials, and is useful for accessing the field via an interface.
func (v *CreateDatadogAccountWithCredentialsInput) GetCredentials() CreateDatadogCredentialsInput {
	return v.Credentials
}

// CreateDatadogAccountWithCredentialsResponse is returned by CreateDatadogAccountWithCredentials on success.
type CreateDatadogAccountWithCredentialsResponse struct {
	CreateDatadogAccount CreateDatadogAccountWithCredentialsCreateDatadogAccount `json:"createDatadogAccount"`
}

// GetCreateDatadogAccount returns CreateDatadogAccountWithCredentialsResponse.CreateDatadogAccount, and is useful for accessing the field via an interface.
func (v *CreateDatadogAccountWithCredentialsResponse) GetCreateDatadogAccount() CreateDatadogAccountWithCredentialsCreateDatadogAccount {
	return v.CreateDatadogAccount
}

type CreateDatadogCredentialsInput struct {
	ApiKey string `json:"apiKey"`
	AppKey string `json:"appKey"`
}

// GetApiKey returns CreateDatadogCredentialsInput.ApiKey, and is useful for accessing the field via an interface.
func (v *CreateDatadogCredentialsInput) GetApiKey() string { return v.ApiKey }

// GetAppKey returns CreateDatadogCredentialsInput.AppKey, and is useful for accessing the field via an interface.
func (v *CreateDatadogCredentialsInput) GetAppKey() string { return v.AppKey }

// CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResult includes the requested fields of the GraphQL type OrganizationBootstrapResult.
type CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResult struct {
	Organization CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultOrganization `json:"organization"`
	Account      CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultAccount      `json:"account"`
	Workspace    CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultWorkspace    `json:"workspace"`
}

// GetOrganization returns CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResult.Organization, and is useful for accessing the field via an interface.
func (v *CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResult) GetOrganization() CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultOrganization {
	return v.Organization
}

// GetAccount returns CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResult.Account, and is useful for accessing the field via an interface.
func (v *CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResult) GetAccount() CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultAccount {
	return v.Account
}

// GetWorkspace returns CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResult.Workspace, and is useful for accessing the field via an interface.
func (v *CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResult) GetWorkspace() CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultWorkspace {
	return v.Workspace
}

// CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultAccount includes the requested fields of the GraphQL type Account.
type CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultAccount struct {
	// Unique identifier of the account
	Id string `json:"id"`
	// Human-readable name within the organization
	Name string `json:"name"`
}

// GetId returns CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultAccount.Id, and is useful for accessing the field via an interface.
func (v *CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultAccount) GetId() string {
	return v.Id
}

// GetName returns CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultAccount.Name, and is useful for accessing the field via an interface.
func (v *CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultAccount) GetName() string {
	return v.Name
}

// CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultOrganization includes the requested fields of the GraphQL type Organization.
type CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultOrganization struct {
	// Unique identifier of the organization
	Id string `json:"id"`
	// Human-readable name, unique across the system
	Name string `json:"name"`
	// When the organization was created
	CreatedAt time.Time `json:"createdAt"`
}

// GetId returns CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultOrganization.Id, and is useful for accessing the field via an interface.
func (v *CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultOrganization) GetId() string {
	return v.Id
}

// GetName returns CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultOrganization.Name, and is useful for accessing the field via an interface.
func (v *CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultOrganization) GetName() string {
	return v.Name
}

// GetCreatedAt returns CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultOrganization.CreatedAt, and is useful for accessing the field via an interface.
func (v *CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultOrganization) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultWorkspace includes the requested fields of the GraphQL type Workspace.
type CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultWorkspace struct {
	// Unique identifier of the workspace
	Id string `json:"id"`
	// Human-readable name within the account
	Name string `json:"name"`
}

// GetId returns CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultWorkspace.Id, and is useful for accessing the field via an interface.
func (v *CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultWorkspace) GetId() string {
	return v.Id
}

// GetName returns CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultWorkspace.Name, and is useful for accessing the field via an interface.
func (v *CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResultWorkspace) GetName() string {
	return v.Name
}

// CreateOrganizationAndBootstrapResponse is returned by CreateOrganizationAndBootstrap on success.
type CreateOrganizationAndBootstrapResponse struct {
	CreateOrganizationAndBootstrap CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResult `json:"createOrganizationAndBootstrap"`
}

// GetCreateOrganizationAndBootstrap returns CreateOrganizationAndBootstrapResponse.CreateOrganizationAndBootstrap, and is useful for accessing the field via an interface.
func (v *CreateOrganizationAndBootstrapResponse) GetCreateOrganizationAndBootstrap() CreateOrganizationAndBootstrapCreateOrganizationAndBootstrapOrganizationBootstrapResult {
	return v.CreateOrganizationAndBootstrap
}

// CreateOrganizationInput is used for create Organization object.
// Input was generated by ent.
type CreateOrganizationInput struct {
	// Human-readable name, unique across the system
	Name string `json:"name"`
}

// GetName returns CreateOrganizationInput.Name, and is useful for accessing the field via an interface.
func (v *CreateOrganizationInput) GetName() string { return v.Name }

// DatadogAccountSite is enum for the field site
type DatadogAccountSite string

const (
	DatadogAccountSiteUs1    DatadogAccountSite = "US1"
	DatadogAccountSiteUs3    DatadogAccountSite = "US3"
	DatadogAccountSiteUs5    DatadogAccountSite = "US5"
	DatadogAccountSiteEu1    DatadogAccountSite = "EU1"
	DatadogAccountSiteUs1Fed DatadogAccountSite = "US1_FED"
	DatadogAccountSiteAp1    DatadogAccountSite = "AP1"
	DatadogAccountSiteAp2    DatadogAccountSite = "AP2"
)

var AllDatadogAccountSite = []DatadogAccountSite{
	DatadogAccountSiteUs1,
	DatadogAccountSiteUs3,
	DatadogAccountSiteUs5,
	DatadogAccountSiteEu1,
	DatadogAccountSiteUs1Fed,
	DatadogAccountSiteAp1,
	DatadogAccountSiteAp2,
}

// Current state of a discovery operation.
type DiscoveryStatus string

const (
	// Discovery has not started yet
	DiscoveryStatusPending DiscoveryStatus = "PENDING"
	// Discovery is actively running
	DiscoveryStatusDiscovering DiscoveryStatus = "DISCOVERING"
	// Discovery is ready (caught up, good enough to proceed)
	DiscoveryStatusReady DiscoveryStatus = "READY"
	// Discovery has encountered errors
	DiscoveryStatusError DiscoveryStatus = "ERROR"
)

var AllDiscoveryStatus = []DiscoveryStatus{
	DiscoveryStatusPending,
	DiscoveryStatusDiscovering,
	DiscoveryStatusReady,
	DiscoveryStatusError,
}

// EnableServiceResponse is returned by EnableService on success.
type EnableServiceResponse struct {
	UpdateService EnableServiceUpdateService `json:"updateService"`
}

// GetUpdateService returns EnableServiceResponse.UpdateService, and is useful for accessing the field via an interface.
func (v *EnableServiceResponse) GetUpdateService() EnableServiceUpdateService { return v.UpdateService }

// EnableServiceUpdateService includes the requested fields of the GraphQL type Service.
type EnableServiceUpdateService struct {
	// Unique identifier of the service
	Id string `json:"id"`
	// Service identifier in telemetry (e.g., 'checkout-service')
	Name string `json:"name"`
	// Whether telemetry analysis is enabled
	Enabled bool `json:"enabled"`
}

// GetId returns EnableServiceUpdateService.Id, and is useful for accessing the field via an interface.
func (v *EnableServiceUpdateService) GetId() string { return v.Id }

// GetName returns EnableServiceUpdateService.Name, and is useful for accessing the field via an interface.
func (v *EnableServiceUpdateService) GetName() string { return v.Name }

// GetEnabled returns EnableServiceUpdateService.Enabled, and is useful for accessing the field via an interface.
func (v *EnableServiceUpdateService) GetEnabled() bool { return v.Enabled }

// GetAccountAccountsAccountConnection includes the requested fields of the GraphQL type AccountConnection.
// The GraphQL type's documentation follows.
//
// A connection to a list of items.
type GetAccountAccountsAccountConnection struct {
	// A list of edges.
	Edges []GetAccountAccountsAccountConnectionEdgesAccountEdge `json:"edges"`
}

// GetEdges returns GetAccountAccountsAccountConnection.Edges, and is useful for accessing the field via an interface.
func (v *GetAccountAccountsAccountConnection) GetEdges() []GetAccountAccountsAccountConnectionEdgesAccountEdge {
	return v.Edges
}

// GetAccountAccountsAccountConnectionEdgesAccountEdge includes the requested fields of the GraphQL type AccountEdge.
// The GraphQL type's documentation follows.
//
// An edge in a connection.
type GetAccountAccountsAccountConnectionEdgesAccountEdge struct {
	// The item at the end of the edge.
	Node GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccount `json:"node"`
}

// GetNode returns GetAccountAccountsAccountConnectionEdgesAccountEdge.Node, and is useful for accessing the field via an interface.
func (v *GetAccountAccountsAccountConnectionEdgesAccountEdge) GetNode() GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccount {
	return v.Node
}

// GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccount includes the requested fields of the GraphQL type Account.
type GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccount struct {
	// Unique identifier of the account
	Id string `json:"id"`
	// Datadog integration configuration
	DatadogAccount GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccountDatadogAccount `json:"datadogAccount"`
}

// GetId returns GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccount.Id, and is useful for accessing the field via an interface.
func (v *GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccount) GetId() string { return v.Id }

// GetDatadogAccount returns GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccount.DatadogAccount, and is useful for accessing the field via an interface.
func (v *GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccount) GetDatadogAccount() GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccountDatadogAccount {
	return v.DatadogAccount
}

// GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccountDatadogAccount includes the requested fields of the GraphQL type DatadogAccount.
type GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccountDatadogAccount struct {
	// Unique identifier of the Datadog configuration
	Id string `json:"id"`
	// Display name for this Datadog account
	Name string `json:"name"`
	// Datadog site for this account (must be explicit)
	Site DatadogAccountSite `json:"site"`
}

// GetId returns GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccountDatadogAccount.Id, and is useful for accessing the field via an interface.
func (v *GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccountDatadogAccount) GetId() string {
	return v.Id
}

// GetName returns GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccountDatadogAccount.Name, and is useful for accessing the field via an interface.
func (v *GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccountDatadogAccount) GetName() string {
	return v.Name
}

// GetSite returns GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccountDatadogAccount.Site, and is useful for accessing the field via an interface.
func (v *GetAccountAccountsAccountConnectionEdgesAccountEdgeNodeAccountDatadogAccount) GetSite() DatadogAccountSite {
	return v.Site
}

// GetAccountResponse is returned by GetAccount on success.
type GetAccountResponse struct {
	// Query accounts. Accounts belong to an organization and contain services and workspaces.
	Accounts GetAccountAccountsAccountConnection `json:"accounts"`
}

// GetAccounts returns GetAccountResponse.Accounts, and is useful for accessing the field via an interface.
func (v *GetAccountResponse) GetAccounts() GetAccountAccountsAccountConnection { return v.Accounts }

// GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnection includes the requested fields of the GraphQL type DatadogAccountConnection.
// The GraphQL type's documentation follows.
//
// A connection to a list of items.
type GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnection struct {
	// A list of edges.
	Edges []GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdge `json:"edges"`
}

// GetEdges returns GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnection.Edges, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnection) GetEdges() []GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdge {
	return v.Edges
}

// GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdge includes the requested fields of the GraphQL type DatadogAccountEdge.
// The GraphQL type's documentation follows.
//
// An edge in a connection.
type GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdge struct {
	// The item at the end of the edge.
	Node GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount `json:"node"`
}

// GetNode returns GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdge.Node, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdge) GetNode() GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount {
	return v.Node
}

// GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount includes the requested fields of the GraphQL type DatadogAccount.
type GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount struct {
	// Unique identifier of the Datadog configuration
	Id string `json:"id"`
	// Aggregate log event discovery progress across all enabled services in this Datadog account.
	// Shows overall discovery status and progress percentage.
	LogEventDiscoveryProgress GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress `json:"logEventDiscoveryProgress"`
}

// GetId returns GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount.Id, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount) GetId() string {
	return v.Id
}

// GetLogEventDiscoveryProgress returns GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount.LogEventDiscoveryProgress, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount) GetLogEventDiscoveryProgress() GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress {
	return v.LogEventDiscoveryProgress
}

// GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress includes the requested fields of the GraphQL type LogEventDiscoveryProgress.
// The GraphQL type's documentation follows.
//
// Log event discovery progress for a service from an integration account.
// Tracks discovery status and how much of the service's logs have been cataloged.
type GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress struct {
	// Current status of log event discovery
	Status DiscoveryStatus `json:"status"`
	// Discovery progress percentage (0-100), null if no volume data yet
	PercentComplete float64 `json:"percentComplete"`
	// Weekly log volume reported by the integration (last 7 days)
	WeeklyVolume int `json:"weeklyVolume"`
	// Weekly volume of logs discovered and cataloged (last 7 days)
	WeeklyDiscoveredVolume float64 `json:"weeklyDiscoveredVolume"`
	// Last error message if discovery failed
	LastError string `json:"lastError"`
	// When the current/most recent discovery run started
	StartedAt time.Time `json:"startedAt"`
	// When the most recent discovery run completed (successfully or with error)
	CompletedAt time.Time `json:"completedAt"`
	// Number of consecutive failures
	ConsecutiveFailures int `json:"consecutiveFailures"`
}

// GetStatus returns GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress.Status, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress) GetStatus() DiscoveryStatus {
	return v.Status
}

// GetPercentComplete returns GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress.PercentComplete, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress) GetPercentComplete() float64 {
	return v.PercentComplete
}

// GetWeeklyVolume returns GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress.WeeklyVolume, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress) GetWeeklyVolume() int {
	return v.WeeklyVolume
}

// GetWeeklyDiscoveredVolume returns GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress.WeeklyDiscoveredVolume, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress) GetWeeklyDiscoveredVolume() float64 {
	return v.WeeklyDiscoveredVolume
}

// GetLastError returns GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress.LastError, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress) GetLastError() string {
	return v.LastError
}

// GetStartedAt returns GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress.StartedAt, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress) GetStartedAt() time.Time {
	return v.StartedAt
}

// GetCompletedAt returns GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress.CompletedAt, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress) GetCompletedAt() time.Time {
	return v.CompletedAt
}

// GetConsecutiveFailures returns GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress.ConsecutiveFailures, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountLogEventDiscoveryProgress) GetConsecutiveFailures() int {
	return v.ConsecutiveFailures
}

// GetDatadogAccountLogDiscoveryProgressResponse is returned by GetDatadogAccountLogDiscoveryProgress on success.
type GetDatadogAccountLogDiscoveryProgressResponse struct {
	// Query connected Datadog accounts.
	DatadogAccounts GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnection `json:"datadogAccounts"`
}

// GetDatadogAccounts returns GetDatadogAccountLogDiscoveryProgressResponse.DatadogAccounts, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountLogDiscoveryProgressResponse) GetDatadogAccounts() GetDatadogAccountLogDiscoveryProgressDatadogAccountsDatadogAccountConnection {
	return v.DatadogAccounts
}

// GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnection includes the requested fields of the GraphQL type DatadogAccountConnection.
// The GraphQL type's documentation follows.
//
// A connection to a list of items.
type GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnection struct {
	// A list of edges.
	Edges []GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdge `json:"edges"`
}

// GetEdges returns GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnection.Edges, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnection) GetEdges() []GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdge {
	return v.Edges
}

// GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdge includes the requested fields of the GraphQL type DatadogAccountEdge.
// The GraphQL type's documentation follows.
//
// An edge in a connection.
type GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdge struct {
	// The item at the end of the edge.
	Node GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount `json:"node"`
}

// GetNode returns GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdge.Node, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdge) GetNode() GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount {
	return v.Node
}

// GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount includes the requested fields of the GraphQL type DatadogAccount.
type GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount struct {
	// Unique identifier of the Datadog configuration
	Id string `json:"id"`
	// Service discovery progress for this Datadog account.
	// Shows whether service discovery is running, completed, or has errors.
	ServiceDiscoveryProgress GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress `json:"serviceDiscoveryProgress"`
}

// GetId returns GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount.Id, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount) GetId() string {
	return v.Id
}

// GetServiceDiscoveryProgress returns GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount.ServiceDiscoveryProgress, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccount) GetServiceDiscoveryProgress() GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress {
	return v.ServiceDiscoveryProgress
}

// GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress includes the requested fields of the GraphQL type ServiceDiscoveryProgress.
// The GraphQL type's documentation follows.
//
// Service discovery progress for an integration account.
// Tracks whether services have been discovered from the integration.
type GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress struct {
	// Current status of service discovery
	Status DiscoveryStatus `json:"status"`
	// Number of services discovered from this integration
	ServicesDiscovered int `json:"servicesDiscovered"`
	// Last error message if discovery failed
	LastError string `json:"lastError"`
	// When the current/most recent discovery run started
	StartedAt time.Time `json:"startedAt"`
	// When the most recent discovery run completed (successfully or with error)
	CompletedAt time.Time `json:"completedAt"`
	// Number of consecutive failures
	ConsecutiveFailures int `json:"consecutiveFailures"`
}

// GetStatus returns GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress.Status, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress) GetStatus() DiscoveryStatus {
	return v.Status
}

// GetServicesDiscovered returns GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress.ServicesDiscovered, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress) GetServicesDiscovered() int {
	return v.ServicesDiscovered
}

// GetLastError returns GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress.LastError, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress) GetLastError() string {
	return v.LastError
}

// GetStartedAt returns GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress.StartedAt, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress) GetStartedAt() time.Time {
	return v.StartedAt
}

// GetCompletedAt returns GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress.CompletedAt, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress) GetCompletedAt() time.Time {
	return v.CompletedAt
}

// GetConsecutiveFailures returns GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress.ConsecutiveFailures, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnectionEdgesDatadogAccountEdgeNodeDatadogAccountServiceDiscoveryProgress) GetConsecutiveFailures() int {
	return v.ConsecutiveFailures
}

// GetDatadogAccountServiceDiscoveryProgressResponse is returned by GetDatadogAccountServiceDiscoveryProgress on success.
type GetDatadogAccountServiceDiscoveryProgressResponse struct {
	// Query connected Datadog accounts.
	DatadogAccounts GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnection `json:"datadogAccounts"`
}

// GetDatadogAccounts returns GetDatadogAccountServiceDiscoveryProgressResponse.DatadogAccounts, and is useful for accessing the field via an interface.
func (v *GetDatadogAccountServiceDiscoveryProgressResponse) GetDatadogAccounts() GetDatadogAccountServiceDiscoveryProgressDatadogAccountsDatadogAccountConnection {
	return v.DatadogAccounts
}

// GetServiceByNameResponse is returned by GetServiceByName on success.
type GetServiceByNameResponse struct {
	// Query services in your system.
	Services GetServiceByNameServicesServiceConnection `json:"services"`
}

// GetServices returns GetServiceByNameResponse.Services, and is useful for accessing the field via an interface.
func (v *GetServiceByNameResponse) GetServices() GetServiceByNameServicesServiceConnection {
	return v.Services
}

// GetServiceByNameServicesServiceConnection includes the requested fields of the GraphQL type ServiceConnection.
// The GraphQL type's documentation follows.
//
// A connection to a list of items.
type GetServiceByNameServicesServiceConnection struct {
	// A list of edges.
	Edges []GetServiceByNameServicesServiceConnectionEdgesServiceEdge `json:"edges"`
}

// GetEdges returns GetServiceByNameServicesServiceConnection.Edges, and is useful for accessing the field via an interface.
func (v *GetServiceByNameServicesServiceConnection) GetEdges() []GetServiceByNameServicesServiceConnectionEdgesServiceEdge {
	return v.Edges
}

// GetServiceByNameServicesServiceConnectionEdgesServiceEdge includes the requested fields of the GraphQL type ServiceEdge.
// The GraphQL type's documentation follows.
//
// An edge in a connection.
type GetServiceByNameServicesServiceConnectionEdgesServiceEdge struct {
	// The item at the end of the edge.
	Node GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService `json:"node"`
}

// GetNode returns GetServiceByNameServicesServiceConnectionEdgesServiceEdge.Node, and is useful for accessing the field via an interface.
func (v *GetServiceByNameServicesServiceConnectionEdgesServiceEdge) GetNode() GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService {
	return v.Node
}

// GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService includes the requested fields of the GraphQL type Service.
type GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService struct {
	// Unique identifier of the service
	Id string `json:"id"`
	// Service identifier in telemetry (e.g., 'checkout-service')
	Name string `json:"name"`
	// Description of service and telemetry characteristics
	Description string `json:"description"`
	// Whether telemetry analysis is enabled
	Enabled bool `json:"enabled"`
	// When the service was created
	CreatedAt time.Time `json:"createdAt"`
	// When the service was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// GetId returns GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService.Id, and is useful for accessing the field via an interface.
func (v *GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService) GetId() string {
	return v.Id
}

// GetName returns GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService.Name, and is useful for accessing the field via an interface.
func (v *GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService) GetName() string {
	return v.Name
}

// GetDescription returns GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService.Description, and is useful for accessing the field via an interface.
func (v *GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService) GetDescription() string {
	return v.Description
}

// GetEnabled returns GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService.Enabled, and is useful for accessing the field via an interface.
func (v *GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService) GetEnabled() bool {
	return v.Enabled
}

// GetCreatedAt returns GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// GetUpdatedAt returns GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService.UpdatedAt, and is useful for accessing the field via an interface.
func (v *GetServiceByNameServicesServiceConnectionEdgesServiceEdgeNodeService) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

// GetServiceNode includes the requested fields of the GraphQL interface Node.
//
// GetServiceNode is implemented by the following types:
// GetServiceNodeAccount
// GetServiceNodeChat
// GetServiceNodeDatadogAccount
// GetServiceNodeDatadogLogIndex
// GetServiceNodeLogEvent
// GetServiceNodeLogEventVolume
// GetServiceNodeLogRule
// GetServiceNodeLogRuleDeployment
// GetServiceNodeMessage
// GetServiceNodeOrganization
// GetServiceNodeService
// GetServiceNodeServiceLogVolume
// GetServiceNodeTeam
// GetServiceNodeWorkspace
// The GraphQL type's documentation follows.
//
// An object with an ID.
// Follows the [Relay Global Object Identification Specification](https://relay.dev/graphql/objectidentification.htm)
type GetServiceNode interface {
	implementsGraphQLInterfaceGetServiceNode()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *GetServiceNodeAccount) implementsGraphQLInterfaceGetServiceNode()           {}
func (v *GetServiceNodeChat) implementsGraphQLInterfaceGetServiceNode()              {}
func (v *GetServiceNodeDatadogAccount) implementsGraphQLInterfaceGetServiceNode()    {}
func (v *GetServiceNodeDatadogLogIndex) implementsGraphQLInterfaceGetServiceNode()   {}
func (v *GetServiceNodeLogEvent) implementsGraphQLInterfaceGetServiceNode()          {}
func (v *GetServiceNodeLogEventVolume) implementsGraphQLInterfaceGetServiceNode()    {}
func (v *GetServiceNodeLogRule) implementsGraphQLInterfaceGetServiceNode()           {}
func (v *GetServiceNodeLogRuleDeployment) implementsGraphQLInterfaceGetServiceNode() {}
func (v *GetServiceNodeMessage) implementsGraphQLInterfaceGetServiceNode()           {}
func (v *GetServiceNodeOrganization) implementsGraphQLInterfaceGetServiceNode()      {}
func (v *GetServiceNodeService) implementsGraphQLInterfaceGetServiceNode()           {}
func (v *GetServiceNodeServiceLogVolume) implementsGraphQLInterfaceGetServiceNode()  {}
func (v *GetServiceNodeTeam) implementsGraphQLInterfaceGetServiceNode()              {}
func (v *GetServiceNodeWorkspace) implementsGraphQLInterfaceGetServiceNode()         {}

func __unmarshalGetServiceNode(b []byte, v *GetServiceNode) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Account":
		*v = new(GetServiceNodeAccount)
		return json.Unmarshal(b, *v)
	case "Chat":
		*v = new(GetServiceNodeChat)
		return json.Unmarshal(b, *v)
	case "DatadogAccount":
		*v = new(GetServiceNodeDatadogAccount)
		return json.Unmarshal(b, *v)
	case "DatadogLogIndex":
		*v = new(GetServiceNodeDatadogLogIndex)
		return json.Unmarshal(b, *v)
	case "LogEvent":
		*v = new(GetServiceNodeLogEvent)
		return json.Unmarshal(b, *v)
	case "LogEventVolume":
		*v = new(GetServiceNodeLogEventVolume)
		return json.Unmarshal(b, *v)
	case "LogRule":
		*v = new(GetServiceNodeLogRule)
		return json.Unmarshal(b, *v)
	case "LogRuleDeployment":
		*v = new(GetServiceNodeLogRuleDeployment)
		return json.Unmarshal(b, *v)
	case "Message":
		*v = new(GetServiceNodeMessage)
		return json.Unmarshal(b, *v)
	case "Organization":
		*v = new(GetServiceNodeOrganization)
		return json.Unmarshal(b, *v)
	case "Service":
		*v = new(GetServiceNodeService)
		return json.Unmarshal(b, *v)
	case "ServiceLogVolume":
		*v = new(GetServiceNodeServiceLogVolume)
		return json.Unmarshal(b, *v)
	case "Team":
		*v = new(GetServiceNodeTeam)
		return json.Unmarshal(b, *v)
	case "Workspace":
		*v = new(GetServiceNodeWorkspace)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing Node.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for GetServiceNode: "%v"`, tn.TypeName)
	}
}

func __marshalGetServiceNode(v *GetServiceNode) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *GetServiceNodeAccount:
		typename = "Account"

		result := struct {
			TypeName string `json:"__typename"`
			*GetServiceNodeAccount
		}{typename, v}
		return json.Marshal(result)
	case *GetServiceNodeChat:
		typename = "Chat"

		result := struct {
			TypeName string `json:"__typename"`
			*GetServiceNodeChat
		}{typename, v}
		return json.Marshal(result)
	case *GetServiceNodeDatadogAccount:
		typename = "DatadogAccount"

		result := struct {
			TypeName string `json:"__typename"`
			*GetServiceNodeDatadogAccount
		}{typename, v}
		return json.Marshal(result)
	case *GetServiceNodeDatadogLogIndex:
		typename = "DatadogLogIndex"

		result := struct {
			TypeName string `json:"__typename"`
			*GetServiceNodeDatadogLogIndex
		}{typename, v}
		return json.Marshal(result)
	case *GetServiceNodeLogEvent:
		typename = "LogEvent"

		result := struct {
			TypeName string `json:"__typename"`
			*GetServiceNodeLogEvent
		}{typename, v}
		return json.Marshal(result)
	case *GetServiceNodeLogEventVolume:
		typename = "LogEventVolume"

		result := struct {
			TypeName string `json:"__typename"`
			*GetServiceNodeLogEventVolume
		}{typename, v}
		return json.Marshal(result)
	case *GetServiceNodeLogRule:
		typename = "LogRule"

		result := struct {
			TypeName string `json:"__typename"`
			*GetServiceNodeLogRule
		}{typename, v}
		return json.Marshal(result)
	case *GetServiceNodeLogRuleDeployment:
		typename = "LogRuleDeployment"

		result := struct {
			TypeName string `json:"__typename"`
			*GetServiceNodeLogRuleDeployment
		}{typename, v}
		return json.Marshal(result)
	case *GetServiceNodeMessage:
		typename = "Message"

		result := struct {
			TypeName string `json:"__typename"`
			*GetServiceNodeMessage
		}{typename, v}
		return json.Marshal(result)
	case *GetServiceNodeOrganization:
		typename = "Organization"

		result := struct {
			TypeName string `json:"__typename"`
			*GetServiceNodeOrganization
		}{typename, v}
		return json.Marshal(result)
	case *GetServiceNodeService:
		typename = "Service"

		result := struct {
			TypeName string `json:"__typename"`
			*GetServiceNodeService
		}{typename, v}
		return json.Marshal(result)
	case *GetServiceNodeServiceLogVolume:
		typename = "ServiceLogVolume"

		result := struct {
			TypeName string `json:"__typename"`
			*GetServiceNodeServiceLogVolume
		}{typename, v}
		return json.Marshal(result)
	case *GetServiceNodeTeam:
		typename = "Team"

		result := struct {
			TypeName string `json:"__typename"`
			*GetServiceNodeTeam
		}{typename, v}
		return json.Marshal(result)
	case *GetServiceNodeWorkspace:
		typename = "Workspace"

		result := struct {
			TypeName string `json:"__typename"`
			*GetServiceNodeWorkspace
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for GetServiceNode: "%T"`, v)
	}
}

// GetServiceNodeAccount includes the requested fields of the GraphQL type Account.
type GetServiceNodeAccount struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetServiceNodeAccount.Typename, and is useful for accessing the field via an interface.
func (v *GetServiceNodeAccount) GetTypename() string { return v.Typename }

// GetServiceNodeChat includes the requested fields of the GraphQL type Chat.
type GetServiceNodeChat struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetServiceNodeChat.Typename, and is useful for accessing the field via an interface.
func (v *GetServiceNodeChat) GetTypename() string { return v.Typename }

// GetServiceNodeDatadogAccount includes the requested fields of the GraphQL type DatadogAccount.
type GetServiceNodeDatadogAccount struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetServiceNodeDatadogAccount.Typename, and is useful for accessing the field via an interface.
func (v *GetServiceNodeDatadogAccount) GetTypename() string { return v.Typename }

// GetServiceNodeDatadogLogIndex includes the requested fields of the GraphQL type DatadogLogIndex.
type GetServiceNodeDatadogLogIndex struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetServiceNodeDatadogLogIndex.Typename, and is useful for accessing the field via an interface.
func (v *GetServiceNodeDatadogLogIndex) GetTypename() string { return v.Typename }

// GetServiceNodeLogEvent includes the requested fields of the GraphQL type LogEvent.
type GetServiceNodeLogEvent struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetServiceNodeLogEvent.Typename, and is useful for accessing the field via an interface.
func (v *GetServiceNodeLogEvent) GetTypename() string { return v.Typename }

// GetServiceNodeLogEventVolume includes the requested fields of the GraphQL type LogEventVolume.
type GetServiceNodeLogEventVolume struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetServiceNodeLogEventVolume.Typename, and is useful for accessing the field via an interface.
func (v *GetServiceNodeLogEventVolume) GetTypename() string { return v.Typename }

// GetServiceNodeLogRule includes the requested fields of the GraphQL type LogRule.
type GetServiceNodeLogRule struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetServiceNodeLogRule.Typename, and is useful for accessing the field via an interface.
func (v *GetServiceNodeLogRule) GetTypename() string { return v.Typename }

// GetServiceNodeLogRuleDeployment includes the requested fields of the GraphQL type LogRuleDeployment.
type GetServiceNodeLogRuleDeployment struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetServiceNodeLogRuleDeployment.Typename, and is useful for accessing the field via an interface.
func (v *GetServiceNodeLogRuleDeployment) GetTypename() string { return v.Typename }

// GetServiceNodeMessage includes the requested fields of the GraphQL type Message.
type GetServiceNodeMessage struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetServiceNodeMessage.Typename, and is useful for accessing the field via an interface.
func (v *GetServiceNodeMessage) GetTypename() string { return v.Typename }

// GetServiceNodeOrganization includes the requested fields of the GraphQL type Organization.
type GetServiceNodeOrganization struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetServiceNodeOrganization.Typename, and is useful for accessing the field via an interface.
func (v *GetServiceNodeOrganization) GetTypename() string { return v.Typename }

// GetServiceNodeService includes the requested fields of the GraphQL type Service.
type GetServiceNodeService struct {
	Typename string `json:"__typename"`
	// Unique identifier of the service
	Id string `json:"id"`
	// Service identifier in telemetry (e.g., 'checkout-service')
	Name string `json:"name"`
	// Description of service and telemetry characteristics
	Description string `json:"description"`
	// Whether telemetry analysis is enabled
	Enabled bool `json:"enabled"`
	// When the service was created
	CreatedAt time.Time `json:"createdAt"`
	// When the service was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// Account this service belongs to
	Account GetServiceNodeServiceAccount `json:"account"`
	// Log event types produced by this service
	LogEvents []GetServiceNodeServiceLogEventsLogEvent `json:"logEvents"`
}

// GetTypename returns GetServiceNodeService.Typename, and is useful for accessing the field via an interface.
func (v *GetServiceNodeService) GetTypename() string { return v.Typename }

// GetId returns GetServiceNodeService.Id, and is useful for accessing the field via an interface.
func (v *GetServiceNodeService) GetId() string { return v.Id }

// GetName returns GetServiceNodeService.Name, and is useful for accessing the field via an interface.
func (v *GetServiceNodeService) GetName() string { return v.Name }

// GetDescription returns GetServiceNodeService.Description, and is useful for accessing the field via an interface.
func (v *GetServiceNodeService) GetDescription() string { return v.Description }

// GetEnabled returns GetServiceNodeService.Enabled, and is useful for accessing the field via an interface.
func (v *GetServiceNodeService) GetEnabled() bool { return v.Enabled }

// GetCreatedAt returns GetServiceNodeService.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetServiceNodeService) GetCreatedAt() time.Time { return v.CreatedAt }

// GetUpdatedAt returns GetServiceNodeService.UpdatedAt, and is useful for accessing the field via an interface.
func (v *GetServiceNodeService) GetUpdatedAt() time.Time { return v.UpdatedAt }

// GetAccount returns GetServiceNodeService.Account, and is useful for accessing the field via an interface.
func (v *GetServiceNodeService) GetAccount() GetServiceNodeServiceAccount { return v.Account }

// GetLogEvents returns GetServiceNodeService.LogEvents, and is useful for accessing the field via an interface.
func (v *GetServiceNodeService) GetLogEvents() []GetServiceNodeServiceLogEventsLogEvent {
	return v.LogEvents
}

// GetServiceNodeServiceAccount includes the requested fields of the GraphQL type Account.
type GetServiceNodeServiceAccount struct {
	// Unique identifier of the account
	Id string `json:"id"`
	// Human-readable name within the organization
	Name string `json:"name"`
}

// GetId returns GetServiceNodeServiceAccount.Id, and is useful for accessing the field via an interface.
func (v *GetServiceNodeServiceAccount) GetId() string { return v.Id }

// GetName returns GetServiceNodeServiceAccount.Name, and is useful for accessing the field via an interface.
func (v *GetServiceNodeServiceAccount) GetName() string { return v.Name }

// GetServiceNodeServiceLogEventsLogEvent includes the requested fields of the GraphQL type LogEvent.
type GetServiceNodeServiceLogEventsLogEvent struct {
	// Unique identifier of the log event
	Id string `json:"id"`
	// Snake_case identifier for event type
	Name string `json:"name"`
	// What this event pattern represents
	Description string `json:"description"`
	// When the log event was created
	CreatedAt time.Time `json:"createdAt"`
}

// GetId returns GetServiceNodeServiceLogEventsLogEvent.Id, and is useful for accessing the field via an interface.
func (v *GetServiceNodeServiceLogEventsLogEvent) GetId() string { return v.Id }

// GetName returns GetServiceNodeServiceLogEventsLogEvent.Name, and is useful for accessing the field via an interface.
func (v *GetServiceNodeServiceLogEventsLogEvent) GetName() string { return v.Name }

// GetDescription returns GetServiceNodeServiceLogEventsLogEvent.Description, and is useful for accessing the field via an interface.
func (v *GetServiceNodeServiceLogEventsLogEvent) GetDescription() string { return v.Description }

// GetCreatedAt returns GetServiceNodeServiceLogEventsLogEvent.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetServiceNodeServiceLogEventsLogEvent) GetCreatedAt() time.Time { return v.CreatedAt }

// GetServiceNodeServiceLogVolume includes the requested fields of the GraphQL type ServiceLogVolume.
type GetServiceNodeServiceLogVolume struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetServiceNodeServiceLogVolume.Typename, and is useful for accessing the field via an interface.
func (v *GetServiceNodeServiceLogVolume) GetTypename() string { return v.Typename }

// GetServiceNodeTeam includes the requested fields of the GraphQL type Team.
type GetServiceNodeTeam struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetServiceNodeTeam.Typename, and is useful for accessing the field via an interface.
func (v *GetServiceNodeTeam) GetTypename() string { return v.Typename }

// GetServiceNodeWorkspace includes the requested fields of the GraphQL type Workspace.
type GetServiceNodeWorkspace struct {
	Typename string `json:"__typename"`
}

// GetTypename returns GetServiceNodeWorkspace.Typename, and is useful for accessing the field via an interface.
func (v *GetServiceNodeWorkspace) GetTypename() string { return v.Typename }

// GetServiceResponse is returned by GetService on success.
type GetServiceResponse struct {
	// Fetches an object given its ID.
	Node GetServiceNode `json:"-"`
}

// GetNode returns GetServiceResponse.Node, and is useful for accessing the field via an interface.
func (v *GetServiceResponse) GetNode() GetServiceNode { return v.Node }

func (v *GetServiceResponse) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GetServiceResponse
		Node json.RawMessage `json:"node"`
		graphql.NoUnmarshalJSON
	}
	firstPass.GetServiceResponse = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Node
		src := firstPass.Node
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalGetServiceNode(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal GetServiceResponse.Node: %w", err)
			}
		}
	}
	return nil
}

type __premarshalGetServiceResponse struct {
	Node json.RawMessage `json:"node"`
}

func (v *GetServiceResponse) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GetServiceResponse) __premarshalJSON() (*__premarshalGetServiceResponse, error) {
	var retval __premarshalGetServiceResponse

	{

		dst := &retval.Node
		src := v.Node
		var err error
		*dst, err = __marshalGetServiceNode(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal GetServiceResponse.Node: %w", err)
		}
	}
	return &retval, nil
}

// ListAccountsAccountsAccountConnection includes the requested fields of the GraphQL type AccountConnection.
// The GraphQL type's documentation follows.
//
// A connection to a list of items.
type ListAccountsAccountsAccountConnection struct {
	// A list of edges.
	Edges []ListAccountsAccountsAccountConnectionEdgesAccountEdge `json:"edges"`
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
}

// GetEdges returns ListAccountsAccountsAccountConnection.Edges, and is useful for accessing the field via an interface.
func (v *ListAccountsAccountsAccountConnection) GetEdges() []ListAccountsAccountsAccountConnectionEdgesAccountEdge {
	return v.Edges
}

// GetTotalCount returns ListAccountsAccountsAccountConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *ListAccountsAccountsAccountConnection) GetTotalCount() int { return v.TotalCount }

// ListAccountsAccountsAccountConnectionEdgesAccountEdge includes the requested fields of the GraphQL type AccountEdge.
// The GraphQL type's documentation follows.
//
// An edge in a connection.
type ListAccountsAccountsAccountConnectionEdgesAccountEdge struct {
	// The item at the end of the edge.
	Node ListAccountsAccountsAccountConnectionEdgesAccountEdgeNodeAccount `json:"node"`
}

// GetNode returns ListAccountsAccountsAccountConnectionEdgesAccountEdge.Node, and is useful for accessing the field via an interface.
func (v *ListAccountsAccountsAccountConnectionEdgesAccountEdge) GetNode() ListAccountsAccountsAccountConnectionEdgesAccountEdgeNodeAccount {
	return v.Node
}

// ListAccountsAccountsAccountConnectionEdgesAccountEdgeNodeAccount includes the requested fields of the GraphQL type Account.
type ListAccountsAccountsAccountConnectionEdgesAccountEdgeNodeAccount struct {
	// Unique identifier of the account
	Id string `json:"id"`
	// Human-readable name within the organization
	Name string `json:"name"`
	// When the account was created
	CreatedAt time.Time `json:"createdAt"`
}

// GetId returns ListAccountsAccountsAccountConnectionEdgesAccountEdgeNodeAccount.Id, and is useful for accessing the field via an interface.
func (v *ListAccountsAccountsAccountConnectionEdgesAccountEdgeNodeAccount) GetId() string {
	return v.Id
}

// GetName returns ListAccountsAccountsAccountConnectionEdgesAccountEdgeNodeAccount.Name, and is useful for accessing the field via an interface.
func (v *ListAccountsAccountsAccountConnectionEdgesAccountEdgeNodeAccount) GetName() string {
	return v.Name
}

// GetCreatedAt returns ListAccountsAccountsAccountConnectionEdgesAccountEdgeNodeAccount.CreatedAt, and is useful for accessing the field via an interface.
func (v *ListAccountsAccountsAccountConnectionEdgesAccountEdgeNodeAccount) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// ListAccountsResponse is returned by ListAccounts on success.
type ListAccountsResponse struct {
	// Query accounts. Accounts belong to an organization and contain services and workspaces.
	Accounts ListAccountsAccountsAccountConnection `json:"accounts"`
}

// GetAccounts returns ListAccountsResponse.Accounts, and is useful for accessing the field via an interface.
func (v *ListAccountsResponse) GetAccounts() ListAccountsAccountsAccountConnection { return v.Accounts }

// ListOrganizationsOrganizationsOrganizationConnection includes the requested fields of the GraphQL type OrganizationConnection.
// The GraphQL type's documentation follows.
//
// A connection to a list of items.
type ListOrganizationsOrganizationsOrganizationConnection struct {
	// A list of edges.
	Edges []ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdge `json:"edges"`
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
}

// GetEdges returns ListOrganizationsOrganizationsOrganizationConnection.Edges, and is useful for accessing the field via an interface.
func (v *ListOrganizationsOrganizationsOrganizationConnection) GetEdges() []ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdge {
	return v.Edges
}

// GetTotalCount returns ListOrganizationsOrganizationsOrganizationConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *ListOrganizationsOrganizationsOrganizationConnection) GetTotalCount() int {
	return v.TotalCount
}

// ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdge includes the requested fields of the GraphQL type OrganizationEdge.
// The GraphQL type's documentation follows.
//
// An edge in a connection.
type ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdge struct {
	// The item at the end of the edge.
	Node ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdgeNodeOrganization `json:"node"`
}

// GetNode returns ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdge.Node, and is useful for accessing the field via an interface.
func (v *ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdge) GetNode() ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdgeNodeOrganization {
	return v.Node
}

// ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdgeNodeOrganization includes the requested fields of the GraphQL type Organization.
type ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdgeNodeOrganization struct {
	// Unique identifier of the organization
	Id string `json:"id"`
	// Human-readable name, unique across the system
	Name string `json:"name"`
	// When the organization was created
	CreatedAt time.Time `json:"createdAt"`
}

// GetId returns ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdgeNodeOrganization.Id, and is useful for accessing the field via an interface.
func (v *ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdgeNodeOrganization) GetId() string {
	return v.Id
}

// GetName returns ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdgeNodeOrganization.Name, and is useful for accessing the field via an interface.
func (v *ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdgeNodeOrganization) GetName() string {
	return v.Name
}

// GetCreatedAt returns ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdgeNodeOrganization.CreatedAt, and is useful for accessing the field via an interface.
func (v *ListOrganizationsOrganizationsOrganizationConnectionEdgesOrganizationEdgeNodeOrganization) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// ListOrganizationsResponse is returned by ListOrganizations on success.
type ListOrganizationsResponse struct {
	// Query organizations. An organization is the top-level container that holds accounts.
	Organizations ListOrganizationsOrganizationsOrganizationConnection `json:"organizations"`
}

// GetOrganizations returns ListOrganizationsResponse.Organizations, and is useful for accessing the field via an interface.
func (v *ListOrganizationsResponse) GetOrganizations() ListOrganizationsOrganizationsOrganizationConnection {
	return v.Organizations
}

// ListServicesResponse is returned by ListServices on success.
type ListServicesResponse struct {
	// Query services in your system.
	Services ListServicesServicesServiceConnection `json:"services"`
}

// GetServices returns ListServicesResponse.Services, and is useful for accessing the field via an interface.
func (v *ListServicesResponse) GetServices() ListServicesServicesServiceConnection { return v.Services }

// ListServicesServicesServiceConnection includes the requested fields of the GraphQL type ServiceConnection.
// The GraphQL type's documentation follows.
//
// A connection to a list of items.
type ListServicesServicesServiceConnection struct {
	// A list of edges.
	Edges []ListServicesServicesServiceConnectionEdgesServiceEdge `json:"edges"`
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
}

// GetEdges returns ListServicesServicesServiceConnection.Edges, and is useful for accessing the field via an interface.
func (v *ListServicesServicesServiceConnection) GetEdges() []ListServicesServicesServiceConnectionEdgesServiceEdge {
	return v.Edges
}

// GetTotalCount returns ListServicesServicesServiceConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *ListServicesServicesServiceConnection) GetTotalCount() int { return v.TotalCount }

// ListServicesServicesServiceConnectionEdgesServiceEdge includes the requested fields of the GraphQL type ServiceEdge.
// The GraphQL type's documentation follows.
//
// An edge in a connection.
type ListServicesServicesServiceConnectionEdgesServiceEdge struct {
	// The item at the end of the edge.
	Node ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService `json:"node"`
}

// GetNode returns ListServicesServicesServiceConnectionEdgesServiceEdge.Node, and is useful for accessing the field via an interface.
func (v *ListServicesServicesServiceConnectionEdgesServiceEdge) GetNode() ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService {
	return v.Node
}

// ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService includes the requested fields of the GraphQL type Service.
type ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService struct {
	// Unique identifier of the service
	Id string `json:"id"`
	// Service identifier in telemetry (e.g., 'checkout-service')
	Name string `json:"name"`
	// Description of service and telemetry characteristics
	Description string `json:"description"`
	// Whether telemetry analysis is enabled
	Enabled bool `json:"enabled"`
	// When the service was created
	CreatedAt time.Time `json:"createdAt"`
	// When the service was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// GetId returns ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService.Id, and is useful for accessing the field via an interface.
func (v *ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService) GetId() string {
	return v.Id
}

// GetName returns ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService.Name, and is useful for accessing the field via an interface.
func (v *ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService) GetName() string {
	return v.Name
}

// GetDescription returns ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService.Description, and is useful for accessing the field via an interface.
func (v *ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService) GetDescription() string {
	return v.Description
}

// GetEnabled returns ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService.Enabled, and is useful for accessing the field via an interface.
func (v *ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService) GetEnabled() bool {
	return v.Enabled
}

// GetCreatedAt returns ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService.CreatedAt, and is useful for accessing the field via an interface.
func (v *ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// GetUpdatedAt returns ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService.UpdatedAt, and is useful for accessing the field via an interface.
func (v *ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

type ValidateDatadogApiKeyInput struct {
	ApiKey string             `json:"apiKey"`
	Site   DatadogAccountSite `json:"site"`
}

// GetApiKey returns ValidateDatadogApiKeyInput.ApiKey, and is useful for accessing the field via an interface.
func (v *ValidateDatadogApiKeyInput) GetApiKey() string { return v.ApiKey }

// GetSite returns ValidateDatadogApiKeyInput.Site, and is useful for accessing the field via an interface.
func (v *ValidateDatadogApiKeyInput) GetSite() DatadogAccountSite { return v.Site }

// ValidateDatadogApiKeyResponse is returned by ValidateDatadogApiKey on success.
type ValidateDatadogApiKeyResponse struct {
	ValidateDatadogApiKey ValidateDatadogApiKeyValidateDatadogApiKeyValidateDatadogApiKeyResult `json:"validateDatadogApiKey"`
}

// GetValidateDatadogApiKey returns ValidateDatadogApiKeyResponse.ValidateDatadogApiKey, and is useful for accessing the field via an interface.
func (v *ValidateDatadogApiKeyResponse) GetValidateDatadogApiKey() ValidateDatadogApiKeyValidateDatadogApiKeyValidateDatadogApiKeyResult {
	return v.ValidateDatadogApiKey
}

// ValidateDatadogApiKeyValidateDatadogApiKeyValidateDatadogApiKeyResult includes the requested fields of the GraphQL type ValidateDatadogApiKeyResult.
type ValidateDatadogApiKeyValidateDatadogApiKeyValidateDatadogApiKeyResult struct {
	Valid bool   `json:"valid"`
	Error string `json:"error"`
}

// GetValid returns ValidateDatadogApiKeyValidateDatadogApiKeyValidateDatadogApiKeyResult.Valid, and is useful for accessing the field via an interface.
func (v *ValidateDatadogApiKeyValidateDatadogApiKeyValidateDatadogApiKeyResult) GetValid() bool {
	return v.Valid
}

// GetError returns ValidateDatadogApiKeyValidateDatadogApiKeyValidateDatadogApiKeyResult.Error, and is useful for accessing the field via an interface.
func (v *ValidateDatadogApiKeyValidateDatadogApiKeyValidateDatadogApiKeyResult) GetError() string {
	return v.Error
}

// __CreateAccountInput is used internally by genqlient
type __CreateAccountInput struct {
	Input CreateAccountInput `json:"input"`
}

// GetInput returns __CreateAccountInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateAccountInput) GetInput() CreateAccountInput { return v.Input }

// __CreateDatadogAccountWithCredentialsInput is used internally by genqlient
type __CreateDatadogAccountWithCredentialsInput struct {
	Input CreateDatadogAccountWithCredentialsInput `json:"input"`
}

// GetInput returns __CreateDatadogAccountWithCredentialsInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateDatadogAccountWithCredentialsInput) GetInput() CreateDatadogAccountWithCredentialsInput {
	return v.Input
}

// __CreateOrganizationAndBootstrapInput is used internally by genqlient
type __CreateOrganizationAndBootstrapInput struct {
	Input CreateOrganizationInput `json:"input"`
}

// GetInput returns __CreateOrganizationAndBootstrapInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateOrganizationAndBootstrapInput) GetInput() CreateOrganizationInput { return v.Input }

// __EnableServiceInput is used internally by genqlient
type __EnableServiceInput struct {
	ServiceId string `json:"serviceId"`
}

// GetServiceId returns __EnableServiceInput.ServiceId, and is useful for accessing the field via an interface.
func (v *__EnableServiceInput) GetServiceId() string { return v.ServiceId }

// __GetAccountInput is used internally by genqlient
type __GetAccountInput struct {
	Id string `json:"id"`
}

// GetId returns __GetAccountInput.Id, and is useful for accessing the field via an interface.
func (v *__GetAccountInput) GetId() string { return v.Id }

// __GetDatadogAccountLogDiscoveryProgressInput is used internally by genqlient
type __GetDatadogAccountLogDiscoveryProgressInput struct {
	Id string `json:"id"`
}

// GetId returns __GetDatadogAccountLogDiscoveryProgressInput.Id, and is useful for accessing the field via an interface.
func (v *__GetDatadogAccountLogDiscoveryProgressInput) GetId() string { return v.Id }

// __GetDatadogAccountServiceDiscoveryProgressInput is used internally by genqlient
type __GetDatadogAccountServiceDiscoveryProgressInput struct {
	Id string `json:"id"`
}

// GetId returns __GetDatadogAccountServiceDiscoveryProgressInput.Id, and is useful for accessing the field via an interface.
func (v *__GetDatadogAccountServiceDiscoveryProgressInput) GetId() string { return v.Id }

// __GetServiceByNameInput is used internally by genqlient
type __GetServiceByNameInput struct {
	Name string `json:"name"`
}

// GetName returns __GetServiceByNameInput.Name, and is useful for accessing the field via an interface.
func (v *__GetServiceByNameInput) GetName() string { return v.Name }

// __GetServiceInput is used internally by genqlient
type __GetServiceInput struct {
	Id string `json:"id"`
}

// GetId returns __GetServiceInput.Id, and is useful for accessing the field via an interface.
func (v *__GetServiceInput) GetId() string { return v.Id }

// __ListAccountsInput is used internally by genqlient
type __ListAccountsInput struct {
	OrganizationID string `json:"organizationID"`
}

// GetOrganizationID returns __ListAccountsInput.OrganizationID, and is useful for accessing the field via an interface.
func (v *__ListAccountsInput) GetOrganizationID() string { return v.OrganizationID }

// __ValidateDatadogApiKeyInput is used internally by genqlient
type __ValidateDatadogApiKeyInput struct {
	Input ValidateDatadogApiKeyInput `json:"input"`
}

// GetInput returns __ValidateDatadogApiKeyInput.Input, and is useful for accessing the field via an interface.
func (v *__ValidateDatadogApiKeyInput) GetInput() ValidateDatadogApiKeyInput { return v.Input }

// The mutation executed by CreateAccount.
const CreateAccount_Operation = `
mutation CreateAccount ($input: CreateAccountInput!) {
	createAccount(input: $input) {
		id
		name
		createdAt
	}
}
`

func CreateAccount(
	ctx_ context.Context,
	client_ graphql.Client,
	input CreateAccountInput,
) (data_ *CreateAccountResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateAccount",
		Query:  CreateAccount_Operation,
		Variables: &__CreateAccountInput{
			Input: input,
		},
	}

	data_ = &CreateAccountResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateDatadogAccountWithCredentials.
const CreateDatadogAccountWithCredentials_Operation = `
mutation CreateDatadogAccountWithCredentials ($input: CreateDatadogAccountWithCredentialsInput!) {
	createDatadogAccount(input: $input) {
		id
		name
		site
		createdAt
		updatedAt
	}
}
`

func CreateDatadogAccountWithCredentials(
	ctx_ context.Context,
	client_ graphql.Client,
	input CreateDatadogAccountWithCredentialsInput,
) (data_ *CreateDatadogAccountWithCredentialsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateDatadogAccountWithCredentials",
		Query:  CreateDatadogAccountWithCredentials_Operation,
		Variables: &__CreateDatadogAccountWithCredentialsInput{
			Input: input,
		},
	}

	data_ = &CreateDatadogAccountWithCredentialsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateOrganizationAndBootstrap.
const CreateOrganizationAndBootstrap_Operation = `
mutation CreateOrganizationAndBootstrap ($input: CreateOrganizationInput!) {
	createOrganizationAndBootstrap(input: $input) {
		organization {
			id
			name
			createdAt
		}
		account {
			id
			name
		}
		workspace {
			id
			name
		}
	}
}
`

func CreateOrganizationAndBootstrap(
	ctx_ context.Context,
	client_ graphql.Client,
	input CreateOrganizationInput,
) (data_ *CreateOrganizationAndBootstrapResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateOrganizationAndBootstrap",
		Query:  CreateOrganizationAndBootstrap_Operation,
		Variables: &__CreateOrganizationAndBootstrapInput{
			Input: input,
		},
	}

	data_ = &CreateOrganizationAndBootstrapResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by EnableService.
const EnableService_Operation = `
mutation EnableService ($serviceId: ID!) {
	updateService(id: $serviceId, input: {enabled:true}) {
		id
		name
		enabled
	}
}
`

// Mutation to enable a service for analysis
func EnableService(
	ctx_ context.Context,
	client_ graphql.Client,
	serviceId string,
) (data_ *EnableServiceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "EnableService",
		Query:  EnableService_Operation,
		Variables: &__EnableServiceInput{
			ServiceId: serviceId,
		},
	}

	data_ = &EnableServiceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetAccount.
const GetAccount_Operation = `
query GetAccount ($id: ID!) {
	accounts(where: {id:$id}, first: 1) {
		edges {
			node {
				id
				datadogAccount {
					id
					name
					site
				}
			}
		}
	}
}
`

func GetAccount(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *GetAccountResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetAccount",
		Query:  GetAccount_Operation,
		Variables: &__GetAccountInput{
			Id: id,
		},
	}

	data_ = &GetAccountResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetDatadogAccountLogDiscoveryProgress.
const GetDatadogAccountLogDiscoveryProgress_Operation = `
query GetDatadogAccountLogDiscoveryProgress ($id: ID!) {
	datadogAccounts(where: {id:$id}, first: 1) {
		edges {
			node {
				id
				logEventDiscoveryProgress {
					status
					percentComplete
					weeklyVolume
					weeklyDiscoveredVolume
					lastError
					startedAt
					completedAt
					consecutiveFailures
				}
			}
		}
	}
}
`

func GetDatadogAccountLogDiscoveryProgress(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *GetDatadogAccountLogDiscoveryProgressResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetDatadogAccountLogDiscoveryProgress",
		Query:  GetDatadogAccountLogDiscoveryProgress_Operation,
		Variables: &__GetDatadogAccountLogDiscoveryProgressInput{
			Id: id,
		},
	}

	data_ = &GetDatadogAccountLogDiscoveryProgressResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetDatadogAccountServiceDiscoveryProgress.
const GetDatadogAccountServiceDiscoveryProgress_Operation = `
query GetDatadogAccountServiceDiscoveryProgress ($id: ID!) {
	datadogAccounts(where: {id:$id}, first: 1) {
		edges {
			node {
				id
				serviceDiscoveryProgress {
					status
					servicesDiscovered
					lastError
					startedAt
					completedAt
					consecutiveFailures
				}
			}
		}
	}
}
`

func GetDatadogAccountServiceDiscoveryProgress(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *GetDatadogAccountServiceDiscoveryProgressResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetDatadogAccountServiceDiscoveryProgress",
		Query:  GetDatadogAccountServiceDiscoveryProgress_Operation,
		Variables: &__GetDatadogAccountServiceDiscoveryProgressInput{
			Id: id,
		},
	}

	data_ = &GetDatadogAccountServiceDiscoveryProgressResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetService.
const GetService_Operation = `
query GetService ($id: ID!) {
	node(id: $id) {
		__typename
		... on Service {
			id
			name
			description
			enabled
			createdAt
			updatedAt
			account {
				id
				name
			}
			logEvents {
				id
				name
				description
				createdAt
			}
		}
	}
}
`

// Query to get detailed information about a specific service by ID
func GetService(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *GetServiceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetService",
		Query:  GetService_Operation,
		Variables: &__GetServiceInput{
			Id: id,
		},
	}

	data_ = &GetServiceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetServiceByName.
const GetServiceByName_Operation = `
query GetServiceByName ($name: String!) {
	services(where: {name:$name}, first: 1) {
		edges {
			node {
				id
				name
				description
				enabled
				createdAt
				updatedAt
			}
		}
	}
}
`

// Query to get service by name
func GetServiceByName(
	ctx_ context.Context,
	client_ graphql.Client,
	name string,
) (data_ *GetServiceByNameResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetServiceByName",
		Query:  GetServiceByName_Operation,
		Variables: &__GetServiceByNameInput{
			Name: name,
		},
	}

	data_ = &GetServiceByNameResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListAccounts.
const ListAccounts_Operation = `
query ListAccounts ($organizationID: ID!) {
	accounts(where: {organizationID:$organizationID}) {
		edges {
			node {
				id
				name
				createdAt
			}
		}
		totalCount
	}
}
`

func ListAccounts(
	ctx_ context.Context,
	client_ graphql.Client,
	organizationID string,
) (data_ *ListAccountsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListAccounts",
		Query:  ListAccounts_Operation,
		Variables: &__ListAccountsInput{
			OrganizationID: organizationID,
		},
	}

	data_ = &ListAccountsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListOrganizations.
const ListOrganizations_Operation = `
query ListOrganizations {
	organizations {
		edges {
			node {
				id
				name
				createdAt
			}
		}
		totalCount
	}
}
`

func ListOrganizations(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *ListOrganizationsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListOrganizations",
		Query:  ListOrganizations_Operation,
	}

	data_ = &ListOrganizationsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListServices.
const ListServices_Operation = `
query ListServices {
	services(first: 100) {
		edges {
			node {
				id
				name
				description
				enabled
				createdAt
				updatedAt
			}
		}
		totalCount
	}
}
`

// Query to list all services with basic information
func ListServices(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *ListServicesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListServices",
		Query:  ListServices_Operation,
	}

	data_ = &ListServicesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by ValidateDatadogApiKey.
const ValidateDatadogApiKey_Operation = `
mutation ValidateDatadogApiKey ($input: ValidateDatadogApiKeyInput!) {
	validateDatadogApiKey(input: $input) {
		valid
		error
	}
}
`

func ValidateDatadogApiKey(
	ctx_ context.Context,
	client_ graphql.Client,
	input ValidateDatadogApiKeyInput,
) (data_ *ValidateDatadogApiKeyResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ValidateDatadogApiKey",
		Query:  ValidateDatadogApiKey_Operation,
		Variables: &__ValidateDatadogApiKeyInput{
			Input: input,
		},
	}

	data_ = &ValidateDatadogApiKeyResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
