name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.sha }}
  cancel-in-progress: false

jobs:
  checks:
    uses: ./.github/workflows/_go-checks.yaml
    secrets: inherit
