name: Nightly

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/_go-checks.yaml
    with:
      run-powersync-replay: true
    secrets: inherit
