name: PR CI

on:
  pull_request:
    branches: [master, arch-reset]
  merge_group:
    branches: [master, arch-reset]
  workflow_dispatch:

concurrency:
  group: pr-ci-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  required-checks:
    name: required-checks
    uses: ./.github/workflows/_go-checks.yaml
    secrets: inherit
