// Package chat provides a client for the stateless Chat API.
//
// The Chat API is a pure function: f(messages, context) → stream of blocks.
// It doesn't read or write messages to any database. The client sends the
// full conversation history on every request and receives a streamed response.
//
// Message persistence is handled separately by the caller.
package chat

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/hashicorp/go-retryablehttp"
	"github.com/usetero/cli/internal/auth"
	"github.com/usetero/cli/internal/domain"
	"github.com/usetero/cli/internal/log"
)

const (
	retryMax     = 3
	retryWaitMin = 100 * time.Millisecond
	retryWaitMax = 2 * time.Second
)

// HTTPDoer is the interface for making HTTP requests.
type HTTPDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// StreamMetadata contains post-stream metadata from the Chat API.
type StreamMetadata struct {
	Title         string // AI-generated conversation title, set after first exchange
	ContextWindow int    // Model's max token capacity (from message_start)
	InputTokens   int    // Tokens consumed by input this turn (from message_stop)
	OutputTokens  int    // Tokens generated by output this turn (from message_stop)
}

// StreamResult captures everything the stream produced.
type StreamResult struct {
	Message  *domain.Message
	Metadata *StreamMetadata // nil if no metadata_update event was received
}

// Client sends messages to the Chat API and streams responses.
type Client interface {
	// Stream sends the conversation to the Chat API and streams the response.
	// The onMessage callback is called each time the message is updated with new content.
	// The returned StreamResult contains the final message and any metadata.
	Stream(ctx context.Context, req Request, onMessage func(*domain.Message)) (*StreamResult, error)

	// SetAccountID sets the account ID for requests.
	SetAccountID(accountID domain.AccountID)
}

// client is the concrete implementation of Client.
type client struct {
	endpoint    string
	httpClient  HTTPDoer
	auth        auth.Auth
	accountID   domain.AccountID
	scope       log.Scope
	globalTools []Tool
}

// Ensure client implements Client.
var _ Client = (*client)(nil)

// NewClient creates a new Chat API client.
// - globalTools are included in every request automatically
// - Retries transient errors (connection reset, 502/503/504) up to 3 times with backoff
// - Gets a fresh token via auth.GetAccessToken before each request
func NewClient(endpoint string, authService auth.Auth, scope log.Scope, globalTools []Tool) Client {
	retryClient := retryablehttp.NewClient()
	retryClient.RetryMax = retryMax
	retryClient.RetryWaitMin = retryWaitMin
	retryClient.RetryWaitMax = retryWaitMax
	retryClient.Logger = nil

	return &client{
		endpoint:    strings.TrimSuffix(endpoint, "/"),
		httpClient:  retryClient.StandardClient(),
		auth:        authService,
		scope:       scope.Child("chat"),
		globalTools: globalTools,
	}
}

// NewClientWithHTTP creates a new Chat API client with a custom HTTP client (for testing).
func NewClientWithHTTP(endpoint string, authService auth.Auth, httpClient HTTPDoer, scope log.Scope, globalTools []Tool) Client {
	return &client{
		endpoint:    strings.TrimSuffix(endpoint, "/"),
		httpClient:  httpClient,
		auth:        authService,
		scope:       scope.Child("chat"),
		globalTools: globalTools,
	}
}

// SetAccountID sets the account ID for requests.
func (c *client) SetAccountID(accountID domain.AccountID) {
	c.accountID = accountID
}

// Stream sends the conversation to the Chat API and streams the response.
// The onMessage callback is called each time the message is updated with new content.
// Global tools are automatically merged with any request-specific tools.
func (c *client) Stream(ctx context.Context, req Request, onMessage func(*domain.Message)) (*StreamResult, error) {
	// Merge global tools with request-specific tools
	allTools := append(c.globalTools, req.Tools...)
	req.Tools = allTools

	url := c.endpoint + "/api/chat/v1/messages"

	c.scope.Debug("sending to chat API",
		log.String("url", url),
		log.String("conversation_id", req.ConversationID),
		log.Int("message_count", len(req.Messages)),
		log.Int("context_count", len(req.Context)),
		log.Int("tool_count", len(req.Tools)),
	)

	// Get fresh token for this request
	token, err := c.auth.GetAccessToken(ctx)
	if err != nil {
		c.scope.Error("failed to get access token", "error", err)
		return nil, fmt.Errorf("get access token: %w", err)
	}

	// Log token metadata for debugging auth issues
	if claims, parseErr := parseTokenAudience(token); parseErr == nil {
		c.scope.Debug("token acquired",
			log.String("sub", claims.sub),
			log.String("aud", strings.Join(claims.aud, ", ")),
			log.String("org_id", claims.orgID),
			log.Bool("expired", claims.expired),
		)
	}

	body, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}

	c.setHeaders(httpReq, token)

	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		c.scope.Error("request failed", "error", err, "url", url)
		return nil, fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		c.scope.Error("chat API returned error",
			log.Int("status", resp.StatusCode),
			log.String("url", url),
			log.String("body", string(respBody)),
			log.String("account_id", c.accountID.String()),
		)
		return nil, fmt.Errorf("chat API error %d: %s", resp.StatusCode, string(respBody))
	}

	contentType := resp.Header.Get("Content-Type")
	if !strings.HasPrefix(contentType, "text/event-stream") {
		respBody, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("expected text/event-stream, got %s: %s", contentType, string(respBody))
	}

	// Use internal accumulator to build the message from events
	acc := newAccumulator()

	err = readStream(resp.Body, func(e event) error {
		acc.handle(e)
		if onMessage != nil {
			onMessage(acc.message())
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	result := &StreamResult{
		Message: acc.message(),
	}
	if acc.title != "" || acc.contextWindow > 0 || acc.inputTokens > 0 {
		result.Metadata = &StreamMetadata{
			Title:         acc.title,
			ContextWindow: acc.contextWindow,
			InputTokens:   acc.inputTokens,
			OutputTokens:  acc.outputTokens,
		}
	}

	return result, nil
}

func (c *client) setHeaders(req *http.Request, token string) {
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "text/event-stream")
	req.Header.Set("Authorization", "Bearer "+token)
	if c.accountID != "" {
		req.Header.Set("X-Account-ID", c.accountID.String())
	}
}

// tokenClaims holds the subset of JWT claims we log for debugging.
type tokenClaims struct {
	sub     string
	aud     []string
	orgID   string
	expired bool
}

// parseTokenAudience extracts key claims from a JWT without signature verification.
func parseTokenAudience(token string) (tokenClaims, error) {
	parts := strings.SplitN(token, ".", 3)
	if len(parts) != 3 {
		return tokenClaims{}, fmt.Errorf("invalid JWT format")
	}
	payload, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return tokenClaims{}, err
	}
	var raw struct {
		Sub   string   `json:"sub"`
		Aud   []string `json:"aud"`
		OrgID string   `json:"org_id"`
		Exp   int64    `json:"exp"`
	}
	if err := json.Unmarshal(payload, &raw); err != nil {
		return tokenClaims{}, err
	}
	return tokenClaims{
		sub:     raw.Sub,
		aud:     raw.Aud,
		orgID:   raw.OrgID,
		expired: raw.Exp > 0 && time.Now().Unix() > raw.Exp,
	}, nil
}
